docs(cn): translate content/docs/hooks-reference.md into Chinese
reactjs/zh-hans.reactjs.org pull request #1018
Opened 2023-01-05 12:04 UTC by baijinping

translate `hooks-reference.md#batching-of-state-updates-batching-of-state-updates` into Chinese

2023-01-12 03:12 UTC, baijinping commented
看不到Vercel failed的详情,提示404 :<
在本地可以正常build和展示

2023-02-22 09:21 UTC, daochouwangu requested changes

2023-02-24 06:07 UTC, baijinping commented on content/docs/hooks-reference.md
> +在 React v18 之前，只有在 React 事件处理函数中的更新会被合并提交。从 React v18 开始， [合并更新默认在所有更新操作中启用](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching) 。请注意， React 确保来自多个 *不同* 用户触发事件的更新 —— 例如，点击按钮两次 —— 各自独立处理，
结合原文后边的举例, 理解起来应该不难. 主要这个`user-initiated`事件, 不知道是不是指`isTrusted=true`的事件, 是也没法加译者注...

2023-02-24 11:11 UTC, awxiaoxian2020 requested changes

2023-02-24 11:11 UTC, awxiaoxian2020 commented on content/docs/hooks-reference.md
> +在极少数情况下，你需要强制以同步方式更新 DOM ，此时可以用 [`flushSync`](/docs/react-dom.html#flushsync) 将其包裹。不过这可能会影响性能，所以只在必要时使用这种方式。
```suggestion
在极少数情况下，你需要强制以同步方式更新 DOM，此时可以用 [`flushSync`](/docs/react-dom.html#flushsync) 将其包裹。不过这可能会影响性能，所以只在必要时使用这种方式。
```

2023-02-24 11:11 UTC, awxiaoxian2020 commented on content/docs/hooks-reference.md
> +在 React v18 之前，只有在 React 事件处理函数中的更新会被合并提交。从 React v18 开始， [合并更新默认在所有更新操作中启用](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching) 。注意，React 不会合并来自*不同* `user-initiated` 事件的更新。 例如，点击按钮两次，将被
```suggestion
在 React v18 之前，只有在 React 事件处理函数中的更新会被合并提交。从 React v18 开始， [合并更新默认在所有更新操作中启用](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching) 。注意，React 确保不同的“用户发起事件”（例如连续点击按钮）的更新始终各自独立处理，不会被批量处理。这可以避免逻辑上的错误。
```
@daochouwangu 你觉得怎么样？

2023-02-24 15:31 UTC, daochouwangu commented on content/docs/hooks-reference.md
> +在 React v18 之前，只有在 React 事件处理函数中的更新会被合并提交。从 React v18 开始， [合并更新默认在所有更新操作中启用](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching) 。注意，React 不会合并来自*不同* `user-initiated` 事件的更新。 例如，点击按钮两次，将被
LGTM

2023-02-24 15:31 UTC, daochouwangu approved these changes

2023-02-25 01:07 UTC, awxiaoxian2020 approved these changes

2023-02-25 08:58 UTC, baijinping commented on content/docs/hooks-reference.md
> +在 React v18 之前，只有在 React 事件处理函数中的更新会被合并提交。从 React v18 开始， [合并更新默认在所有更新操作中启用](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching) 。注意，React 不会合并来自*不同* `user-initiated` 事件的更新。 例如，点击按钮两次，将被
LGTM+1

2023-02-28 01:02 UTC, daochouwangu approved these changes

2023-02-28 01:13 UTC, merged