docs(cn): translate pages/learn/adding-interactivity.md into Chinese
reactjs/zh-hans.reactjs.org pull request #1053
Opened 2023-02-13 16:32 UTC by awxiaoxian2020

Co-Authored-By: QiChang Li <github@liqichang.com>

close #605

2023-02-14 05:51 UTC, daochouwangu requested changes
翻译优化

2023-02-14 05:51 UTC, daochouwangu commented on beta/src/content/learn/adding-interactivity.md
> +界面上的控件会根据用户的输入而更新。例如，点击按钮切换轮播图的展示。在 React 中，随时间变化的数据被称为状态（state）。你可以向任何组件添加状态，并按需进行更新。在本章节中，你将学习如何编写处理交互的组件，更新它们的状态，并根据时间变化展示显示不同的效果。
```suggestion
界面上的控件会根据用户的输入而更新。例如，点击按钮切换轮播图的展示。在 React 中，随时间变化的数据被称为状态（state）。你可以向任何组件添加状态，并按需进行更新。在本章节中，你将学习如何编写处理交互的组件，更新它们的状态，并根据时间变化显示不同的效果。
```

2023-02-14 05:51 UTC, daochouwangu commented on beta/src/content/learn/adding-interactivity.md
> +你可以用 [`useState`](/reference/usestate) Hook 为组件添加状态。Hook 是能让你的组件使用 React 功能的特殊函数（状态是这些功能之一）。`useState` Hook 让你声明一个状态变量。它接收初始状态并返回一对值：当前状态，以及一个让你更新状态的状态设置函数。
```suggestion
你可以用 [`useState`](/reference/usestate) Hook 为组件添加状态。*Hooks* 是能让你的组件使用 React 功能的特殊函数（状态是这些功能之一）。`useState` Hook 让你声明一个状态变量。它接收初始状态并返回一对值：当前状态，以及一个让你更新状态的设置函数。
```

2023-02-14 05:51 UTC, daochouwangu commented on beta/src/content/learn/adding-interactivity.md
> +想象一下，你的组件是厨房里的厨师，用食材制作出美味的菜肴。在这个场景中，React 是服务员，负责提出顾客的要求，并带来他们订单。这个请求和服务 UI 的过程有三个步骤：
```suggestion
想象一下，你的组件是厨房里的厨师，用食材制作出美味的菜肴。在这个场景中，React 是服务员，负责提出顾客的要求，并给顾客上菜。这个请求和服务 UI 的过程有三个步骤：
```

2023-02-14 05:51 UTC, daochouwangu commented on beta/src/content/learn/adding-interactivity.md
> +2. **渲染**组件（接到厨房的订单）
```suggestion
2. **渲染**组件（在厨房准备订单）
```

2023-02-14 05:51 UTC, daochouwangu commented on beta/src/content/learn/adding-interactivity.md
> +状态可以持有任何类型的 JavaScript 值，包括对象。但你不应该直接改变你在 React 状态中持有的对象和数组。相反，当你想更新一个对象和数组时，你需要创建一个新的对象（或复制现有的对象），然后更新状态以使用该副本。
```suggestion
状态可以持有任何类型的 JavaScript 值，包括对象。但你不应该直接改变你在 React 状态中持有的对象和数组。相反，当你想更新一个对象和数组时，你需要创建一个新的对象（或复制现有的对象），然后用这个副本来更新状态。
```

2023-02-14 05:51 UTC, daochouwangu commented on beta/src/content/learn/adding-interactivity.md
> +数组是另一种可以存在状态中的可变 JavaScript 对象，应将其视为只读。就像对象一样，当你想更新存在状态中的数组时，你需要创建一个新数组（或者复制现有数组），然后设置状态以使用新数组：
```suggestion
数组是另一种可以存在状态中的可变 JavaScript 对象，应将其视为只读。就像对象一样，当你想更新存在状态中的数组时，你需要创建一个新数组（或者复制现有数组），然后用新数组来更新状态。
```

2023-02-14 05:59 UTC, awxiaoxian2020 commented on beta/src/content/learn/adding-interactivity.md
> +你可以用 [`useState`](/reference/usestate) Hook 为组件添加状态。Hook 是能让你的组件使用 React 功能的特殊函数（状态是这些功能之一）。`useState` Hook 让你声明一个状态变量。它接收初始状态并返回一对值：当前状态，以及一个让你更新状态的状态设置函数。
Edit：Hook 应为单数。参见 https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97#%E8%8B%B1%E6%96%87

2023-02-21 01:20 UTC, daochouwangu submitted a review, later dismissed

2023-03-20 10:29 UTC, merged