fix: change the previous English link to Chinese link
reactjs/zh-hans.reactjs.org pull request #1060
Opened 2023-02-15 06:12 UTC by Sunny-117

之前提交过的pr：https://github.com/reactjs/zh-hans.reactjs.org/commit/3d5698e68f3d60e54356b884e001c08382d710dd

此次pr是为了将所有的英文链接转移到中文

2023-02-15 07:02 UTC, awxiaoxian2020 commented
有些 MDN 页面中文翻译没有对应页面，是否统一需要讨论。

2023-02-15 07:53 UTC, Sunny-117 commented
> 有些 MDN 页面中文翻译没有对应页面，是否统一需要讨论。

没有翻译的-继续用原地址
等翻译完成再替换？

我建议中文文档跳转link应该尽量转去中文，体验好一些

2023-02-15 08:00 UTC, awxiaoxian2020 commented
> 没有翻译的-继续用原地址
> 等翻译完成再替换？

@Sunny-117 理论上应该这样做，但是工作量有点大

2023-02-16 06:02 UTC, daochouwangu requested changes
The archive url shouldn't change

2023-02-16 06:02 UTC, daochouwangu commented on content/blog/2017-11-28-react-v16.2.0-fragment-support.md
> +Fragment syntax in JSX was inspired by prior art such as the `XMLList() <></>` constructor in [E4X](https://web.archive.org/web/20201019115828/https://developer.mozilla.org/zh-CN/docs/Archive/Web/E4X
```suggestion
Fragment syntax in JSX was inspired by prior art such as the `XMLList() <></>` constructor in [E4X](https://web.archive.org/web/20201019115828/https://developer.mozilla.org/en-US/docs/Archive/Web/E4X/E4X_for_templating). Using a pair of empty tags is meant to represent the idea it won't add an actual element to the DOM.
```

2023-02-21 01:21 UTC, daochouwangu approved these changes

2023-03-20 06:51 UTC, awxiaoxian2020 commented
最近文档的变化是比较大的，建议过一段时间，根据最新的目录，重新发起 Pull Request.

2023-03-20 06:51 UTC, closed without merging