docs(cn): translate the home page
reactjs/zh-hans.reactjs.org pull request #1087
Opened 2023-03-20 13:40 UTC by daochouwangu

translate the home page
翻译首页

2023-03-20 13:43 UTC, daochouwangu commented on src/components/Layout/HomeContent.js
> +                您的组织可以抹平平台差异，并形成拥有端到端的全部功能的团队。
是否有更好的？

2023-03-20 13:45 UTC, daochouwangu reviewed
编辑器自动换行，不知道是不是我配置的问题，网页显示是正常的。

2023-03-21 00:55 UTC, awxiaoxian2020 requested changes

2023-03-21 00:55 UTC, awxiaoxian2020 commented on src/components/Layout/HomeContent.js
> +                    React。一些研究需要数年才能得到回报。 React
```suggestion
                    React。一些研究需要数年才能得到回报。React
```

2023-03-21 02:09 UTC, daochouwangu commented on src/components/Layout/HomeContent.js
> +              也是一种架构。实现它的框架可以从运行时甚至构建期间的异步组件中获取数据，或从文件或数据库读取数据，并将其传递给交互式组件。
原文是‘on the server’. 重点应该是 Server React Component. 运行时是个服务端和客户端都有的概念。

2023-03-21 03:10 UTC, awxiaoxian2020 commented on src/components/Layout/HomeContent.js
> +              也是一种架构。实现它的框架可以从运行时甚至构建期间的异步组件中获取数据，或从文件或数据库读取数据，并将其传递给交互式组件。
我修改了相关表述。另外为了导航的一致性，`参考文档` 统一为 `参考`

2023-03-21 05:32 UTC, QC-L commented on src/components/Layout/HomeContent.js
> +            一个构建 Web 和原生用户界面的库
用于构建 Web 和原生交互界面的库

2023-03-21 05:32 UTC, QC-L commented on src/components/Layout/HomeContent.js
> +            一个构建 Web 和原生用户界面的库
感觉这样会好一点

2023-03-21 05:33 UTC, QC-L commented on src/components/Layout/HomeContent.js
> +            一个构建 Web 和原生用户界面的库
```suggestion
            用于构建 Web 和原生交互界面的库
```

2023-03-21 07:49 UTC, Yucohny commented on src/components/Layout/HomeContent.js
> +                          Web 视图——你的 React 组件由平台提供的真实 Android 或
这个地方应该是破折号「——」而不是两个短横线吧？

2023-03-21 07:49 UTC, Yucohny commented on src/components/Layout/HomeContent.js
> +                          真正的原生
```suggestion
                          开发真正的原生应用程序
```

2023-03-21 09:34 UTC, awxiaoxian2020 commented on src/components/Layout/HomeContent.js
> +                          Web 视图——你的 React 组件由平台提供的真实 Android 或
这里好像就是破折号，手机上看可能有问题

2023-03-21 10:36 UTC, awxiaoxian2020 approved these changes

2023-03-21 11:13 UTC, Yucohny approved these changes

2023-03-21 11:14 UTC, merged