docs(cn): translate the  reference/react/lazy page
reactjs/zh-hans.reactjs.org pull request #1101
Opened 2023-03-25 10:28 UTC by Davont

翻译 the  reference/react/lazy 页面

@QC-L @awxiaoxian2020  
辛苦检视！

2023-03-25 22:43 UTC, awxiaoxian2020 requested changes
文中使用“您”的地方无特殊情况请改成“你”。

2023-03-25 22:43 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +[请看下面的更多例子。](#usage)
```suggestion
[请看下面的更多例子。](#usage)

```

2023-03-25 22:43 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +* `load`: 一个返回 [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) 或另一个 *thenable*（具有 `then` 方法的类 Promise 对象）的函数。在你尝试第一次渲染返回的组件之前，React 是不会调用 load 函数的。
```suggestion
* `load`: 一个返回 [Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise) 或另一个 *thenable*（具有 `then` 方法的类 Promise 对象）的函数。在你尝试第一次渲染返回的组件之前，React 是不会调用 load 函数的。在 React 首次调用 `load` 后，它将等待其解析，然后将解析值渲染成 React 组件。返回的 Promise 和 Promise 的解析值都将被缓存，因此 React 不会多次调用 `load` 函数。如果 Promise 被拒绝，则 React 将 `throw` 抛出最近错误边界处理程序的拒绝原因。
```

2023-03-25 22:43 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +此代码依赖于动态 [动态 `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)，可能需要你的打包工具或框架提供支持。
```suggestion
此代码依赖于 [动态 `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)，可能需要你的打包工具或框架提供支持。
```

2023-03-26 03:10 UTC, daochouwangu requested changes

2023-03-26 03:10 UTC, daochouwangu commented on src/content/reference/react/lazy.md
> +* `load`: 一个返回 [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) 或另一个 *thenable*（具有 `then` 方法的类 Promise 对象）的函数。在你尝试第一次渲染返回的组件之前，React 是不会调用 load 函数的。
```suggestion
* `load`: 一个返回 [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) 或另一个 *thenable*（具有 `then` 方法的类 Promise 对象）的函数。在你尝试第一次渲染返回的组件之前，React 是不会调用 load 函数的。在 React 首次调用 `load` 后，它将等待其解析，然后将解析值渲染成 React 组件。返回的 Promise 和 Promise 的解析值都将被缓存，因此 React 不会多次调用 `load` 函数。如果 Promise 被拒绝，则 React 将抛出拒绝原因给最近的错误边界处理。
```

2023-03-26 05:22 UTC, awxiaoxian2020 requested changes

2023-03-26 05:22 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +`lazy` 可以让你推迟加载组件的代码，直到它第一次被渲染。
```suggestion
`lazy` 可以能够在组件第一次被渲染之前推迟加载组件的代码。
```
这样会不会好一点？

2023-03-26 05:22 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +`lazy` 返回一个 React 组件，你可以在 fiber 树中渲染。当懒加载组件的代码仍在加载时，尝试渲染它将会处于 *暂停* 状态。使用 [`<Suspense>`](/reference/react/Suspense) 在其加载时显示一个加载指示器。
```suggestion
`lazy` 返回一个 React 组件，你可以在 fiber 树中渲染。当懒加载组件的代码仍在加载时，尝试渲染它将会处于 *暂停* 状态。使用 [`<Suspense>`](/reference/react/Suspense) 可以在其加载时显示一个正在加载的提示。
```

2023-03-26 05:22 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +// 添加一个固定的延迟，以便你可以看到加载状态
```suggestion

// 添加一个固定的延迟，以便你可以看到加载状态
```

2023-03-26 05:22 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +这个示例代码加载时有人工延迟。如果下次你取消选中并重新选中复选框时，`Preview` 将被缓存，因此不会出现加载状态。要再次查看加载状态，请在示例中单击 “Reset”。
```suggestion
这个示例代码人为地推迟了加载。在你下次取消选中并重新选中复选框时，`Preview` 将被缓存，因此不会出现加载状态。要再次查看加载状态，请在示例中单击 “Reset”。
```

2023-03-26 05:36 UTC, awxiaoxian2020 requested changes

2023-03-26 05:36 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +如果想在组件第一次渲染前推迟加载这个组件的代码，请使用以下导入替换：
```suggestion
如果想在组件第一次渲染前延迟加载这个组件的代码，请使用以下导入替换：
```

2023-03-26 12:17 UTC, Davont commented
已经更改！感谢检视

2023-03-26 12:18 UTC, Davont commented
> 文中使用“您”的地方无特殊情况请改成“你”。

已经更改

2023-03-27 14:19 UTC, awxiaoxian2020 requested changes

2023-03-27 14:19 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +如果想在组件第一次渲染前延迟加载这个组件的代码，请替换成以下导入方式：
```suggestion

如果想在组件第一次渲染前延迟加载这个组件的代码，请替换成以下导入方式：
```

2023-03-27 23:18 UTC, awxiaoxian2020 requested changes
请一定保证行行对应~

2023-03-27 23:18 UTC, awxiaoxian2020 commented on src/content/reference/react/lazy.md
> +此代码依赖于 [动态 `import()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/import)，可能需要你的打包工具或框架提供支持。
```suggestion

此代码依赖于 [动态 `import()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/import)，可能需要你的打包工具或框架提供支持。
```

2023-03-28 01:44 UTC, Davont commented
> 请一定保证行行对应~

抱歉，没明白您的意思，您意思是 英文的第几行要对应中文的第几行，不能出现多余的空行，是这个意思吗？

2023-03-28 01:48 UTC, awxiaoxian2020 commented
> > 请一定保证行行对应~
> 
> 抱歉，没明白您的意思，您意思是 英文的第几行要对应中文的第几行，不能出现多余的空行，是这个意思吗？

是的，请参阅 wiki 关于行数的描述。

你的问题在于该空行的地方没有空行~

2023-03-28 02:40 UTC, Davont commented
> > > 请一定保证行行对应~
> > 
> > 
> > 抱歉，没明白您的意思，您意思是 英文的第几行要对应中文的第几行，不能出现多余的空行，是这个意思吗？
> 
> 是的，请参阅 wiki 关于行数的描述。
> 
> 你的问题在于该空行的地方没有空行~

已经更新

2023-03-28 04:33 UTC, awxiaoxian2020 approved these changes

2023-03-28 04:50 UTC, daochouwangu approved these changes

2023-03-28 04:51 UTC, merged