docs(cn): translate /content/blog/2020-02-26-react-v16.13.0.md into Chinese
reactjs/zh-hans.reactjs.org pull request #448
Opened 2020-09-29 13:12 UTC by Yilia-Wish

docs(cn): translate /content/blog/2020-02-26-react-v16.13.0.md into Chinese

2020-09-29 13:32 UTC, yuqingc requested changes
请先阅读 https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97
阅读之后，请先调整一下全文的标点和样式。

2020-09-29 13:32 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +我们今天发布了 React 16.13.0。它包含了 bug 修复和新的不推荐警告，来帮助准备未来的主要版本。
“新的不推荐警告”这个读起来不通啊

2020-09-29 13:32 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +一个 React component 不应该在 render 期间对其他component造成副作用影响。
单词之间的空格。不过 component 需要翻译成“组件”。请参考 https://github.com/reactjs/zh-hans.reactjs.org/issues/2

2020-09-29 13:32 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +在 render 期间调用 `setState` 是被支持的，但是 [仅仅适用于 *同一个 component*](/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops). 如果你在另一个 component render 期间调用 `setState` ,现在你将会看到一条警告:
使用中文标点，中文之间不需要空格
```suggestion
在 render 期间调用 `setState` 是被支持的，但是 [仅仅适用于*同一个 component*](/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops)。 如果你在另一个 component render 期间调用 `setState`，现在你将会看到一条警告。
```

2020-10-03 03:07 UTC, yuqingc requested changes
注意格式
@QC-L 帮忙 Review 一下

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +[字符串 ref 是旧版的 API](/docs/refs-and-the-dom.html#legacy-api-string-refs) 这是不可取的，将来将被弃用：
legacy 翻译参考 #2

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +这样的代码通常暗含 bug。（你可能希望ref在 `ClassParent` 上可用，但是它被放在 `ClassWithRenderProp` 上）。
注意格式
```suggestion
这样的代码通常暗含 bug。（你可能希望 ref 在 `ClassParent` 上可用，但是它被放在 `ClassWithRenderProp` 上）。
```

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +**你很可能没有这样的代码**。如果是故意的，请将其转换为[`React.createRef()`](/docs/refs-and-the-dom.html#creating-refs)：
故意的感觉有贬义的含义，可以采用“有意”或者“有意为之”这类中性词

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +**你很可能没有这样的代码**。如果是故意的，请将其转换为[`React.createRef()`](/docs/refs-and-the-dom.html#creating-refs)：
注意格式
```suggestion
**你很可能没有这样的代码**。如果是故意的，请将其转换为 [`React.createRef()`](/docs/refs-and-the-dom.html#creating-refs)：
```

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +> 要查看此警告，你需要在你的 Babel plugins 中安装[babel-plugin-transform-react-jsx-self](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-self)。它必须 _仅仅_ 在开发模式下启用。
注意格式谢谢
```suggestion
> 要查看此警告，你需要在你的 Babel plugins 中安装 [babel-plugin-transform-react-jsx-self](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-self)。它必须 _仅仅_ 在开发模式下启用。 
```

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +> 如果你使用 Create React App 或者用 babel 7 + 预置了 React，那么默认情况下已经安装了这个插件。
preset 是 babel 的术语，不需要翻译
```suggestion
> 如果你使用 Create React App 或者用 babel 7+ 的 React preset，那么默认情况下已经安装了这个插件。
```

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +替换的用法 `React.createFactory` 用普通的 JSX 。或者可以复制并粘贴此单行辅助对象或将其发布为库：
替换的用法 `React.createFactory` 用普通的 JSX 这句话不通。。。
你可以说 把xxx替换为xxx

2020-10-03 03:07 UTC, yuqingc commented on content/blog/2020-02-26-react-v16.13.0.md
> +虽然它指出了代码中的一个错误，但不清楚错误在哪里存在，以及下一步该怎么做。此版本向此警告添加了一个 Component 堆栈，使其看起来如下所示：
component 请翻译，下同

2020-10-08 01:39 UTC, QC-L commented on content/blog/2020-02-26-react-v16.13.0.md
> +我们今天发布了 React 16.13.0。它包含了 bug 修复和新的弃用警告，来帮助准备未来的主要版本。
```suggestion
今天我们发布了 React 16.13.0。此版本修复了部分 bug 并添加了新的弃用警告，以助力接下来的主要版本。
```

2020-10-08 01:56 UTC, QC-L commented on content/blog/2020-02-26-react-v16.13.0.md
> +一个 React 组件不应该在 render 期间对其他组件造成副作用影响。
```suggestion
React 组件不应在 render 期间对其他组件产生副作用副作用。
```

2020-10-09 10:05 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +在 render 期间调用 `setState` 是被支持的，但是 [仅仅适用于*同一个 component*](/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops)。 如果你在另一个 component render 期间调用 `setState`，现在你将会看到一条警告。
done

2020-10-09 10:06 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +你可能期待这个 `<div>` 总是拥有红色背景，不论 `toggle` 的值是什么。然而，在 `true` 和 `false`之间交替使用`toggle`时，背景色开始是 `red`，然后在 `transparent` 和 `blue`之间交替， [像你能在这个 demo 中看到的](https://codesandbox.io/s/suspicious-sunset-g3jub)。
done

2020-10-09 10:06 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +**React 现在检测到冲突的样式规则并记录警告。**要解决此问题，请不要在 `style` 属性中混合使用同一CSS属性的简写和全写版本。
done

2020-10-09 10:08 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +### 某些不推荐使用的字符串 ref 的警告 {#warnings-for-some-deprecated-string-refs}
done

2020-10-09 10:08 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +[字符串 ref 是旧版的 API](/docs/refs-and-the-dom.html#legacy-api-string-refs) 这是不可取的，将来将被弃用：
done

2020-10-09 10:09 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +这样的代码通常暗含 bug。（你可能希望ref在 `ClassParent` 上可用，但是它被放在 `ClassWithRenderProp` 上）。
done

2020-10-09 10:10 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +**你很可能没有这样的代码**。如果是故意的，请将其转换为[`React.createRef()`](/docs/refs-and-the-dom.html#creating-refs)：
both done

2020-10-09 10:11 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +> 要查看此警告，你需要在你的 Babel plugins 中安装[babel-plugin-transform-react-jsx-self](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-self)。它必须 _仅仅_ 在开发模式下启用。
done

2020-10-09 10:13 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +> 如果你使用 Create React App 或者用 babel 7 + 预置了 React，那么默认情况下已经安装了这个插件。
done

2020-10-09 10:13 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +替换的用法 `React.createFactory` 用普通的 JSX 。或者可以复制并粘贴此单行辅助对象或将其发布为库：
done

2020-10-09 10:15 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +虽然它指出了代码中的一个错误，但不清楚错误在哪里存在，以及下一步该怎么做。此版本向此警告添加了一个 Component 堆栈，使其看起来如下所示：
done

2020-10-09 10:17 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +我们今天发布了 React 16.13.0。它包含了 bug 修复和新的弃用警告，来帮助准备未来的主要版本。
done

2020-10-09 10:22 UTC, Yilia-Wish commented on content/blog/2020-02-26-react-v16.13.0.md
> +一个 React 组件不应该在 render 期间对其他组件造成副作用影响。
done

2020-10-09 12:36 UTC, yuqingc approved these changes
lgtm

2020-10-09 16:15 UTC, QC-L approved these changes

2020-10-09 16:15 UTC, merged