docs(cn): translate content/blog/2013-06-02-jsfiddle-integration.md i…
reactjs/zh-hans.reactjs.org pull request #565
Opened 2021-08-08 07:37 UTC by redhat123456

…nto chinese

2021-08-08 14:13 UTC, redhat123456 commented
各位大佬，看一下 @QC-L

2021-08-09 01:20 UTC, Ivocin requested changes
注意空格和中文标点

2021-08-09 01:20 UTC, Ivocin commented on content/blog/2013-06-02-jsfiddle-integration.md
> +[JSFiddle](https://jsfiddle.net) 刚刚宣布支持React。这是一个令人兴奋的消息，因为它使代码片段上的协作变得更加容易。你可以玩这个基础的 **[base React JSFiddle](http://jsfiddle.net/vjeux/kb3gN/)**, fork 它并分享它😎! 一个 [fiddle without JSX](http://jsfiddle
```suggestion
[JSFiddle](https://jsfiddle.net) 刚刚宣布支持 React。这是一个令人兴奋的消息，因为它使代码片段上的协作变得更加容易。你可以尝试这个**[基础的 React JSFiddle](http://jsfiddle.net/vjeux/kb3gN/)**，fork 它并分享它 😎！这里还有一个 [不含 JSX 的 fiddle](http://jsfiddle.net/vjeux/VkebS/)。
```

2021-08-09 01:20 UTC, Ivocin commented on content/blog/2013-06-02-jsfiddle-integration.md
> +<blockquote class="twitter-tweet" align="center"><p>React(通过Facebook)现在可以在JSFiddle上使用。 <a href="http://t.co/wNQf9JPv5u" title="http://facebook.github.io/react/">facebook.github.io/react/</a></p>&mdas
```suggestion
<blockquote class="twitter-tweet" align="center"><p>React（通过 Facebook）现在可以在 JSFiddle 上使用。 <a href="http://t.co/wNQf9JPv5u" title="http://facebook.github.io/react/">facebook.github.io/react/</a></p>&mdash; JSFiddle (@jsfiddle) <a href="https://twitter.com/jsfiddle/status/341114115781177344">2013 年 6 月 2 日</a></blockquote>
```

2021-08-09 01:41 UTC, redhat123456 commented
好

2021-08-09 01:48 UTC, redhat123456 reviewed
好

2021-08-09 07:53 UTC, Ivocin requested changes

2021-08-09 07:53 UTC, Ivocin commented on content/blog/2013-06-02-jsfiddle-integration.md
> +[JSFiddle](https://jsfiddle.net) 刚刚宣布支持 React 。这是一个令人兴奋的消息 ， 因为它使代码片段上的协作变得更加容易 。 你可以玩这个基础的 **[base React JSFiddle](http://jsfiddle.net/vjeux/kb3gN/)**, fork 它并分享它😎! 一个 [fiddle without JSX](http://js
```suggestion
[JSFiddle](https://jsfiddle.net)  刚刚宣布支持 React。这是一个令人兴奋的消息，因为它使代码片段上的协作变得更加容易。你可以尝试这个 **[基础的 React JSFiddle](http://jsfiddle.net/vjeux/kb3gN/)**，fork 它并分享它😎！这里还有一个 [不含 JSX 的 fiddle](http://jsfiddle.net/vjeux/VkebS/)。
```

2021-08-09 07:53 UTC, Ivocin commented on content/blog/2013-06-02-jsfiddle-integration.md
> +<blockquote class="twitter-tweet" align="center"><p>React（通过 Facebook）现在可以在 JSFiddle 上使用。 <a href="http://t.co/wNQf9JPv5u" title="http://facebook.github.io/react/">facebook.github.io/react/</a></p>&m
```suggestion
<blockquote class="twitter-tweet" align="center"><p>React（通过 Facebook）现在可以在 JSFiddle 上使用。<a href="http://t.co/wNQf9JPv5u" title="http://facebook.github.io/react/">facebook.github.io/react/</a></p>&mdash; JSFiddle (@jsfiddle) <a href="https://twitter.com/jsfiddle/status/341114115781177344">2013 年 6 月 2 日</a></blockquote>
```

2021-08-10 05:19 UTC, merged

2021-08-10 11:51 UTC, redhat123456 reviewed
好