[Beta]: docs(cn): conditional-rendering
reactjs/zh-hans.reactjs.org pull request #636
Opened 2021-11-03 15:04 UTC by Alienover

2021-11-03 15:06 UTC, Alienover commented on beta/src/pages/learn/conditional-rendering.md
> +如果你之前是习惯面向对象开发的，你可能会认为上面的两个例子略有不同，因为其中一个可能会创建两个不同的 `<li>` “实例”。但 JSX 元素不是“实例”，因为它们没有内部状态也不是真是的 DOM 节点。它们只是一些简单的描述，就像图纸一样。所以上面这两个例子，事实上，是完全相同的。在 [状态的保持和重置](/learn/preserving-and-resetting-state) 里会深入探
Will update the `Preserving and Resetting State` after someone translated it.

2021-11-03 15:06 UTC, Alienover commented on beta/src/pages/learn/conditional-rendering.md
> +[大括号 - JavaScript 的“新世界”。](/learn/javascript-in-jsx-with-curly-braces#using-curly-braces-a-window-into-the-javascript-world) 将变量用大括号嵌入在返回的 JSX 树中，来嵌套计算好的表达式与 JSX：
Will update the `Curly braces open the "window into JavaScript"` after someone translated it.

2023-02-15 13:14 UTC, daochouwangu submitted a review, later dismissed

2023-02-15 13:27 UTC, awxiaoxian2020 commented
@daochouwangu We should fix the conflicts.

2023-02-17 09:21 UTC, awxiaoxian2020 requested changes
翻译再检查和润色一下~ :)

2023-02-17 09:21 UTC, awxiaoxian2020 commented on beta/src/content/learn/conditional-rendering.md
> +通常你的组件会需要根据不同的情况显示不同的内容。在 React，你可以通过使用 Javascript 的 `if` 语句，或者 `&&`，`? :` 运算符来选择性地渲染 JSX。
```suggestion
通常你的组件会需要根据不同的情况显示不同的内容。在 React 中，你可以通过使用 JavaScript 的 `if` 语句、`&&` 和 `? :` 运算符来选择性地渲染 JSX。
```

2023-02-17 09:21 UTC, awxiaoxian2020 commented on beta/src/content/learn/conditional-rendering.md
> +留意这里你是怎么使用 JavaScript 的 `if` 和 `return` 语句来写分支逻辑。在 React，是由 JavaScript 来处理控制流的（比如条件)。
```suggestion
留意这里你是怎么使用 JavaScript 的 `if` 和 `return` 语句来写分支逻辑。在 React 中，是由 JavaScript 来处理控制流的（比如条件）。

2023-02-17 09:21 UTC, awxiaoxian2020 commented on beta/src/content/learn/conditional-rendering.md
> +实际上，在组件里返回 `null` 并不常见，因为这样会让想使用它的开发者感觉奇怪。通常，你可以在父组件里选择是否要渲染该组件。让我们接着往下看吧！
```suggestion
实际上，在组件里返回 `null` 并不常见，因为这样会让想使用它的开发者感觉奇怪。通常情况下，你可以在父组件里选择是否要渲染该组件。让我们接着往下看吧！
```

2023-02-17 09:21 UTC, awxiaoxian2020 commented on beta/src/content/learn/conditional-rendering.md
> +相似于
```suggestion
和下面的写法很像：
```

2023-02-17 09:21 UTC, awxiaoxian2020 commented on beta/src/content/learn/conditional-rendering.md
> +这个例子中，每种饮品的信息是放在一起的，而不是分散到多个条件判断里。这会使得以后增加更多的饮品更加容易。
```suggestion
这个例子中，每种饮品的信息是放在一起的，而没有将其分散到多个条件判断里。这会让我们以后可以更容易地增加更多的饮品。
```

2023-03-01 10:23 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-03-01 10:24 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-03-02 01:27 UTC, daochouwangu requested changes

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +* 如何根据不同条件返回不同地 JSX
```suggestion
* 如何根据不同条件返回不同的 JSX
```

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +在一些情况下，你不想有任何东西进行渲染。比如，假设你不想显示已经打包好的物品。但一个组件必须返回一些东西。这种情况下，你可以直接返回 `null`。
```suggestion
在一些情况下，你不想有任何东西进行渲染。比如，你不想显示已经打包好的物品。但一个组件必须返回一些东西。这种情况下，你可以直接返回 `null`。
```
比如，假设
有点重复

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +在之前的例子里，你通过在组件内部控制哪些 JSX 树（如果有的话！）会返回。你可能已经发现了在渲染输出里会有一些重复的内容：
```suggestion
在之前的例子里，你在组件内部控制哪些 JSX 树（如果有的话！）会返回。你可能已经发现了在渲染输出里会有一些重复的内容：
```
也可以是：
通过组件来控制哪些 JSX 树被返回。
通过....，然后就没了，不太符合常规语法，应该是通过xxx实现xxx。

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +你可以认为，*“如果 `isPacked=true` 时，则（`?`）渲染 `name + ' ✔'`，否则（`:`）渲染 `name`。”*
```suggestion
你可以认为，*“如果 `isPacked` 为 true 时，则（`?`）渲染 `name + ' ✔'`，否则（`:`）渲染 `name`。”*
```
或者 isPacked === true

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +如果你之前是习惯面向对象开发的，你可能会认为上面的两个例子略有不同，因为其中一个可能会创建两个不同的 `<li>` “实例”。但 JSX 元素不是“实例”，因为它们没有内部状态也不是真是的 DOM 节点。它们只是一些简单的描述，就像图纸一样。所以上面这两个例子，事实上，是完全相同的。在 [状态的保持和重置](/learn/preserving-and-resetting-state) 里会深入探
```suggestion
如果你之前是习惯面向对象开发的，你可能会认为上面的两个例子略有不同，因为其中一个可能会创建两个不同的 `<li>` “实例”。但 JSX 元素不是“实例”，因为它们没有内部状态也不是真是的 DOM 节点。它们只是一些简单的描述，就像图纸一样。所以上面这两个例子事实上是完全相同的。在 [状态的保持和重置](/learn/preserving-and-resetting-state) 里会深入探讨其原因。
```

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +你会遇到的另一个常见的快捷表达式是 [JavaScript 与（`&&`）运算符](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Logical_AND#:~:text=The%20logical%20AND%20(%20%26%26%20)%20operator,it%20returns%
```suggestion
你会遇到的另一个常见的快捷表达式是 [JavaScript 与（`&&`）运算符](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Logical_AND#:~:text=The%20logical%20AND%20(%20%26%26%20)%20operator,it%20returns%20a%20Boolean%20value.)。在 React 组件里，通常用在当条件成立时，你想渲染一些 JSX，**或者不做任何渲染**。使用 `&&`，你也可以实现仅当 `isPacked` 为 `true` 时，渲染勾选符号。
```
同上

2023-03-02 01:27 UTC, daochouwangu commented on beta/src/content/learn/conditional-rendering.md
> +在这个解决方案里，分别用了两个条件判断在名字和重要性标签里插入一个空格。另外，你也可以通过一个带前导空格的片段：`importance > 0 && <> <i>...</i></>`，或者将空格放在 `<i>` 标签内：`importance > 0 && <i> ...</i>`, 来实现相同的效果。
```suggestion
在这个解决方案里，分别用了两个条件判断在名字和重要性标签里插入一个空格。另外，你也可以通过一个带前导空格的 fragment ：`importance > 0 && <> <i>...</i></>`，或者将空格放在 `<i>` 标签内：`importance > 0 && <i> ...</i>`, 来实现相同的效果。
```
[fragment 不翻译](https://github.com/reactjs/zh-hans.reactjs.org/issues/2)

2023-03-02 02:37 UTC, awxiaoxian2020 approved these changes

2023-03-03 00:52 UTC, daochouwangu approved these changes

2023-03-03 00:55 UTC, merged