docs: add-react-to-a-website
reactjs/zh-hans.reactjs.org pull request #640
Opened 2021-11-04 03:13 UTC by Atrist

2021-11-04 03:14 UTC, Atrist commented
@QC-L

2021-12-06 17:07 UTC, yyyang1996 requested changes

2021-12-06 17:07 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +如果你使用 React.createElement() 的这种简写形式，那么在没有 JSX 的情况下使用 React 几乎同样方便。
```suggestion
在你不使用 JSX 编写 React 组件时，这种简写形式的 `React.createElement()` 同样方便。
```

2021-12-09 14:51 UTC, yyyang1996 requested changes

2021-12-09 14:51 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +React 在设计之初就可以被渐进式适配，并且你可以根据需要选择性地使用 React 。无论你是使用微前端，已有项目，还是仅仅想尝试一下 React，你只需要几行代码便可以将 React 添加到你的 HTML 页面--无需构建工具！
```suggestion
React 在设计之初就可以被渐进式适配，并且你可以根据需要选择性地使用 React。无论是微前端，或是已有项目，还是仅仅想尝试一下 React，你都只需要几行代码便可以将 React 添加到你的 HTML 页面--无需构建工具！
```

2021-12-09 14:51 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +你可以在 `<body>` 标签内的任何地方放置一个类似 `<div>` 的容器元素。根据需要，你可以在一个页面上放置多个独立的 DOM 容器。它们通常是空标签 —— React 会替换 DOM 容器内的任何已有内容。
```suggestion
你可以在 `<body>` 标签内的任何地方放置一个类似 `<div>` 的容器元素。你可以根据需要在一个页面上放置多个独立的 DOM 容器，它们通常是空标签 —— React 会替换 DOM 容器内的任何已有内容。
```

2021-12-09 14:51 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +- [**react-dom.development.js**](https://unpkg.com/react-dom@17/umd/react-dom.development.js) 让 React 将 HTML 元素渲染到 [DOM](https://developer.mozilla.org/docs/Web/API/Document_Object_Model) 的依赖文件。
```suggestion
- [**react-dom.development.js**](https://unpkg.com/react-dom@17/umd/react-dom.development.js) 这个脚本文件可以让 React 将 HTML 元素渲染到 [DOM](https://developer.mozilla.org/docs/Web/API/Document_Object_Model)。
```

2021-12-09 14:51 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +部署时，将 "development.js" 替换为 "production.min.js"
```suggestion
部署时，你需要将 "development.js" 替换为 "production.min.js"。
```

2021-12-09 14:51 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +### 步骤 4： 把你的 React 组件添加到网站中 {/*step-4-add-your-react-component-to-the-page*/}
```suggestion
### 步骤 4： 把你的 React 组件添加到页面中 {/*step-4-add-your-react-component-to-the-page*/}
```

2021-12-09 14:51 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +如果你不想每次都键入 `React.createElement`，通常的做法是创建快捷方式：
```suggestion
如果你不想每次都键入 `React.createElement`，通常的做法是使用简写：
```

2021-12-16 05:59 UTC, yyyang1996 requested changes

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +在本小节中，我们会展示如何将 React 组件添加到现有的 HTML 页面中。你可以在你自己的网站上尝试，或者创建一个 [空的 HTML 文件](https://gist.github.com/rachelnabors/7b33305bf33776354797a2e3c1445186/archive/859eac2f7079c9e1f0a6eb818a9684a464064d80.zip) 来进
```suggestion
在本小节中，我们会展示如何将 React 组件添加到现有的 HTML 页面中。你可以在你自己的网站上尝试，或者创建一个 [空的 HTML 文件](https://gist.github.com/rachelnabors/7b33305bf33776354797a2e3c1445186/archive/859eac2f7079c9e1f0a6eb818a9684a464064d80.zip) 来进行练习。你只需要连接到网络，使用一个像 Notepad 的文本编辑器（也可以是 VSCode，可以查看我们的文档来学习 [如何设置你的编辑器](/learn/editor-setup/)）！
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +在 HTML 页面文件的同级目录下创建一个名为 **like_button.js** 的文件,并将下面的代码片段添加到文件中。这段代码定义了一个名为 LikeButton 的 React 组件。[你可以在这里了解更多关于如何创建一个组件。](/learn/your-first-component)
```suggestion
在 HTML 页面文件的同级目录下创建一个名为 **like_button.js** 的文件，并将下面的代码片段添加到文件中。这段代码定义了一个名为 LikeButton 的 React 组件。[你可以在这里了解更多关于如何创建一个组件。](/learn/your-first-component)
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +1. 在 **index.html**,添加另外一个的容器元素 `<div id="component-goes-here-too"></div>`.
```suggestion
1. 在 **index.html**，添加另外一个的容器元素 `<div id="component-goes-here-too"></div>`。
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +2. 在 **like_button.js**,为新的容器元素添加 `ReactDOM.render()`:
```suggestion
2. 在 **like_button.js**，为新的容器元素添加 `ReactDOM.render()`：
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +这有[一个示例，它显示了三次 “Like” 按钮，并向各自传入了一些数据](https://gist.github.com/rachelnabors/c0ea05cc33fbe75ad9bbf78e9044d7f8)!
```suggestion
这有 [一个示例，它显示了三次 “Like” 按钮，并向各自传入了一些数据](https://gist.github.com/rachelnabors/c0ea05cc33fbe75ad9bbf78e9044d7f8)！
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +部署时，你需要将 "development.js" 替换为 "production.min.js"。
```suggestion
部署时，你需要将 “development.js” 替换为 “production.min.js”。
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +#### 你可以重复使用你的组件! {/*you-can-reuse-components*/}
```suggestion
#### 你可以重复使用你的组件！{/*you-can-reuse-components*/}
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +- **如果你没有一个代码压缩的步骤**,[这有一个配置它的方式](https://gist.github.com/gaearon/42a2ffa41b8319948f9be4076286e1f3)。
```suggestion
- **如果你没有一个代码压缩的步骤**，[这有一个配置它的方式](https://gist.github.com/gaearon/42a2ffa41b8319948f9be4076286e1f3)。
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +使用 JSX 编写 **like_button.js**:
```suggestion
使用 JSX 编写 **like_button.js**：
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +2. 在 **index.html** 文件中，为 link_button_js 的 `script` 标签添加 `type="text/babel"` 属性:
```suggestion
2. 在 **index.html** 文件中，为 link_button_js 的 `script` 标签添加 `type="text/babel"` 属性：
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +这是 [一个使用了 JSX 的 HTML 文件的例子](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html) ，你可以下载并尝试使用。
```suggestion
这是 [一个使用了 JSX 的 HTML 文件的例子](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html)，你可以下载并尝试使用。
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +在终端上进入你的项目文件夹，然后粘贴这两个命令：(**确保你的计算机安装了 [Node.js](https://nodejs.org/) !**):
```suggestion
在终端上进入你的项目文件夹，然后粘贴这两个命令：(**确保你的计算机安装了 [Node.js](https://nodejs.org/)！**)：
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +2. 在终端执行这个命令： `npx babel --watch src --out-dir . --presets react-app/prod ` (不要等待它运行结束 —— 这个命令启动了一个对 JSX 的自动监听器。)
```suggestion
2. 在终端执行这个命令： `npx babel --watch src --out-dir . --presets react-app/prod ` （不要等待它运行结束 —— 这个命令启动了一个对 JSX 的自动监听器。）
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +3. 把包含 JSX 语法的 **like_button_js** 文件移动到新创建的 **src** 文件夹中(或者在 **src**文件夹中创建一个包含[此段代码](https://gist.githubusercontent.com/rachelnabors/ffbc9a0e33665a58d4cfdd1676f05453/raw/652003ff54d2dab8a1a1e5cb3bb1e
```suggestion
3. 把包含 JSX 语法的 **like_button_js** 文件移动到新创建的 **src** 文件夹中（或者在 **src**文件夹中创建一个包含 [此段代码](https://gist.githubusercontent.com/rachelnabors/ffbc9a0e33665a58d4cfdd1676f05453/raw/652003ff54d2dab8a1a1e5cb3bb1e28ff207c1a6/like_button.js) 的 **like_button_js** 的文件）
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +如果你认为你已经习惯了构建工具，并希望它们能为你做更多事, [我们在这描述了一些最流行和易上手的工具链](/learn/start-a-new-react-project).
```suggestion
如果你认为你已经习惯了构建工具，并希望它们能为你做更多事，[我们在这描述了一些最流行和易上手的工具链](/learn/start-a-new-react-project)。
```

2021-12-16 05:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +如果使用 `React.createElement()`, 将会是这样:
```suggestion
如果使用 `React.createElement()`，将会是这样：
```

2021-12-16 06:09 UTC, yyyang1996 commented
Review 完毕，译者已经修改。cc @QC-L  @Atrist

2021-12-16 08:05 UTC, QC-L commented on beta/src/pages/learn/add-react-to-a-website.md
> +## 一分钟用上 React {/*add-react-in-one-minute*/}
```suggestion
## 一分钟接入 React {/*add-react-in-one-minute*/}
```

2021-12-16 12:27 UTC, QC-L commented on beta/src/pages/learn/add-react-to-a-website.md
> +  - Atrist
```suggestion
  - Atrist
  - yyyang1996
```

2021-12-16 12:28 UTC, QC-L commented on beta/src/pages/learn/add-react-to-a-website.md
> +现在，你可以在任何添加了 `type="text/babel"` 属性的 `<script>` 标签内使用 JSX。举一个例子：
```suggestion
现在，你可以在任何添加了 `type="text/babel"` 属性的 `<script>` 标签内使用 JSX。示例如下：
```

2021-12-16 12:29 UTC, QC-L commented on beta/src/pages/learn/add-react-to-a-website.md
> +这是 [一个使用了 JSX 的 HTML 文件的例子](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html)，你可以下载并尝试使用。
```suggestion
这是 [一个使用了 JSX 的 HTML 文件示例](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html)，你可以下载并尝试使用。
```

2021-12-17 13:59 UTC, yyyang1996 requested changes

2021-12-17 13:59 UTC, yyyang1996 commented on beta/src/pages/learn/add-react-to-a-website.md
> +最后,在 **like_button.js** 底部添加以下两行代码。这两行代码会找到我们在步骤 1 中添加到 HTML 里的 `<div>`，然后在它内部显示我们的 React 组件 “like” 按钮。
```suggestion
最后，在 **like_button.js** 底部添加以下两行代码。这两行代码会找到我们在步骤 1 中添加到 HTML 里的 `<div>`，然后在它内部显示我们的 React 组件 “like” 按钮。
```

2021-12-17 14:00 UTC, yyyang1996 submitted a review, later dismissed

2021-12-18 14:51 UTC, QC-L commented on beta/src/pages/learn/add-react-to-a-website.md
> +替换
```suggestion

替换

```

2021-12-19 05:11 UTC, yyyang1996 approved these changes

2021-12-19 12:38 UTC, QC-L approved these changes

2021-12-19 12:38 UTC, merged