[Beta]: docs(cn): translate learn/referencing-values-with-refs.md
reactjs/zh-hans.reactjs.org pull request #649
Opened 2021-11-06 06:51 UTC by SylviaZ89

2021-12-07 15:16 UTC, Neo42 requested changes

2021-12-08 04:08 UTC, Neo42 commented
另外建议按[排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97)要求把译文中的 Ref / refs / State 改成单数小写的 ref / state

2021-12-09 07:59 UTC, Neo42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +  - SylviaZ89
```suggestion
  - Neo42
  - SylviaZ89
```

2021-12-09 09:03 UTC, Neo42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +<DeepDive title="useRef 内部是如何工作的？">
```suggestion
<DeepDive title="useRef 内部是如何运行的？">
```

2021-12-19 06:57 UTC, Neo42 commented
校对完毕，麻烦处理一下，谢谢 @SylviaZ89

2021-12-21 12:14 UTC, SylviaZ89 commented
> 校对完毕，麻烦处理一下，谢谢 @SylviaZ89

收到 周末处理好 @Neo42

2021-12-25 09:05 UTC, SylviaZ89 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +| 可变 —— 你可以在渲染过程之外修改和更新 `current` 的值。 | “不可变” —— 你必须使用 state 设置函数来修改 state 变量，从而排队重新渲染。 |
“让一次重渲染进入渲染队列” 这样呢

2021-12-25 09:10 UTC, SylviaZ89 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +当一条信息用于渲染时，将它保存在 state 中。 当一条信息仅被事件处理器需要，并且更改它不会重新渲染时，使用 ref 可能更有效。
我觉得根据 修改state —> 触发渲染 这个主被动关系，这里的 require 更接近“要求”的意思，而不是“需要”。译成“更改它不会重新渲染”主要是想表达这个主被动关系。
efficient确实译成“高效“更好

2021-12-25 15:48 UTC, SylviaZ89 commented
@Neo42  感谢，很严谨！提交了一部分，没修改的部分可以再讨论下。translators 那里我最后再提交，免得影响行号~

2021-12-26 04:29 UTC, Neo42 commented
> @Neo42 感谢，很严谨！提交了一部分，没修改的部分可以再讨论下。translators 那里我最后再提交，免得影响行号~

好的。translators 那里我原以为是按字母顺序，后来 @QC-L 告诉我现在需要把第一译者优先排序，所以我改了一下。另外可以说说你对没修改的地方有什么见解吗？

2021-12-26 04:33 UTC, Neo42 commented on beta/src/pages/learn/referencing-values-with-refs.md
> +| 可变 —— 你可以在渲染过程之外修改和更新 `current` 的值。 | “不可变” —— 你必须使用 state 设置函数来修改 state 变量，从而排队重新渲染。 |
> “让一次重渲染进入渲染队列” 这样呢

我觉得这句比我改得好~

2023-02-23 14:58 UTC, daochouwangu requested changes

2023-02-23 14:58 UTC, daochouwangu commented on beta/src/content/learn/referencing-values-with-refs.md
> +当一条信息用于渲染时，将它保存在 state 中。当一条信息仅被事件处理器需要，并且更改它不会重新渲染时，使用 ref 可能会更高效。
```suggestion
当一条信息用于渲染时，将它保存在 state 中。当一条信息仅被事件处理器需要，并且更改它不需要重新渲染时，使用 ref 可能会更高效。 
```
这里的意思偏向于不用触发重渲染的值适合放在 ref 中。
`不会重渲染` 更强调放在里面不会重新渲染，有点因果颠倒的意思。

2023-02-23 14:58 UTC, daochouwangu commented on beta/src/content/learn/referencing-values-with-refs.md
> +- 存储不需要计算 JSX 的其他对象。
```suggestion
- 存储不需要被用来计算 JSX 的其他对象。
```
其实就是渲染时用不到的对象的意思

2023-02-25 05:14 UTC, SylviaZ89 commented
@daochouwangu Thanks！Suggested changes commited，LGTM

2023-02-26 03:32 UTC, awxiaoxian2020 requested changes

2023-02-26 03:32 UTC, awxiaoxian2020 commented on beta/src/content/learn/referencing-values-with-refs.md
> +当用户按下 “开始” 时，你将用 [`setInterval`](https://developer.mozilla.org/docs/Web/API/setInterval) 每 10 毫秒更新一次时间：
```suggestion
当用户按下“开始”时，你将用 [`setInterval`](https://developer.mozilla.org/docs/Web/API/setInterval) 每 10 毫秒更新一次时间：
```
还有多处引号空格，请一并修改。

2023-02-28 00:57 UTC, daochouwangu approved these changes

2023-02-28 01:54 UTC, awxiaoxian2020 approved these changes

2023-02-28 14:18 UTC, daochouwangu approved these changes

2023-02-28 22:57 UTC, merged