[Beta] docs(cn): state-a-components-memory
reactjs/zh-hans.reactjs.org pull request #651
Opened 2021-11-08 11:03 UTC by 7ooz

2021-12-19 13:03 UTC, x-cold commented on beta/src/pages/learn/state-a-components-memory.md
> +要修复此代码，请删除不必要的 state 变量。（我们将在稍后讨论 [为什么上述代码不起作用](/learn/troubleshooting-state-updates#setting-state-does-not-update-variables)。）
```suggestion
要修复此代码，请删除不必要的 state 变量。（我们将在稍后讨论[为什么上述代码不起作用](/learn/troubleshooting-state-updates#setting-state-does-not-update-variables)。）
```

2021-12-19 13:03 UTC, x-cold commented on beta/src/pages/learn/state-a-components-memory.md
> +以下是一个使用了一般变量 `name` 的固定版本，这个变量声明于需要它的函数中。
```suggestion
以下是一个使用了普通变量 `name` 的固定版本，这个变量声明于需要它的函数中。
```

2021-12-19 13:03 UTC, x-cold commented on beta/src/pages/learn/state-a-components-memory.md
> +State 变量仅用于在组件重渲染时保存信息。在单个事件处理函数中，一般变量就足够了。当一般变量运行良好时，不要引入 state 变量。
```suggestion
State 变量仅用于在组件重渲染时保存信息。在单个事件处理函数中，普通变量就足够了。当普通变量运行良好时，不要引入 state 变量。
```

2021-12-19 13:04 UTC, x-cold commented on beta/src/pages/learn/state-a-components-memory.md
> +  - 7ooz
```suggestion
  - 7ooz
  - x-cold
```

2022-01-22 06:32 UTC, KnowsCount commented on beta/src/pages/learn/state-a-components-memory.md
> +1. **保留**渲染之间的数据。
```suggestion
1. **保留** 渲染之间的数据。
```

2023-02-23 11:59 UTC, awxiaoxian2020 commented
Do you consider applying code review or looking into it?

2023-02-24 05:56 UTC, zzwgh commented
> Do you consider applying code review or looking into it?
> 
> Or you have done these changes?

last round of conversations are resolved. maybe need some more review on it.

2023-02-27 14:40 UTC, daochouwangu requested changes

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +State 只是这些特性中的一个，你之后还会遇到其他 Hooks。
```suggestion
State 只是这些特性中的一个，你之后还会遇到其他 Hook。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +**Hooks——以 `use` 开头的函数——只能在组件或[自定义 Hooks](/learn/reusing-logic-with-custom-hooks) 的最顶层调用。** 你不能在条件语句、循环语句或其他嵌套函数内调用 Hooks。Hooks 是函数，但将它们视为关于组件需求的无条件声明会很有帮助。在组件顶部 “use” React 特性，类似于在文件顶部“导入”模块。
```suggestion
**Hooks ——以 `use` 开头的函数——只能在组件或[自定义 Hook](/learn/reusing-logic-with-custom-hooks) 的最顶层调用。** 你不能在条件语句、循环语句或其他嵌套函数内调用 Hook。Hook 是函数，但将它们视为关于组件需求的无条件声明会很有帮助。在组件顶部 “use” React 特性，类似于在文件顶部“导入”模块。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +Hooks 是特殊的函数，只在 React [渲染](/learn/render-and-commit#step-1-trigger-a-render)时有效（我们将在下一节详细介绍）。它们能让你 “hook” 到不同的 React 特性中去。
```suggestion
Hook 是特殊的函数，只在 React [渲染](/learn/render-and-commit#step-1-trigger-a-render)时有效（我们将在下一节详细介绍）。它们能让你 “hook” 到不同的 React 特性中去。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +1. **state 变量** (`index`) 与你存储的值。
```suggestion
1. **state 变量** (`index`) 会保存上次渲染的值。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +* Hooks 是以 `use` 开头的特殊函数。它们能让你 “hook” 到像 state 这样的 React 特性中。
```suggestion
* Hook 是以 `use` 开头的特殊函数。它们能让你 “hook” 到像 state 这样的 React 特性中。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +* Hooks 可能会让你想起 imports：它们需要在非条件语句中调用。调用 Hooks 时，包括 `useState`，仅在组件或另一个 Hook 的顶层被调用才有效。
```suggestion
* Hook 可能会让你想起 import：它们需要在非条件语句中调用。调用 Hook 时，包括 `useState`，仅在组件或另一个 Hook 的顶层被调用才有效。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +首先，从 React 导入 `useState`。然后用 `useState` 声明的 state 变量替换 `firstName` 和 `lastName`。最后，用 `setFirstName(...)` 替换每个 `firstName = ...` 赋值，并对 `lastName` 做同样的事情。不要忘记更新 `handleReset`，以便重置按钮。
```suggestion
首先，从 React 导入 `useState`。然后用 `useState` 声明的 state 变量替换 `firstName` 和 `lastName`。最后，用 `setFirstName(...)` 替换每个 `firstName = ...` 赋值，并对 `lastName` 做同样的事情。不要忘记更新 `handleReset`，以使重置按钮生效。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +Hooks 只允许在*什么地方* 调用？这个组件是否违反了任何规则？检查是否有注释禁用了 linter 检查--这往往是 bug 的藏身之处!
```suggestion
Hook 只允许在*什么地方* 调用？这个组件是否违反了任何规则？检查是否有注释禁用了 linter 检查--这往往是 bug 的藏身之处！
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +Hooks 只能在组件函数的顶层调用。这里，第一个 `isSent` 定义遵循这个规则，但是 `message` 的定义位于一个条件语句中。
```suggestion
Hook 只能在组件函数的顶层调用。这里，第一个 `isSent` 定义遵循这个规则，但是 `message` 的定义位于一个条件语句中。
```

2023-02-27 14:40 UTC, daochouwangu commented on beta/src/content/learn/state-a-components-memory.md
> +你还可以删除不必要的`else` 分支以减少嵌套。但要保证对 Hooks 的所有调用都发生在*第一个 `return` 前，这很重要。
```suggestion
你还可以删除不必要的 `else` 分支以减少嵌套。但要保证对 Hook 的所有调用都发生在*第一个 `return` 前，这很重要。
```

2023-02-28 01:01 UTC, daochouwangu approved these changes

2023-02-28 01:01 UTC, daochouwangu approved these changes

2023-02-28 01:40 UTC, awxiaoxian2020 approved these changes

2023-02-28 01:42 UTC, merged