[Beta]: docs(cn): sharing-state-between-components
reactjs/zh-hans.reactjs.org pull request #652
Opened 2021-11-08 12:45 UTC by qinhua

2021-12-11 03:48 UTC, dearalina commented on beta/src/pages/learn/sharing-state-between-components.md
> +2. 从父组件 **传递** 硬编码数据
2. 从父组件 **传递** 硬编码数据。

2021-12-11 08:22 UTC, dearalina requested changes
@qinhua 对于一些翻译进行了二次修改！请查看~

2021-12-11 08:22 UTC, dearalina commented on beta/src/pages/learn/sharing-state-between-components.md
> +**对于每个唯一的状态，都应该有与它对应的组件**。这一原则也被称为拥有[“可信单一数据源”](https://en.wikipedia.org/wiki/Single_source_of_truth)。它并不意味着所有状态都活跃在一个地方——但对每个状态来说，都有一个特定的组成部分来保存这些信息。与复制组件之间的共享状态不同，你需要 *将其提升* 到公共父级，并 *将其传递* 到需要它的子级中
**对于每个独一无二的状态，都应该存在拥有该状态的组件**。这一原理也被称为拥有[“可信单一数据源”](https://en.wikipedia.org/wiki/Single_source_of_truth)。它并不意味着所有状态都活跃在一个地方——对每个状态来说，都需要一个特定的组件来保存这些状态信息。你应该 *将状态提升* 到公共父级，或 *将状态传递* 到需要它的子级中，而不是在组件之间复制共享的状态。

2021-12-11 08:22 UTC, dearalina commented on beta/src/pages/learn/sharing-state-between-components.md
> +你的应用状态会随着操作而改变。通常，当你在处理每个状态的“活跃”位置时，会进行移除或备份操作。这是整个过程的一部分！
你的应用会随着你的操作而变化。当你将状态上下移动时，你依然会想要确定每个状态在哪里“活跃”。这都是过程的一部分！

2021-12-11 08:22 UTC, dearalina commented on beta/src/pages/learn/sharing-state-between-components.md
> +* 将组件视为“受控”（由属性驱动）或“不受控”（由状态驱动）是很有用的。
考虑该将组件视为“受控”（由属性驱动）或是“不受控”（由状态驱动）是十分有益的。

2021-12-11 08:22 UTC, dearalina commented on beta/src/pages/learn/sharing-state-between-components.md
> +现在有两个独立的输入框。为了让它们的状态保持同步：编辑一个输入框时应使用相同的文本更新另一个输入框，反之亦然。你需要将它们的状态提升到父组件中。
现在有两个独立的输入框。为了让它们保持同步：即编辑一个输入框时，另一个输入框也会更新相同的文本，反之亦然。

2021-12-11 08:22 UTC, dearalina commented on beta/src/pages/learn/sharing-state-between-components.md
> +使用 `filterItems(foods, query)` 方法来通过搜索条件过滤列表项。为了测试你的修改，请在输入框中输入 “寿” 来验证是否能过滤出 “寿司”。
使用 `filterItems(foods, query)` 方法来通过搜索条件过滤列表项。为了测试修改是否正确，请尝试在输入框中输入 “寿司” ，“烤肉串” 或 “点心”。

2021-12-11 13:53 UTC, qinhua commented on beta/src/pages/learn/sharing-state-between-components.md
> +3. 为父组件添加状态并将其与事件处理函数一起向下传递
收到

2023-02-18 07:50 UTC, awxiaoxian2020 commented
@qinhua our ci failed.

please check it with `yarn dev` or other possible commands on your local machine to fix it.

2023-02-19 04:35 UTC, awxiaoxian2020 commented
It's weird that we need modify the tsx file.

2023-02-19 06:00 UTC, qinhua commented
> It's weird that we need modify the tsx file.

I found the title level has been modified after compare the MD file with main branch, and that will produce some errors in Navigation.tsx.

2023-02-20 03:09 UTC, daochouwangu requested changes

2023-03-11 00:35 UTC, awxiaoxian2020 commented on beta/src/content/learn/sharing-state-between-components.md
> +每个 `Panel` 组件都有一个布尔值 `isActive`，用于控制其内容是否可见。
@daochouwangu 这里的顺序是不是要改一下比较好

2023-03-13 01:07 UTC, daochouwangu approved these changes

2023-03-13 03:41 UTC, awxiaoxian2020 approved these changes

2023-03-13 03:43 UTC, merged