[Beta]: docs(cn): managing-state
reactjs/zh-hans.reactjs.org pull request #653
Opened 2021-11-08 12:49 UTC by qinhua

2021-12-07 05:32 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +随着你的应用不断变大，去刻意的关注应用状态如何组织，以及数据如何在组件之间流动会对你很有帮助。冗余或重复的状态往往是缺陷的根源。
```suggestion
随着你的应用不断变大，更有意识的去关注应用状态如何组织，以及数据如何在组件之间流动会对你很有帮助。冗余或重复的状态往往是缺陷的根源。
```

2021-12-07 06:36 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +* [“状态提升”如何在组件之间共享状态](/learn/sharing-state-between-components)
```suggestion
* [如何使用“状态提升”在组件之间共享状态](/learn/sharing-state-between-components)
```

2021-12-07 07:25 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +良好的状态组织可以把易于修改和调试的组件与频繁出问题的组件区分开来。最重要的原则是，状态不应包含冗余或重复的信息。如果包含一些多余的状态，我们会很容易忘记去更新它，从而导致问题产生！
```suggestion
良好的状态组织，可以区分开易于修改和调试的组件与频繁出问题的组件。最重要的原则是，状态不应包含冗余或重复的信息。如果包含一些多余的状态，我们会很容易忘记去更新它，从而导致问题产生！
```

2021-12-07 07:31 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +        您的全名是：{fullName}
```suggestion
        您的全名是：{lastName + firstName}
```

2021-12-07 07:45 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +阅读 **[选择状态结构](/learn/choosing-the-state-structure)** 来学习如何简化状态更新并避开常见问题。
```suggestion
阅读 **[选择状态结构](/learn/choosing-the-state-structure)** 来学习如何组织状态并避开错误。
```

2021-12-07 09:51 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +有时候，你希望两个组件的状态始终同步更改。要实现这一点，可以将相关状态从这两个组件上移除，并把状态放到它们的公共父级，再通过属性将状态传递给这两个组件。这被称为“状态提升”，这是编写 React 代码时常做的事。
```suggestion
有时候你希望两个组件的状态始终同步更改。要实现这一点，可以将相关状态从这两个组件上移除，并把这些状态移到最近的父级组件，然后通过 props 将状态传递给这两个组件。这被称为“状态提升”，这是编写 React 代码时常做的事。
```

2021-12-08 08:31 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +在以下示例中，要求每次只能激活一个面板。要实现这一点，父组件将保留状态并为其子组件指定属性，而不是将活动状态保留在每个面板中。
```suggestion
在以下示例中，要求每次只能激活一个面板。要实现这一点，父组件将管理激活状态并为其子组件指定 prop，而不是将激活状态保留在各自的子组件中。
```

2021-12-08 09:43 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +具有跨多个事件处理程序的多状态更新组件可能会令人不知所措。对于这种情况，你可以将组件外部的所有状态更新逻辑合并到一个称为“reducer”的函数中。这样，事件处理程序就会变得简洁，因为它们只需要指定用户的“操作”。在文件的底部，reducer 函数指定状态应该如何更新以响应每个操作！
```suggestion
许多需要更新状态的组件，它们的事件处理程序分布在不同地方可能会令人不知所措。对于这种情况，你可以在组件外部将所有状态更新逻辑合并到一个称为“reducer”的函数中。这样，事件处理程序就会变得简洁，因为它们只需要指定用户的“操作”。在文件的底部，reducer 函数指定状态应该如何更新以响应每个操作！
```

2021-12-08 09:48 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +* [如何避免使用“逐层props”传递数据](/learn/passing-data-deeply-with-context)
```suggestion
* [如何避免数据通过 prop 逐级透传](/learn/passing-data-deeply-with-context)
```

2021-12-08 10:00 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +通常，你会通过 props 将信息从父组件传递给子组件。但是，如果要在树中深入传递一些 prop，或者 UI 树中的许多组件需要相同的 prop，那么传递 prop 可能会变得很麻烦。Context 允许父组件将一些信息提供给它下面的任何组件，不管它有多深，而无需通过 props 显式传递。
```suggestion
通常，你会通过 props 将信息从父组件传递给子组件。但是，如果要在组件树中深入传递一些 prop，或者树里的许多组件需要使用相同的 prop，那么传递 prop 可能会变得很麻烦。Context 允许父组件将一些信息提供给它下层的任何组件，不管该组件多深层也无需通过 props 逐层透传。
```

2021-12-09 06:56 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +阅读 **[使用 Context 进行深层数据传递](/learn/passing-data-deeply-with-context)** 来学习如何使用上下文代替属性传递。
```suggestion
阅读 **[使用 Context 进行深层数据传递](/learn/passing-data-deeply-with-context)** 来学习如何使用 Context 来代替传递 props。
```

2021-12-09 06:57 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +这里，`Heading` 组件通过“询问”最近的 `Section` 来确定其标题级别。每个 `Section` 通过询问父 `Section` 并向其添加一个来跟踪自己的级别。每个 `Section` 都向它下面的所有组件提供信息，而不需要传递 props——它是通过 Context 来实现的。
```suggestion
这里的`Heading` 组件通过“询问”最近的 `Section` 来确定其标题级别。每个 `Section` 的级别是通过给父 `Section`添加的级别来确定的 。每个 `Section` 都向它下层的所有组件提供信息，不需要逐层传递 props，而是通过 Context 来实现。
```

2021-12-09 07:25 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +基于这种方法，使用 reducer 来管理一个具有复杂状态的父组件。组件树中任意位置的其他组件都可以通过上下文读取其状态。还可以派发操作来更新状态。
```suggestion
基于这种想法，使用 reducer 来管理一个具有复杂状态的父组件。组件树中任何深度的其他组件都可以通过 context 读取其状态。还可以 dispatch 一些 action 来更新状态。
```

2021-12-09 18:18 UTC, qinhua commented on beta/src/pages/learn/managing-state.md
> +这里，`Heading` 组件通过“询问”最近的 `Section` 来确定其标题级别。每个 `Section` 通过询问父 `Section` 并向其添加一个来跟踪自己的级别。每个 `Section` 都向它下面的所有组件提供信息，而不需要传递 props——它是通过 Context 来实现的。
这里有些空格要修改一下，辛苦大佬了。

> 这里的`Heading` 组件通过“询问”最近的 `Section` 来确定其标题级别。

- `Heading` 前面少了个空格 

> 每个 `Section` 的级别是通过给父 `Section`添加的级别来确定的 。

- 第二个 `Section` 后面少了空格，末尾句号前多了一个空格

2021-12-09 18:31 UTC, qinhua commented on beta/src/pages/learn/managing-state.md
> +具有跨多个事件处理程序的多状态更新组件可能会令人不知所措。对于这种情况，你可以将组件外部的所有状态更新逻辑合并到一个称为“reducer”的函数中。这样，事件处理程序就会变得简洁，因为它们只需要指定用户的“操作”。在文件的底部，reducer 函数指定状态应该如何更新以响应每个操作！
> 许多需要更新状态的组件，它们的事件处理程序分布在不同地方可能会令人不知所措。

这里读起来还是感觉怪怪的，哈哈。
不知道换成下面这样读起来会不会好一点呢？

> 对于那些需要更新多个状态的组件来说，过于分散的事件处理程序可能会令人不知所措。

2021-12-10 00:49 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +具有跨多个事件处理程序的多状态更新组件可能会令人不知所措。对于这种情况，你可以将组件外部的所有状态更新逻辑合并到一个称为“reducer”的函数中。这样，事件处理程序就会变得简洁，因为它们只需要指定用户的“操作”。在文件的底部，reducer 函数指定状态应该如何更新以响应每个操作！
会通顺了很多！

2021-12-10 00:52 UTC, lyanmm commented on beta/src/pages/learn/managing-state.md
> +这里，`Heading` 组件通过“询问”最近的 `Section` 来确定其标题级别。每个 `Section` 通过询问父 `Section` 并向其添加一个来跟踪自己的级别。每个 `Section` 都向它下面的所有组件提供信息，而不需要传递 props——它是通过 Context 来实现的。
是我粗心了🤣

2022-01-22 06:28 UTC, KnowsCount commented on beta/src/pages/learn/managing-state.md
> +    return <h1>感谢您！</h1>
```suggestion
    return <h1>对了！</h1>
```

2022-01-22 06:29 UTC, KnowsCount commented on beta/src/pages/learn/managing-state.md
> +    </form>
请问这几处改变代码是为什么？

2022-01-22 06:30 UTC, KnowsCount commented on beta/src/pages/learn/managing-state.md
> +      let shouldError = Math.random() > 0.5;
```suggestion
      let shouldError = Math.random() > 0.5;
```

请勿改变原文代码。

2022-01-22 06:30 UTC, KnowsCount requested changes
1. 尽量避免 `您` 的使用。
2. 文中多次出现更改原文代码的情况，请避免。

2022-01-22 10:22 UTC, qinhua commented on beta/src/pages/learn/managing-state.md
> +    </form>
> 请问这几处改变代码是为什么？

官方后面更新了示例

2022-01-28 10:42 UTC, qinhua commented on beta/src/pages/learn/managing-state.md
> +      let shouldError = Math.random() > 0.5;
已更新

2022-05-27 03:34 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +在本节中，你将学习如何组织好状态，如何保持状态更新逻辑的可维护性，以及如何跨组件共享状态。
```suggestion
```

2022-05-27 03:34 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +随着你的应用不断变大，更有意识的去关注应用状态如何组织，以及数据如何在组件之间流动会对你很有帮助。冗余或重复的状态往往是缺陷的根源。
```suggestion
随着你的应用不断变大，更有意识的去关注应用状态如何组织，以及数据如何在组件之间流动会对你很有帮助。冗余或重复的状态往往是缺陷的根源。在本节中，你将学习如何组织好状态，如何保持状态更新逻辑的可维护性，以及如何跨组件共享状态。
```

2022-05-27 03:35 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +        </Panel>
```suggestion
      </Panel>
```

2022-05-27 03:36 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +React 允许你覆盖默认行为，可通过向组件传递一个唯一 `key`（如 `<Chat key={email}/>` 来 *强制* 重置其状态。
```suggestion
React 允许你覆盖默认行为，可通过向组件传递一个唯一 `key`（如 `<Chat key={email}/>` 来 *强制* 重置其状态。这会告诉 React ，如果收件人不同，应将其作为一个 **不同的** `Chat` 组件，需要使用新数据和 UI（比如输入框）来重新创建它。现在，在接收者之间切换时就会重置输入框——即使渲染的是同一个组件。
```

2022-05-27 03:36 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +这告诉 React ，如果收件人不同，应将其作为一个 *不同的* `Chat` 组件，需要使用新数据和 UI（比如输入框）来重新创建它。现在，在接收者之间切换时就会重置输入框——即使渲染的是同一个组件。
```suggestion
```

2022-05-27 03:37 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +  }) {
```suggestion
}) {
```

2022-05-27 03:38 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +import { useTasksDispatch } from './TaskBoardContext.js';
```suggestion
import { useTasksDispatch } from './TasksContext.js';
```

2022-05-27 03:39 UTC, QC-L commented on beta/src/pages/learn/managing-state.md
> +  - KnowsCount
```suggestion
  - KnowsCount
  - QC-L
```

2022-05-27 03:40 UTC, merged