[Beta]:docs(cn): translation api reactdom done
reactjs/zh-hans.reactjs.org pull request #662
Opened 2021-11-12 08:22 UTC by liu-jin-yi

2021-12-07 14:47 UTC, evan-lc commented on beta/src/pages/reference/reactdom.md
> +ReactDOM 包能够让你在页面上渲染 React 组件。
```suggestion
ReactDOM package 能够让你在页面上渲染 React 组件。
```

2021-12-07 15:20 UTC, evan-lc commented on beta/src/pages/reference/reactdom.md
> +可以将一段 JSX （"React 元素"）渲染到浏览器 DOM 容器中。
```suggestion
可以将一段 JSX （“React 元素”）渲染到浏览器 DOM 容器节点中。
```

2021-12-08 15:30 UTC, evan-lc commented on beta/src/pages/reference/reactdom.md
> +通常情况下，你会在你的应用程序的顶层使用 ReactDOM 来渲染你的组件。你要么直接使用它，要么交由 [框架](/learn/start-a-new-react-project#building-with-react-and-a-framework) 为你渲染。你的大部分组件应该 *不* 需要导入这个模块。
```suggestion
通常情况下，你会在你的应用程序的顶层使用 ReactDOM 来展示你的组件。你要么直接使用它，要么交由 [框架](/learn/start-a-new-react-project#building-with-react-and-a-framework) 为你使用。你的大部分组件应该 *不* 需要导入这个模块。
```

2022-06-02 12:34 UTC, awxiaoxian2020 requested changes

2022-06-02 12:34 UTC, awxiaoxian2020 commented on beta/src/pages/reference/reactdom.md
> +通常情况下，你会在你的应用程序的顶层使用 ReactDOM 来展示你的组件。你要么直接使用它，要么交由 [框架](/learn/start-a-new-react-project#building-with-react-and-a-framework) 为你使用。你的大部分组件应该 *不* 需要导入这个模块。
```suggestion
通常情况下，你会在你的应用程序的顶层使用 ReactDOM 来展示你的组件。你要么直接使用它，要么让 [框架](/learn/start-a-new-react-project#building-with-react-and-a-framework) 为你所用。你的大部分组件应该 *不* 需要导入这个模块。
```

2022-06-04 04:04 UTC, awxiaoxian2020 approved these changes

2023-02-14 12:47 UTC, awxiaoxian2020 commented
I think this PR should be closed. Please let me know if I'm wrong. :)

2023-02-14 12:47 UTC, closed without merging