[Beta]: docs(cn): translate learn/manipulating-the-dom-with-refs.md
reactjs/zh-hans.reactjs.org pull request #665
Opened 2021-11-14 15:03 UTC by SylviaZ89

2021-12-07 14:08 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +- `ref` JSX 属性如何与 `useRef` Hook 相关联
```suggestion
- JSX 中的 `ref` 属性如何与 `useRef` Hook 相关联
```

2021-12-07 14:26 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +`useRef` Hook 返回一个对象，该对象有一个名为 `current` 的属性。最初，`myRef.current` 是 `null`。当 React 为这个 `<div>` 创建一个 DOM 节点时，React 会把对该节点的引用放入 `myRef.current`。然后，你可以从 [事件处理器](/learn/responding-to-events) 访问此 DOM 节点，并使用在
```suggestion
`useRef` Hook 返回一个仅拥有 `current` 属性的对象。最开始，`myRef.current` 的值是 `null`。当 React 为这个 `<div>` 创建一个 DOM 节点时，React 会把对该节点的引用赋值给 `myRef.current`。然后，你可以从 [事件处理器](/learn/responding-to-events) 访问此 DOM 节点，并使用在其上定义的内置 [浏览器 APIs](https://developer.mozilla.org/docs/Web/API/Element)。
```

2021-12-07 14:32 UTC, SylviaZ89 commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +`useRef` Hook 返回一个对象，该对象有一个名为 `current` 的属性。最初，`myRef.current` 是 `null`。当 React 为这个 `<div>` 创建一个 DOM 节点时，React 会把对该节点的引用放入 `myRef.current`。然后，你可以从 [事件处理器](/learn/responding-to-events) 访问此 DOM 节点，并使用在
> ```suggestion
> `useRef` Hook 返回一个仅拥有 `current` 属性的对象。最开始，`myRef.current` 的值是 `null`。当 React 为这个 `<div>` 创建一个 DOM 节点时，React 会把对该节点的引用赋值给 `myRef.current`。然后，你可以从 [事件处理器](/learn/responding-to-events) 访问此 DOM 节点，并使用在其上定义的内置 [浏览器 APIs](https://developer.mozilla.org/docs/Web/API/Element)。
> ```

这里我觉得不改动也可以(◦˙▽˙◦)

2021-12-08 04:07 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +一个组件中可以有多个 ref。在这个例子中，有一个由三张图片和三个按钮组成的轮播，通过调用浏览器的 [`scrollIntoView()`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollIntoView) 方法，在相应的 DOM 节点上将它们居中显示在视口中：
```suggestion
一个组件中可以有多个 ref。在这个例子中，有一个由三张图片和三个按钮组成的轮播，点击按钮会调用相应 DOM 节点的浏览器 [`scrollIntoView()`](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollIntoView) 方法将它们居中显示在视口中：
```

2021-12-08 05:17 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +在上面的例子中，有一个预定义数量的 refs。但有时候，你可能需要ref 指向列表中的每个项目，而你又不知道会有多少个。像这样做**是行不通的**：
```suggestion
在上面的例子中，ref 的数量是预先确定的。但有时候，你可能需要为列表中的每一项都绑定 ref ，而你又不知道会有多少项。像下面这样做**是行不通的**：
```

2021-12-08 05:19 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +这是因为 **Hooks 只能在组件的顶层被调用。** 不能在循环、条件判断或 `map()` 函数中调用 `useRef`。
```suggestion
这是因为 **Hooks 只能在组件的顶层被调用。** 不能在循环语句、条件语句或 `map()` 函数中调用 `useRef`。
```

2021-12-08 05:31 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +这使你可以之后从 Map 读取单个 DOM 节点。
```suggestion
这使你之后可以从 Map 读取单个 DOM 节点。
```

2021-12-08 05:38 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +相反，解决方案是**将函数传递给 `ref` 属性**。这称为 “ ref 回调”。当需要设置 ref 时，React 将使用 DOM 节点调用你的 ref 回调，并在需要清除它时使用 `null` 来调用。这使你可以维护自己的数组或 [Map](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Ob
```suggestion
相反，解决方案是**将函数传递给 `ref` 属性**。这称为 “ ref 回调”。当需要设置 ref 时，React 将调用你的 ref 回调并传入 DOM 节点，在需要清除它时传入 `null`。这使你可以维护自己的数组或 [Map](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map)，并通过其索引或某种类型的 ID 访问任何 ref。
```

2021-12-08 11:11 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +1. `<MyInput ref={inputRef} />` 告诉 React 将对应的 DOM 节点放入 `inputRef.current` 中。但是，由 `MyInput` 组件传参进来 —— 默认情况下，它不会。
```suggestion
1. `<MyInput ref={inputRef} />` 告诉 React 将对应的 DOM 节点放入 `inputRef.current` 中。但是，这取决于 `MyInput` 组件允许这种行为  —— 默认情况下，它不会。
```

2021-12-08 11:34 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +这里，`MyInput` 中的 `realInputRef` 保存了实际的输入 DOM 节点。 但是，`useImperativeHandle` 指示 React 提供你自己的特殊对象作为父组件的 ref 值。 所以 `Form` 组件内的 `inputRef.current` 将只有 `focus` 方法。在这种情况下，ref “句柄” 不是 DOM 节点，而是你在 `useImperativ
```suggestion
这里，`MyInput` 中的 `realInputRef` 保存了实际的 input DOM 节点。 但是，`useImperativeHandle` 指示 React 将你自己指定的对象作为父组件的 ref 值。 所以 `Form` 组件内的 `inputRef.current` 将只有 `focus` 方法。在这种情况下，ref “句柄” 不是 DOM 节点，而是你在 `useImperativeHandle` 调用中创建的自定义对象。
```

2021-12-08 11:49 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +**通常，你将从事件处理器访问 refs。** 如果你想对 ref 执行某些操作，但没有特定的事件可以执行此操作，你可能需要一个 effect。我们将在下一页讨论 effect。
```suggestion
**通常，你将从事件处理器访问 refs。** 如果你想使用 ref 执行某些操作，但没有特定的事件可以执行此操作，你可能需要一个 effect。我们将在下一页讨论 effect。
```

2021-12-08 12:05 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +为了说明这个问题，这个例子包括一条欢迎消息和两个按钮。第一个按钮使用 [条件渲染](/learn/conditional-rendering) 和 [state](/learn/state-a-components-memory) 切换它的存在，就像你通常在 React 中所做的那样。第二个按钮使用 [`remove()` DOM API](https://developer.mozilla.o
```suggestion
为了说明这个问题，这个例子包括一条欢迎消息和两个按钮。第一个按钮使用 [条件渲染](/learn/conditional-rendering) 和 [state](/learn/state-a-components-memory) 切换它的显示和隐藏，就像你通常在 React 中所做的那样。第二个按钮使用 [`remove()` DOM API](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/remove) 将其从 React 控制之外的 DOM 中强行移除.
```

2021-12-08 12:09 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +**避免更改由 React 管理的 DOM 节点。** 修改、向 React 管理的元素添加子元素、从中删除子元素会导致不一致的视觉结果，或与上述类似的崩溃。
```suggestion
**避免更改由 React 管理的 DOM 节点。** 对 React 管理的元素进行修改、添加子元素、从中删除子元素会导致不一致的视觉结果，或与上述类似的崩溃。
```

2021-12-08 12:18 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +做到单击 “搜索” 按钮时，将焦点放在搜索域上。
```suggestion
做到点击 “搜索” 按钮时，使搜索域获得焦点。
```

2021-12-08 12:27 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +做到单击 “搜索” 按钮将焦点放在搜索域上。请注意，每个组件都在单独的文件中定义，并且不能将其移出。如何将它们连接在一起？
```suggestion
做到单击 “搜索” 按钮使得搜索域获取焦点。请注意，每个组件都在单独的文件中定义，并且不能将其移出。如何将它们连接在一起？
```

2021-12-08 12:29 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +你需要 `forwardRef` 来通过传参从你自己的组件中暴露一个 DOM 节点，比如 `SearchInput`。
```suggestion
你需要 `forwardRef` 来主动从你自己的组件中暴露一个 DOM 节点，比如 `SearchInput`。
```

2021-12-08 12:35 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +你需要向 `SearchButton` 添加一个`onClick` 属性，并让  `SearchButton` 将其向下传递给浏览器 `<button>`。你还要向下传递一个 ref 给 `<SearchInput>`，它将转发给真正的 `<input>` 并填充它。最后，在单击处理器中，你将对存储在该 ref 中的 DOM 节点调用 `focus`。
```suggestion
你需要向 `SearchButton` 添加一个`onClick` 属性，`SearchButton` 会将其向下传递给浏览器原生 `<button>`。你还要向下传递一个 ref 给 `<SearchInput>`，`<SearchInput>` 将转发 ref 给真正的 `<input>` 并对它进行赋值。最后，在单击事件处理器中，你将能对存储在该 ref 中的 DOM 节点调用 `focus`。
```

2021-12-09 05:46 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +2. 将其用作 `<input ref={inputRef}>` 传递。这告诉 React **将这个 `<input>` 的 DOM 节点放入 `inputRef.current`。**
```suggestion
2. 像 `<input ref={inputRef}>` 这样传递它。这告诉 React **将这个 `<input>` 的 DOM 节点放入 `inputRef.current`。**
```

2021-12-09 05:54 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +## 获取指向节点的 ref
```suggestion
## 获取指向节点的 ref {/*Getting a ref to the node*/}
```

2021-12-09 05:56 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +### 示例: 使文本输入框获得焦点
```suggestion
### 示例: 使文本输入框获得焦点 {/*Example: Focusing a text input*/}
```

2021-12-09 05:57 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +### 示例: 滚动至一个元素
```suggestion
### 示例: 滚动至一个元素 {/*Example: Scrolling to an element*/}
```

2021-12-09 05:57 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +## 访问另一个组件的 DOM 节点
```suggestion
## 访问另一个组件的 DOM 节点 {/*Accessing another component's DOM nodes*/}
```

2021-12-09 05:58 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +## React 何时添加 refs
```suggestion
## React 何时添加 refs {/*When React attaches the refs*/}
```

2021-12-09 05:58 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +## 使用 refs 操作 DOM 的最佳实践
```suggestion
## 使用 refs 操作 DOM 的最佳实践 {/*Best practices for DOM manipulation with refs*/}
```

2021-12-09 05:58 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +### 播放和暂停视频
```suggestion
### 播放和暂停视频 {/*Play and pause the video*/}
```

2021-12-09 05:59 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +### 使搜索域获得焦点
```suggestion
### 使搜索域获得焦点 {/*Play and pause the video*/}
```

2021-12-09 05:59 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +### 滚动图像轮播
```suggestion
### 滚动图像轮播 {/*Scrolling an image carousel*/}
```

2021-12-09 06:00 UTC, ZhangDaZongWei commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +### 使分开的组件中的搜索域获得焦点
```suggestion
### 使分开的组件中的搜索域获得焦点 {/*Focus the search field with separate components*/}
```

2021-12-12 09:35 UTC, SylviaZ89 commented on beta/src/pages/learn/manipulating-the-dom-with-refs.md
> +## 获取指向节点的 ref
看到最近提交的原文在标题后都加了 {/*getting-a-ref-to-the-node*/}，要怎么处理呢？直接显示出来？

2023-02-23 14:07 UTC, daochouwangu requested changes

2023-02-25 05:15 UTC, SylviaZ89 commented
@daochouwangu Thanks！Suggested changes commited，LGTM

2023-02-28 00:58 UTC, daochouwangu approved these changes

2023-02-28 01:39 UTC, merged