docs(cn): reference/usestate
reactjs/zh-hans.reactjs.org pull request #666
Opened 2021-11-14 17:04 UTC by kingzez

@QC-L translate done, please review.

2021-12-08 11:26 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +## 使用 state {#using-state}
@kingzez 请调整一下锚点，`{#using-state}` =>`{/*using-state*/}`

2021-12-08 11:41 UTC, watonyweng requested changes

2021-12-08 11:41 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +调用 `useState` 并将初始 state 传给它。React 将存储你传递的 state，并将其返回给你。
调用 `useState` 并传递初始 state 。

2021-12-08 11:41 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +你将得到 JSX 的最新的 state 值。
你将得到 JSX 中最新的 state 值。

2021-12-08 11:41 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +* 当常规变量起作用时，不要使用 state。State 仅用于[在重新渲染之间保留信息](/learn/state-a-components-memory)。
当常规变量起作用时，不要使用 state。State 仅用于[在重新渲染之间持久化信息](/learn/state-a-components-memory)。

2021-12-08 11:41 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +Updater 函数有点冗长，但有时它们会派上用场。它们允许你访问待处理 state，而不是最终渲染时的 state。如果你想把[多个更新排队处理](/learn/queueing-a-series-of-state-updates)，这会很有帮助。
如果你想把[多个更新排队处理](/learn/queueing-a-series-of-state-updates)，这将会很有用。

2021-12-08 11:41 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +或者，你可以在要返回的对象外加上括号：
或者，你可以包裹要返回的对象：

2021-12-08 11:41 UTC, watonyweng commented on beta/src/pages/reference/usestate.md
> +这是性能优化。您可以使用它来避免在重新渲染时创建较大的对象或数组。
这是一个性能优化。你可以使用它来避免在重新渲染时创建较大的对象或数组。

2023-02-14 12:55 UTC, awxiaoxian2020 commented
This PR should adjust the directory structure.

2023-02-27 07:29 UTC, closed without merging