docs(cn): translate learn/javascript-in-jsx-with-curly-braces into Chinese
reactjs/zh-hans.reactjs.org pull request #672
Opened 2021-11-20 14:11 UTC by flynn-eye

2021-12-07 10:09 UTC, Megrax requested changes

2021-12-07 10:09 UTC, Megrax commented on beta/src/pages/learn/javascript-in-jsx-with-curly-braces.md
> +JSX 允许你在 JavaScript 中编写类似 HTML 的标记，让渲染逻辑和内容在同一处地方。有些情况下，你想在一处标记中添加一些 JavaScript 逻辑或者引用动态属性。这种情况下，你可以在 JSX 的花括号内来编写 JavaScript。
两处“情况下”太赘余了

2021-12-08 06:41 UTC, Megrax commented
hi @flynn-eye 麻烦看看 review 后的建议，更新一下 PR 吧，有觉得不合适的地方可以再讨论一下～

2021-12-08 06:44 UTC, flynn-eye commented
> hi @flynn-eye 麻烦看看 review 后的建议，更新一下 PR 吧，有觉得不合适的地方可以再讨论一下～

好的

2021-12-08 13:26 UTC, flynn-eye commented
> hi @flynn-eye 麻烦看看 review 后的建议，更新一下 PR 吧，有觉得不合适的地方可以再讨论一下～

按照建议已经修改好了

2021-12-08 14:59 UTC, Megrax commented
> 按照建议已经修改好了 @Megrax

呃...你好像只改了74行之前的？@flynn-eye
74行以及之后的好像还是没变啊：https://github.com/reactjs/zh-hans.reactjs.org/pull/672/files#diff-8bd85313f364f68f7cfeaf7d2582d66d7eb84d4aaa7cd0839b2ccaa2e56a9e43R74
🤣

2021-12-08 15:17 UTC, flynn-eye commented
> > 按照建议已经修改好了 @Megrax
> 
> 呃...你好像只改了74行之前的？@flynn-eye 74行以及之后的好像还是没变啊：https://github.com/reactjs/zh-hans.reactjs.org/pull/672/files#diff-8bd85313f364f68f7cfeaf7d2582d66d7eb84d4aaa7cd0839b2ccaa2e56a9e43R74 🤣

这次真改好了 @Megrax M 😵

2021-12-10 05:04 UTC, Megrax approved these changes

2021-12-16 12:39 UTC, Megrax commented on beta/src/pages/learn/javascript-in-jsx-with-curly-braces.md
> +title: 在 JSX 的花括号内使用 JavaScript
```suggestion
title: 在 JSX 的花括号内使用 JavaScript
translators:
  - flynn-eye
  - Megrax
```

2021-12-16 12:41 UTC, Megrax commented on beta/src/pages/learn/javascript-in-jsx-with-curly-braces.md
> +title: 在 JSX 的花括号内使用 JavaScript
@flynn-eye 麻烦添加一下译者信息～

2022-05-30 09:19 UTC, merged