[Beta] docs(cn): translate learn/rendering-lists into Chinese
reactjs/zh-hans.reactjs.org pull request #676
Opened 2021-11-28 06:28 UTC by Megrax

@QC-L pls review

2021-11-30 10:50 UTC, watonyweng submitted a review, later dismissed

2021-12-18 08:24 UTC, rottenpen commented
@Megrax 可以稍微润色一下语句吗，review 了前面一小部分，感觉很多地方都是直译。

2021-12-22 15:48 UTC, rottenpen commented
@Megrax  有进度吗

2021-12-22 15:55 UTC, Megrax commented
> @Megrax 有进度吗

在改～最近有点忙，争取周末搞定🤕

2021-12-25 17:37 UTC, Megrax commented
@rottenpen 尽我所能进行了一些改动和润色，觉得还有问题的地方可以指出来一起讨论一下 ：)

2021-12-28 09:52 UTC, rottenpen commented on beta/src/pages/learn/rendering-lists.md
> +1. 最后，**返回** `listItems`：
```suggestion
3. 最后，**返回** `listItems`：
```

2021-12-28 09:52 UTC, rottenpen commented on beta/src/pages/learn/rendering-lists.md
> +* 如何从组件中抽离出数据，并把它们放入比如数组和对象这样的数据结构中。
```suggestion
* 如何从组件中抽离出数据，并把它们放入像数组、对象这样的数据结构中。
```
比如一般是在句首中用的吧。

2021-12-28 09:52 UTC, rottenpen commented on beta/src/pages/learn/rendering-lists.md
> +这个解法中，我们直接在父级的 `<ul>` 元素里就执行了 `map` 方法。当然如果你想提高代码的可读性，你也可以先用变量保存一下 `map` 之后的结果。
```suggestion
这个解决方案（或者直接用方案）中，我们直接在父级的 `<ul>` 元素里就执行了 `map` 方法。当然如果你想提高代码的可读性，你也可以先用变量保存一下 `map` 之后的结果。
```

2021-12-28 09:52 UTC, rottenpen commented on beta/src/pages/learn/rendering-lists.md
> +`RecipeList` 组件的代码里嵌套了两层 `map`。处于简化代码的考虑，让我们提取出一个接受 `id`，`name`，`ingredients` 作为 props 的 `Recipe` 组件。你会把外层的 `key` 放在哪里，原因是什么？
```suggestion
`RecipeList` 组件的代码里嵌套了两层 `map`。出于简化代码的考虑，我们提取出一个接受 `id`，`name`，`ingredients` 作为 props 的 `Recipe` 组件。这种情况下，你会把外层的 `key` 放在哪里呢？原因是什么？
```

2021-12-28 09:52 UTC, rottenpen commented
@Megrax 好啦

2022-01-01 14:25 UTC, Megrax commented on beta/src/pages/learn/rendering-lists.md
>    profession: 'physicist',
这里是指把 代码里的 `'physicist'` 翻译成 `'物理学家'`？这个我感觉没有必要翻译吧，把代码里有的注释改成中文就差不多了...

2022-01-01 14:26 UTC, Megrax commented on beta/src/pages/learn/rendering-lists.md
> +假设你只想要展示职业是 `chemist` 的人。那么你可以使用 JavaScript 的 `filter()` 方法来返回满足条件的项。这个方法会接受一个数组，让它通过 “过滤器”（一个返回值为 `true` 或 `false` 的函数），最终返回一个只包含满足条件的项的新数组。
这里我觉得没有必要直接对代码块进行翻译，理由同上

2022-01-01 14:29 UTC, Megrax commented on beta/src/pages/learn/rendering-lists.md
> +这个解法中，我们直接在父级的 `<ul>` 元素里就执行了 `map` 方法。当然如果你想提高代码的可读性，你也可以先用变量保存一下 `map` 之后的结果。
这里为什么要增加括号里的部分？我没有 get 到这个点，而且感觉这样不是很通顺🤔

2022-01-02 04:34 UTC, rottenpen commented on beta/src/pages/learn/rendering-lists.md
> +这个解法中，我们直接在父级的 `<ul>` 元素里就执行了 `map` 方法。当然如果你想提高代码的可读性，你也可以先用变量保存一下 `map` 之后的结果。
不是不是 括号是指解决方案或者方案 来替代解法

2022-01-02 04:36 UTC, rottenpen commented on beta/src/pages/learn/rendering-lists.md
>    profession: 'physicist',
看到其他人地名职业之类的是会翻译的

2022-01-02 13:21 UTC, Megrax commented
@rottenpen 对代码中的一些英文进行了翻译，看下还有无问题～

2022-01-04 04:08 UTC, rottenpen commented
@QC-L 好了 没问题了

2023-02-14 13:01 UTC, awxiaoxian2020 commented
需要处理冲突

2023-02-17 08:18 UTC, Megrax commented
@awxiaoxian2020 冲突已解决

2023-02-17 09:06 UTC, awxiaoxian2020 requested changes

2023-02-17 09:06 UTC, awxiaoxian2020 commented on beta/src/content/learn/rendering-lists.md
> +    '我写，擦除，重写',
这里个人建议使用原文，因为代码中文本并不涉及逻辑，保持原文并不会妨碍对上下文的理解。就文本意义而言，这本就是一首诗，不建议翻译。

2023-02-17 09:06 UTC, awxiaoxian2020 commented on beta/src/content/learn/rendering-lists.md
> +这是因为你必须给数组中的每一项都指定一个 `key` ———— 它可以是字符串或数字的形式，只要能唯一标识出各个数组项就行：
破折号为全角，不需要空格。
我为什么感觉这个破折号长了一截……

2023-02-17 09:30 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-02-17 12:07 UTC, daochouwangu requested changes

2023-02-17 12:07 UTC, daochouwangu commented on beta/src/content/learn/rendering-lists.md
> +记住，采用 fragment 语法（通常写作 `<></>`）来包裹 JSX 节点可以避免引入额外的 `<div>` 元素！
```suggestion
记住，采用 fragment 语法（通常写作 `<> </>`）来包裹 JSX 节点可以避免引入额外的 `<div>` 元素！
```

2023-02-23 14:59 UTC, daochouwangu approved these changes

2023-02-23 15:09 UTC, awxiaoxian2020 approved these changes

2023-02-23 15:11 UTC, merged