[Beta]: docs(cn): preserving-and-resetting-state.md
reactjs/zh-hans.reactjs.org pull request #679
Opened 2021-11-30 05:45 UTC by YogaLin

2021-12-09 17:06 UTC, Neo42 requested changes

2021-12-14 09:31 UTC, Neo42 commented
@YogaLin 校对完毕，麻烦处理一下，谢谢

2021-12-15 14:08 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +修复它使得不管选中的顺序如何，表示展开的状态都与各个联系人相关联。
@Neo42 这里修改后 "使得 `expanded` state 无论所选的顺序如何" 感觉有些歧义，主语 expanded state 是没有顺序的。这样呢？“修复它，使得不管选中的顺序如何 `expanded` state 都与各个联系人相关联。”

2021-12-15 14:46 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +目前你切换了玩家后，分数还是没有变化。这两个 `Counter` 出现于相同位置，所以 React 认为是 _同一个_ `Counter` ，只是传了不同的 `person` prop。
“目前，当你切换了玩家时” 中间的逗号不能去掉吗，中文里这样表达感觉不是很通畅。

2021-12-15 14:52 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +修复它使得不管选中的顺序如何，表示展开的状态都与各个联系人相关联。
@YogaLin 没问题，你改的这种读起来比较容易理解

2021-12-15 14:58 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +目前你切换了玩家后，分数还是没有变化。这两个 `Counter` 出现于相同位置，所以 React 认为是 _同一个_ `Counter` ，只是传了不同的 `person` prop。
对，逗号应该去掉的，不知道当时怎么想的😂

2021-12-15 15:12 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +修复它使得不管选中的顺序如何，表示展开的状态都与各个联系人相关联。
```suggestion
修复它，使得不管选中的顺序如何 `expanded` state 都与各个联系人相关联。
```

2021-12-15 15:46 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +修复它使得不管选中的顺序如何，表示展开的状态都与各个联系人相关联。
不过你之前的句子结构没有错，确实"如何"后面应该加逗号，因为”如何“后面是个完整的句子，不加逗号的话会结构混乱。我改的时候漏写了，sorry

2021-12-15 15:48 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +修复它，使得不管选中的顺序如何 `expanded` state 都与各个联系人相关联。
不过你之前的句子结构没有错，确实"如何"后面应该加逗号，因为”如何“后面是个完整的句子，不加逗号的话会结构混乱。我改的时候漏写了，sorry

```suggestion
修复它，使得不管选中的顺序如何，`expanded` state 都与各个联系人相关联。
```

2021-12-15 16:05 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +修复它，使得不管选中的顺序如何 `expanded` state 都与各个联系人相关联。
Never mind，辛苦你查了这么多漏

2021-12-18 05:50 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +有没有办法让 React 重新创建而不是复用 DOM ？
这样修改后“它”有被理解成“重新创建的 DOM”的歧义。

2021-12-18 05:50 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +- 不要嵌套组件的定义，否则将意外地重置状态。
加个“被”是不是好些
```suggestion
- 不要嵌套组件的定义，否则你会意外导致 state 被重置。
```

2021-12-18 05:51 UTC, YogaLin commented
@Neo42 所有的 suggestions 都已经处理了，还有4处想再讨论一下，麻烦有空看看。（第一次参加翻译，谢谢你指出我的较多错误）

2021-12-23 15:09 UTC, QC-L commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +* React 怎样“看待”组件结构
```suggestion
* React 怎样“处理”组件结构
```

2021-12-23 15:10 UTC, QC-L commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +* React 怎样“看待”组件结构
这里用处理更好些吧？看待感觉很奇怪...

2021-12-23 15:30 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +* React 怎样“看待”组件结构
原文“see”就是看的意思

2021-12-23 15:34 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +现在切换收件人都将清除文本字段：
那这样呢？
```suggestion
现在切换收件人就会总是导致文本字段被清除：
```

2021-12-23 15:34 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +- 不要嵌套组件的定义，否则将意外地重置状态。
没问题

2021-12-23 16:04 UTC, Neo42 commented
> @Neo42 所有的 suggestions 都已经处理了，还有4处想再讨论一下，麻烦有空看看。（第一次参加翻译，谢谢你指出我的较多错误）

谢谢，我会尽快处理

2021-12-24 06:35 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +* React 怎样“看待”组件结构
这里对应下文想表达的应该是”组件在 React 看来是一种树形的结构“，但确实”看待“读起来怪怪的。

“如何处理”也能体现出来这层意思？

2021-12-24 06:38 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +- 不要嵌套组件的定义，否则将意外地重置状态。
另外加了个 “地”
```suggestion
- 不要嵌套组件的定义，否则你会意外地导致 state 被重置。

```

2021-12-24 06:40 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +现在切换收件人都将清除文本字段：
还是不太通顺的感觉

2021-12-24 07:10 UTC, QC-L commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +* React 怎样“看待”组件结构
我知道原文的是 see...
但这里用 看待 很奇怪
组件被 React 看做树形结构，会将组件视为树形结构处理

2021-12-24 08:22 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +* React 怎样“看待”组件结构
所以才会加引号的呀😂用处理的话就不用加引号了

2021-12-25 07:11 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
>  <Illustration src="/images/docs/illustrations/i_keys-in-trees.png" alt="React distinguishes between components with different keys, even if they are of the same type." />
从语法上讲，这里时态是一般现在时，“表示通常性、规律性、习惯性、真理性（即事实）的动作或状态，或者动作有时间规律发生的事件的一种时间状态”（百度百科），所以用“会”应该是合理的。如果是“能用”，那原文应该是 “can distinguish”，所以可能有些牵强。

问题也可能出在 “components with different keys” 上，如果不把 “with” 翻译成“用”，而把 “with different keys” 看作修饰 “components” 的定语的话就说的通了——不是 React 用 key 组件，而是 React 会区分 key 不同的组件。
```suggestion
<Illustration src="/images/docs/illustrations/i_keys-in-trees.png" alt="React 会区分 key 不同的组件，即使组件属于同一类型。" />
```

2021-12-25 07:37 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +现在切换收件人都将清除文本字段：
我在这里考虑加一个“就”是因为我认为这一句有在表达前后对比的意思，因为前文说过有不符合预期的特性，改好之后就对比一下，就相当于：“之前……是不符合预期的，改了一下，现在这样**就**对了。”相比之下，不加“就”的话，对比的效果可能就不是那么明显了。

如果在句尾加一个“了”呢？
```suggestion
现在切换收件人就会总是导致文本字段被清除了：
```

2021-12-25 08:08 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +有没有办法让 React 重新创建而不是复用 DOM ？
```suggestion
有没有办法让 React 重新创建 DOM 而不是复用它？
```
这样呢？

一开始的译法“重新创建”后面没有宾语，读起来会有点脱节

2021-12-25 09:11 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +- 不要嵌套组件的定义，否则将意外地重置状态。
我觉得可以的

2021-12-27 08:43 UTC, YogaLin commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +现在切换收件人都将清除文本字段：
越来越拗口了感觉，“导致”是不是可以去掉呢：

```suggestion
现在切换收件人就总会清除文本字段：
```

2022-01-01 10:48 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +现在切换收件人都将清除文本字段：
那还是把“了”加上吧，不然读起来很别扭
```suggestion
现在切换收件人就总会清除文本字段了：
```

2022-01-04 03:50 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +  - Neo42
```suggestion
  - YogaLin
```

2022-01-04 03:50 UTC, Neo42 commented on beta/src/pages/learn/preserving-and-resetting-state.md
> +  - YogaLin
```suggestion
  - Neo42
```

2022-01-04 03:52 UTC, Neo42 commented
@YogaLin 请再把译者名字顺序再调换一下。之前我以为译者名字是按照字母顺序排序，后来 @QC-L 告诉我需要暂时把第一译者放在前面。给你添麻烦了，非常抱歉！

2022-01-04 09:19 UTC, YogaLin commented
> @YogaLin 请再把译者名字顺序再调换一下。之前我以为译者名字是按照字母顺序排序，后来 @QC-L 告诉我需要暂时把第一译者放在前面，以后再决定按字母排序。给你添麻烦了，非常抱歉！

done, 没事哈

2022-01-04 09:49 UTC, Neo42 commented
@QC-L LGTM.

2022-01-06 16:58 UTC, Neo42 approved these changes

2022-04-05 06:33 UTC, KnowsCount approved these changes

2022-05-26 15:57 UTC, merged