docs(cn): translate learn/thinking-in-react
reactjs/zh-hans.reactjs.org pull request #682
Opened 2021-12-02 15:04 UTC by HerbertHe

2021-12-06 11:35 UTC, watonyweng approved these changes

2021-12-07 15:32 UTC, zcfan reviewed
目前部分译文质量欠佳，建议进一步打磨一下～

2021-12-07 15:32 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +想象一下, 你早已从设计者那儿获取了一个 JSON API 和 模型。
假设你已经从设计者那获取了一个 JSON API 和 mockup

2021-12-07 15:32 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +想象一下, 你早已从设计者那儿获取了一个 JSON API 和 模型。
mockup 应该不需要翻译，对技术人员来说原文更好理解，且 mockup 译文并非模型

2021-12-07 15:32 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +title: 在 React 中思考
用 React 的方式思考

2021-12-07 15:32 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +React 可以改变你对设计和构建应用的思考。曾经你看到的可能是森林, 在与 React 工作为伴之后, 你将更享受每一颗独立的树。React 使对于设计系统和 UI 状态的思考更加容易。在本篇教程中, 我们将带你感悟使用 React 进行构建可搜索产品数据表格的心路历程。
译文本身应当是简明流畅的，建议机翻仅做参考，形成译文时请确保合乎中文读者阅读习惯

2021-12-07 15:32 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +## 使用模型开始 {/*start-with-the-mockup*/}
从使用 mockup 开始

2021-12-07 15:32 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +## 自此之后, 该往何处 {/*where-to-go-from-here*/}
👍～

2021-12-08 03:16 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +title: 在 React 中思考
看了下之前翻译为“React 哲学”，建议继续沿用

2021-12-08 04:01 UTC, HerbertHe commented on beta/src/pages/learn/thinking-in-react.md
> +想象一下, 你早已从设计者那儿获取了一个 JSON API 和 模型。
我感觉翻译成原型应该合适，设计者的产品原型的来源。

2021-12-08 06:38 UTC, zcfan requested changes
👍调整这句即可，其他的看起来都不错～

2021-12-08 06:38 UTC, zcfan commented on beta/src/pages/learn/thinking-in-react.md
> +本章只是一个概述, 旨在告诉你如何使用 React 如何进行思考构建组件和应用程序。你可以即刻 [开始一个 React 项目](/learn/installation), 或者 [深潜于在教程中使用到的所有语法](/learn/describing-the-ui)。
```suggestion
本章只是一个概述, 旨在告诉你如何使用 React 如何进行思考构建组件和应用程序。你可以即刻 [开始一个 React 项目](/learn/installation), 或者[深入了解本教程中用到的所有语法](/learn/describing-the-ui)。
```

2021-12-09 04:20 UTC, zcfan approved these changes

2021-12-13 12:02 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
> +React 可以改变你对可见设计和应用构建的思考。曾经你可能已见过成片的森林, 在与 React 工作为伴后, 你将更享受其中每一颗独立的树。React 使思考设计系统和 UI 状态更加容易。在本篇教程中, 我们将带你领略使用 React 进行构建可搜索产品数据表格的全过程。
```suggestion
React 可以改变你对可见设计和应用构建的思考。曾经你可能已见过成片的森林，在与 React 工作为伴后, 你将更享受其中每一颗独立的树。React 使思考设计系统和 UI 状态更加容易。在本篇教程中，我们将带你领略使用 React 进行构建可搜索产品数据表格的全过程。
```

2021-12-13 12:02 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
> +React 可以改变你对可见设计和应用构建的思考。曾经你可能已见过成片的森林, 在与 React 工作为伴后, 你将更享受其中每一颗独立的树。React 使思考设计系统和 UI 状态更加容易。在本篇教程中, 我们将带你领略使用 React 进行构建可搜索产品数据表格的全过程。
检查下标点...

2021-12-14 18:37 UTC, HerbertHe commented on beta/src/pages/learn/thinking-in-react.md
> +React 可以改变你对可见设计和应用构建的思考。曾经你可能已见过成片的森林, 在与 React 工作为伴后, 你将更享受其中每一颗独立的树。React 使思考设计系统和 UI 状态更加容易。在本篇教程中, 我们将带你领略使用 React 进行构建可搜索产品数据表格的全过程。
emmm全部用的半角符号

2022-01-22 06:04 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +你既可以通过从层次结构更高层组件 (如 `FilterableProductTable`) 开始 "自上而下" 构建，也可以通过从更低层级组件 (如 `ProductRow`) "自下而上" 进行构建。在简单的例子中，自上而下构建通常更简单; 而在大型项目中，自下而上构建更简单。
```suggestion
你既可以通过从层次结构更高层组件 (如 `FilterableProductTable`) 开始 "自上而下" 构建，也可以通过从更低层级组件 (如 `ProductRow`) "自下而上" 进行构建。在简单的例子中，自上而下构建通常更简单；而在大型项目中，自下而上构建更简单。
```

2022-01-22 06:04 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +**如果示例看起来很吓人，不要感到烦躁！* 在本篇指南中，我们将更关注于概念而非代码。收藏 [描述 UI](/learn/describing-the-ui) 的内容，将会帮助你填补短板、理解代码。
```suggestion
**如果示例看起来很吓人，不要感到烦躁！**在本篇指南中，我们将更关注于概念而非代码。收藏 [描述 UI](/learn/describing-the-ui) 的内容，将会帮助你填补短板、理解代码。
```

2022-01-22 06:05 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +1. 原始列表中的产品**作为 props 传递，所以它不是 state**。
```suggestion
1. 原始列表中的产品 **被作为 props 传递，所以不是 state**。
```

2022-01-22 06:05 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +4. 过滤后列表中的产品**不是 state，因为可以通过被原始列表中的产品，根据搜索框文本和复选框的值进行计算**。
```suggestion
4. 过滤后列表中的产品 **不是 state，因为可以通过被原始列表中的产品，根据搜索框文本和复选框的值进行计算**。
```

2022-01-22 06:05 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +在验证你应用程序中的最小 state 数据之后，你需要验证哪个组件是通过改变 state 实现可响应的，或者*拥有*这个 state。记住: React 使用单向数据流，通过组件层级结构从父组件传递数据至子组件。这可能不能立马知晓哪个组件拥有什么 state。如果你是第一次阅读此章节可能会感到有挑战性，但可以通过下面的步骤搞定它!
```suggestion
在验证你应用程序中的最小 state 数据之后，你需要验证哪个组件是通过改变 state 实现可响应的，或者 *拥有* 这个 state。记住：React 使用单向数据流，通过组件层级结构从父组件传递数据至子组件。这可能不能立马知晓哪个组件拥有什么 state。如果你是第一次阅读此章节可能会感到有挑战性，但可以通过下面的步骤搞定它!
```

2022-01-22 06:06 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +  - HerbertHe
```suggestion
  - HerbertHe
  - KnowsCount
```

2022-01-22 06:07 UTC, KnowsCount approved these changes

2022-01-28 07:15 UTC, KnowsCount commented on beta/src/pages/learn/thinking-in-react.md
> +构建应用程序的静态版本来渲染你的数据模型，将构建 [组件](/learn/your-first-component) 并复用其它的组件，然后使用 [props](/learn/passing-props-to-a-component) 进行传递数据。Props 是从父组件向子组件传递数据的一种方式。(如果你对 [state](/learn/state-a-components-memory) 章
我认为此处大写没问题，并且就算小写无需在全角句号后加空格。

2022-01-28 07:24 UTC, Bin9o commented on beta/src/pages/learn/thinking-in-react.md
> +构建应用程序的静态版本来渲染你的数据模型，将构建 [组件](/learn/your-first-component) 并复用其它的组件，然后使用 [props](/learn/passing-props-to-a-component) 进行传递数据。Props 是从父组件向子组件传递数据的一种方式。(如果你对 [state](/learn/state-a-components-memory) 章
嗯嗯好的！

2022-05-27 02:42 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
>  Add state to the component with the [`useState()` Hook](/apis/usestate). Hooks let you "hook into" a component's [render cycle](/learn/render-and-commit). Add two state variables at the top of `Filte
```suggestion
用 [`useState()` Hook](/apis/usestate) 为组件添加 state。Hook 可以 "钩住" 组件的 [渲染周期](/learn/render-and-commit)。在 `FilterableProductTable` 的顶部添加两个 state 变量，用于指定你应用程序的初始 state：
```

2022-05-27 02:52 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
> +你可以看见应用程序如何反应。在下面的沙盒代码，过修改`useState('')` 为 `useState('fruit')` 以编辑 `filterText` 的初始值，将会看到搜索输入值和表格更新:
```suggestion
你可以查看你应用程序的表现。在下面的沙盒代码中，通过修改`useState('')` 为 `useState('fruit')` 以编辑 `filterText` 的初始值，你将会发现搜索输入框和表格发生更新:
```

2022-05-27 02:53 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
> +在上面的沙盒中，`ProductTable` 和 `SearchBar` 读取 `filterText` 和 `inStockOnly` props 以渲染表格、输入、复选框。
```suggestion
在上面的沙盒中，`ProductTable` 和 `SearchBar` 读取 `filterText` 和 `inStockOnly` props 以渲染表格、输入、复选框。举个例子，这里展示了 `SearchBar` 如何填充输入的值:
```

2022-05-27 02:56 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
```suggestion
```

2022-05-27 02:59 UTC, QC-L submitted a review, later dismissed

2022-05-27 03:03 UTC, QC-L commented on beta/src/pages/learn/thinking-in-react.md
>  (If this code looks intimidating, go through the [Quick Start](/learn/) first!)
```suggestion
（如果你无法理解这段代码，请先阅读 [快速入门](/learn/) 章节！)
```

2022-05-27 03:04 UTC, merged