Update reference-react-component.md
reactjs/zh-hans.reactjs.org pull request #691
Opened 2021-12-10 09:21 UTC by zaoren

There are some small mistakes that can mislead others 
reference https://github.com/facebook/react/issues/9117

2021-12-31 09:49 UTC, KimYangOfCat requested changes

2021-12-31 09:49 UTC, KimYangOfCat commented on content/docs/reference-react-component.md
> +`componentDidMount()` 会在组件挂载后（在他自己的容器中挂载完成了，并不代表已经挂载到DOM树）立即调用。依赖于 DOM 节点的初始化应该放在这里。如需通过网络请求获取数据，此处是实例化请求的好地方。
@zaoren Hello，我查阅了本段的英文：

>componentDidMount() is invoked immediately after a component is mounted (inserted into the tree). Initialization that requires DOM nodes should go here. If you need to load data from a remote endpoint, this is a good place to instantiate the network request.

这里括号里面的内容应该是用于解释 mounted 这个动词哒，意思就是说挂载这个动作与”插入DOM树中“一样；所以这里应该不是想表达”已经挂载到 DOM 树中“的这个观点。
也许是这个中括号的位置不太对，导致了你的误解，可以考虑调整如下：


```suggestion
`componentDidMount()` 会在组件挂载（插入 DOM 树中）后立即调用。依赖于 DOM 节点的初始化应该放在这里。如需通过网络请求获取数据，此处是实例化请求的好地方。
```

2022-01-22 06:27 UTC, KnowsCount commented on content/docs/reference-react-component.md
> +`componentDidMount()` 会在组件挂载后（在他自己的容器中挂载完成了，并不代表已经挂载到DOM树）立即调用。依赖于 DOM 节点的初始化应该放在这里。如需通过网络请求获取数据，此处是实例化请求的好地方。
是的，我们文档翻译要尽量尊重原文，如果你觉得文档有错或者不妥当，请去英文文档。

2022-02-07 16:47 UTC, closed without merging

2022-03-16 01:45 UTC, zaoren commented on content/docs/reference-react-component.md
> +`componentDidMount()` 会在组件挂载后（在他自己的容器中挂载完成了，并不代表已经挂载到DOM树）立即调用。依赖于 DOM 节点的初始化应该放在这里。如需通过网络请求获取数据，此处是实例化请求的好地方。
好的 感谢大佬回复... 才看到邮件😂