docs(cn): reacting-to-input-with-state
reactjs/zh-hans.reactjs.org pull request #692
Opened 2021-12-11 13:24 UTC by BBboy01

Chinese version lear/reacting-to-input-with-state

2021-12-31 08:17 UTC, KimYangOfCat commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +你所写的 `updateDOM` 函数展示了当你设置状态时，React 在幕后都做了什么。（然而，React 同样为了那些自上次设置状态后未改变的属性避免接触 DOM。）
```suggestion
你所写的 `updateDOM` 函数展示了当你设置状态时，React 在幕后都做了什么。（然而，为了那些自上次设置状态后未改变的属性，React 同样避免修改 DOM。）
```
个人理解 此处 的 touch 应该是修改的意思。

2021-12-31 08:17 UTC, KimYangOfCat commented on beta/src/pages/learn/reacting-to-input-with-state.md
>  If you're struggling to think where to start, the stub below already has most of the structure in place. If you start here, fill in the missing logic in the `updateDOM` function. (Refer to the origin
```suggestion
```
英文原文忘记删除了

2021-12-31 08:17 UTC, KimYangOfCat commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +你会想要避免状态内容中的重复，因此你只需要关注那些必要的部分。花费一点时间在重构你的状态结构上，这会让你的组件更容易理解，减少重复并且避免意料之外的意义。你的目的是**避免在内存中的状态不表示任何你想让用户看到的有效的 UI 的情况。**（比如你绝对不会想要在展示错误信息的时候同时禁用掉输入框，导致用户无法纠正错误！）
```suggestion
你会想要避免状态内容中的重复，因此你只需要关注那些必要的部分。花费一点时间在重构你的状态结构上，这会让你的组件更容易理解，减少重复并且避免意外的含义。你的目的是**防止出现在内存中的状态不代表任何你希望用户看到的有效 UI 的情况。**（比如你绝对不会想要在展示错误信息的时候同时禁用掉输入框，导致用户无法纠正错误！）
```

2021-12-31 08:17 UTC, KimYangOfCat commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +试试当点击图片时*删除*外面 `<div>` 的类名 `background--active`，但是将 `picture--active` 的类名添加到 `<img>` 上。当再次点击背景图片时恢复最开始的 CSS 类名。
```suggestion
试试当点击图片时*删除*外部 `<div>` 的类名 `background--active`，但是将 `picture--active` 的类名添加到 `<img>` 上。当再次点击背景图片时恢复最开始的 CSS 类名。
```

2021-12-31 08:17 UTC, KimYangOfCat commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +  - BBboy01
```suggestion
  - BBboy01
  - KimYangOfCat
```

2021-12-31 08:19 UTC, KimYangOfCat submitted a review, later dismissed

2021-12-31 08:19 UTC, KimYangOfCat commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +  - BBboy01
```suggestion
  - BBboy01
  - KimYangOfCat
```
Thanks!

2022-01-16 02:28 UTC, TinaaaaP reviewed
great work! just a few comments for fluency and word order

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +接下来你会需要在内存中通过 [`useState`](/reference/usestate) 表示组件中的视图状态。诀窍很简单：state 的每个部分都是“处于变化中的”，并且**你需要让“变化的部分”尽可能的少**。太复杂的话会产生更多 bug！
```suggestion
接下来你会需要在内存中通过 [`useState`](/reference/usestate) 表示组件中的视图状态。诀窍很简单：state 的每个部分都是“处于变化中的”，并且**你需要让“变化的部分”尽可能的少**。更复杂的程序会产生更多 bug！
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +先从*绝对必须*存在的状态开始。例如，你需要存储输入的 `message` 以及存储最后一个错误的 `error` （如果存在的话）：
```suggestion
先从*绝对必须*存在的状态开始。例如，你需要存储输入的 `message` 以及用于存储最后一个错误的 `error` （如果存在的话）：
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +如果你很难立即想出最好的办法，那就先从添加足够多的 state 开始，“确保”所有可能的视图状态都囊括其中：
```suggestion
如果你很难立即想出最好的办法，那就先从添加足够多的 state 开始，*确保*所有可能的视图状态都囊括其中：
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +你会想要避免 state 内容中的重复，因此你只需要关注那些必要的部分。花费一点时间在重构你的 state 结构上，这会让你的组件更容易理解，减少重复并且避免意外的含义。你的目的是**防止出现在内存中的 state 不代表任何你希望用户看到的有效 UI 的情况。**（比如你绝对不会想要在展示错误信息的时候同时禁用掉输入框，导致用户无法纠正错误！）
```suggestion
你会想要避免 state 内容中的重复，从而只需要关注那些必要的部分。花一点时间来重构你的 state 结构，会让你的组件更容易被理解，减少重复并且避免歧义。你的目的是**防止出现在内存中的 state 不代表任何你希望用户看到的有效 UI 的情况。**（比如你绝对不会想要在展示错误信息的时候同时禁用掉输入框，导致用户无法纠正错误！）
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +这有一些问题让你可以批判性地审视自己声明的 state 变量：
```suggestion
这有一些你可以问自己的， 关于 state 变量的问题：
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +* **这个 state 是否会导致矛盾？**例如，`isTyping` 与 `isSubmitting` 的状态不能同时为 `true`。当有矛盾产生的同时也就说明了这个 state 没有足够的约束条件。两个布尔值有四种可能的组合，但是只有三种对应有效的状态。为了将“不可能”的状态移除，你可以将 `'typing'`、`'submitting'` 以及 `'success'` 这三个中的其中一
```suggestion
* **这个 state 是否会导致矛盾？**例如，`isTyping` 与 `isSubmitting` 的状态不能同时为 `true`。矛盾的产生通常说明了这个 state 没有足够的约束条件。两个布尔值有四种可能的组合，但是只有三种对应有效的状态。为了将“不可能”的状态移除，你可以将 `'typing'`、`'submitting'` 以及 `'success'` 这三个中的其中一个与 `status` 结合。
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +* **你是否可以在另一个相反的 state 变量中得到相同的信息？**`isError` 是多余的，因为你可以检查 `error !== null`。
```suggestion
* **你是否可以通过另一个 state 变量的相反值得到相同的信息？**`isError` 是多余的，因为你可以检查 `error !== null`。
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +尽管这些代码相对与最初的命令式的例子来说更长，但是却更健壮。将所有的交互变为 state 的改变，可以让你避免之后引入新的视图状态后导致现有 state 被破坏。同时也使你在不必改变交互逻辑本身的情况下，更改每个状态中应该显示的内容。
```suggestion
尽管这些代码相对与最初的命令式的例子来说更长，但是却更不易损。将所有的交互变为 state 的改变，可以让你避免之后引入新的视图状态后导致现有 state 被破坏。同时也使你在不必改变交互逻辑本身的情况下，更改每个状态中应该显示的内容。
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +试试当点击图片时*删除*外部 `<div>` 的类名 `background--active`，但是将 `picture--active` 的类名添加到 `<img>` 上。当再次点击背景图片时恢复最开始的 CSS 类名。
```suggestion
试一试实现当点击图片时*删除*外部 `<div>` 的类名 `background--active`，并将 `picture--active` 的类名添加到 `<img>` 上。当再次点击背景图片时将恢复最开始的 CSS 类名。
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +检验这个通过点击图片然后点击图片的外面：
```suggestion
通过点击图片然后点击图片外围来确定这个版本可用：
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +这是一个通过扁平的 JavaScript 和 DOM 实现的小型表单。通过与它交互来理解它的行为表现：
```suggestion
这是一个通过纯 JavaScript 和 DOM 实现的小型表单。通过与它交互来理解它的行为表现：
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +这个表单的模式切换在两个模式中：在编辑中的模式，你可以看到输入框；在查看模式，你只能看到结果。按钮的标签会根据你所处的模式在“编辑”和“保存”两者中切换。当你改变输入框的内容时，欢迎的信息会最下面实时更新。
```suggestion
这个表单在两种模式间切换：编辑模式，你可以看到输入框；查看模式，你只能看到结果。按钮的标签会根据你所处的模式在“编辑”和“保存”两者中切换。当你改变输入框的内容时，欢迎信息会最下面实时更新。
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +也要确保它会在按钮中更新文本内容！
```suggestion
也要确保它在底下更新文本内容！
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +如果没有 React，你可以十分健壮地并且使其与 React 的版本十分相似地重构这个代码吗？像 React 那样，如果 state 是明确的，这个重构的代码会是什么样的？
```suggestion
如果没有 React，你可以重构这段代码，使其逻辑不易损并且与 React 版本更相似么？如果 state 是明确的，像React中一样，这个重构的代码会是什么样的？
```

2022-01-16 02:28 UTC, TinaaaaP commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +你所写的 `updateDOM` 函数展示了当你设置 state 时，React 在幕后都做了什么。（然而，为了那些自上次设置 state 后未改变的属性，React 同样避免修改 DOM。）
```suggestion
你所写的 `updateDOM` 函数展示了当你设置 state 时，React 在幕后都做了什么。（然而，React 同样避免修改那些自上次设置 state 后未改变的属性所相对应的 DOM）
```

2022-01-20 12:23 UTC, BBboy01 commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +3. **表示**内存中的 state，通过 `useState`
这边这样写是为了保持排版整齐，个人觉得现在这样不影响理解，但确实不符合国人阅读习惯

2022-01-20 12:48 UTC, BBboy01 commented on beta/src/pages/learn/reacting-to-input-with-state.md
> +你已经从上面的例子看到如何去实现一个表单了，为了更好地理解如何在 React 中思考，你将会在下面用 React 重新实现操作 UI：
in 表示处于 react 这个第三方库的环境下，例如处于 vue 的环境下组件怎么遍写，以 的话更应该是用 with，我觉得这里强调的是开发者使用第三方库的情况下如何在以该库的编程思维去遍写组件

2023-02-18 05:05 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +在这个命令式 UI 编程的例子中，表单没有使用 React 生成，而是使用原生的 [DOM](https://developer.mozilla.org/zh-CN/docs/Web/API/Document_Object_Model):
```suggestion
在这个命令式 UI 编程的例子中，表单**没有使用** React 生成，而是使用原生的 [DOM](https://developer.mozilla.org/zh-CN/docs/Web/API/Document_Object_Model):
```

2023-02-18 05:09 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +  // Try 'submitting', 'error', 'success'：
```suggestion
  // Try 'submitting', 'error', 'success':
```

2023-02-18 05:10 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +* **错误时**：与输入状态类似，但会多错误的消息
```suggestion
* **无数据**：表单有一个不可用状态的“提交”按钮。
* **输入中**：表单有一个可用状态的“提交”按钮。
* **提交中**：表单完全处于不可用状态，加载动画出现。
* **成功时**：显示“成功”的消息而非表单。
* **错误时**：与输入状态类似，但会多错误的消息。
```

2023-02-18 05:15 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +  5. 连接事件处理函数去设置 state
```suggestion
  1. 定位你的组件中不同的视图状态。
  2. 确定是什么触发了这些 state 的改变。
  3. 通过 `useState` 模块化内存中的 state。
  4. 删除任何不必要的 state 变量。
  5. 连接事件处理函数去设置 state。
```

2023-02-18 05:16 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +#### 添加和删除一个 CSS 类名 {/*add-and-remove-a-css-class*/}
```suggestion
#### 添加和删除一个 CSS class {/*add-and-remove-a-css-class*/}
```

2023-02-18 05:18 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +试一试实现当点击图片时*删除*外部 `<div>` 的类名 `background--active`，并将 `picture--active` 的类名添加到 `<img>` 上。当再次点击背景图片时将恢复最开始的 CSS 类名。
```suggestion
尝试实现当点击图片时*删除*外部 `<div>` 的 CSS class `background--active`，并将 `picture--active` 的 CSS class 添加到 `<img>` 上。当再次点击背景图片时将恢复最开始的 CSS class。
```

2023-02-18 05:20 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +        alt="印度尼西亚，Kampung Pelangi 的彩虹屋"
```suggestion
        alt="Rainbow houses in Kampung Pelangi, Indonesia"
```

2023-02-18 05:21 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +        alt="印度尼西亚，Kampung Pelangi 的彩虹屋"
```suggestion
        alt="Rainbow houses in Kampung Pelangi, Indonesia"
```

2023-02-18 05:22 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +          alt="印度尼西亚，Kampung Pelangi 的彩虹屋"
```suggestion
          alt="Rainbow houses in Kampung Pelangi, Indonesia"
```

2023-02-18 05:22 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +        alt="印度尼西亚，Kampung Pelangi 的彩虹屋"
```suggestion
        alt="Rainbow houses in Kampung Pelangi, Indonesia"
```

2023-02-18 05:23 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +* 当图片处于非激活状态时，CSS 类名是 `background background--active` 和 `picture`。
```suggestion
* 当图片处于激活状态时，CSS class 是 `background` 和 `picture picture--active`。
* 当图片处于非激活状态时，CSS class 是 `background background--active` 和 `picture`。
```

2023-02-18 05:24 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +一个布尔类型的 state 已经足够表示图片是否处于激活状态。最初的工作仅仅是移除或添加 CSS 类名。然而在 React 中你需要去*描述*什么是你想要看到的而非*操作* UI 元素。因此你需要基于当前 state 去计算这两个 CSS 类名。同时你需要去 [阻止冒泡行为](/learn/responding-to-events#stopping-propagation)，只有这样点击图片的时
```suggestion
一个布尔类型的 state 已经足够表示图片是否处于激活状态。最初的工作仅仅是移除或添加 CSS class。然而在 React 中你需要去*描述*什么是你想要看到的而非*操作* UI 元素。因此你需要基于当前 state 去计算这两个 CSS class。同时你需要去 [阻止冒泡行为](/learn/responding-to-events#stopping-propagation)，只有这样点击图片的时候不会触发点击背景的回调。
```

2023-02-18 05:54 UTC, awxiaoxian2020 requested changes

2023-02-18 05:54 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +React 使用声明式模式控制 UI。你不必直接控制 UI 的各个部分，而应该声明你的组件可以处于的不同 state，并根据用户的输入在它们之间切换。这与设计师对 UI 的思考方式很相似。
```suggestion
React 控制 UI 的方式是声明式的。你不必直接控制 UI 的各个部分，只需要声明组件可以处于的不同状态，并根据用户的输入在它们之间切换。这与设计师对 UI 的思考方式很相似。
```
这里第一段主要讲设计哲学，所以我觉得不太涉及代码层面的东西。个人更倾向于翻译 state。

2023-02-18 05:54 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +* 了解如何列举你的组件可能处于的不同视图状态
```suggestion
* 了解如何列举组件可能处于的不同视图状态
```

2023-02-18 05:54 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +## 声明式 UI 与 命令式 UI 的比较 {/*how-declarative-ui-compares-to-imperative*/}
```suggestion
## 声明式 UI 与命令式 UI 的比较 {/*how-declarative-ui-compares-to-imperative*/}
```

2023-02-18 05:54 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +3. **表示**内存中的 state，通过 `useState`
```suggestion
3. **表示**内存中的 state（需要使用 `useState`）
```

2023-02-18 05:54 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +### 步骤 1：定位你的组件中不同的视图状态 {/*step-1-identify-your-components-different-visual-states*/}
```suggestion
### 步骤 1：定位组件中不同的视图状态 {/*step-1-identify-your-components-different-visual-states*/}
```

2023-02-18 06:30 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +类似这样的页面通常被称作“实时风格指南”或“故事板”。
@awxiaoxian2020 "living styleguides" 和 "storybooks" 这样翻译你觉得合适么，感觉怪怪的，尤其是 storybooks，不翻译会不会好点

2023-02-18 06:58 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +类似这样的页面通常被称作“实时风格指南”或“故事板”。
是的，storybook 更像是一个库。参见https://storybook.js.org，https://react-styleguidist.js.org，建议均不翻译。

2023-02-18 06:58 UTC, awxiaoxian2020 requested changes

2023-02-18 06:58 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +<Diagram name="responding_to_input_flow" height={350} width={688} alt="流程图从左到右共有 5 个节点。第一个 ’empty‘ 节点通过 ’start typing‘ 分支与 ’typing‘ 节点相连。‘typing’ 节点则通过 ‘press submit’ 分支与拥有两个分支的 ‘submitting’ 节点相连。其中
此处的标点符号似乎需要修正。

2023-02-18 13:40 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +类似这样的页面通常被称作“实时风格指南”或“故事板”。
嗯嗯，当初是觉得此处 storybooks 不像是说 storybook 这个库，不翻译确实方便开发者理解

2023-02-18 13:43 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +类似这样的页面通常被称作“实时风格指南”或“故事板”。
storybook 本义应该是一种前端或设计界的术语，我不太了解

2023-02-18 13:58 UTC, awxiaoxian2020 requested changes

2023-02-18 13:58 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +以上两种情况中，**你必须设置 [ state 变量](/learn/state-a-components-memory#anatomy-of-usestate)去更新 UI**。对于正在开发中的表单来说，你需要改变 state 以响应几个不同的输入：
```suggestion
以上两种情况中，**你必须设置 [state 变量](/learn/state-a-components-memory#anatomy-of-usestate) 去更新 UI**。对于正在开发中的表单来说，你需要改变 state 以响应几个不同的输入：
```

2023-02-18 14:00 UTC, awxiaoxian2020 submitted a review, later dismissed

2023-02-19 09:30 UTC, daochouwangu requested changes

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +你所写的 `updateDOM` 函数展示了当你设置 state 时，React 在幕后都做了什么。（然而，React 同样避免修改那些自上次设置 state 后未改变的属性所相对应的 DOM）
```suggestion
你所写的 `updateDOM` 函数展示了当你设置 state 时，React 在幕后都做了什么。（而且 React 不会修改对应 state 没改变的 DOM ）
```

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +如果没有 React，你可以十分健壮地并且使其与 React 的版本十分相似地重构这个代码吗？像 React 那样，如果 state 是明确的，这个重构的代码会是什么样的？
```suggestion
你能否不用 React 重构这段代码，使其即具有健壮性并且和 React 版代码类似吗？并且像 React 那样具有显式的状态？
```
这里不太好翻译

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +这是之前的挑战中的没有使用 React 而写的命令式原始沙盒：
```suggestion
这是之前的挑战中的没有使用 React 而写的命令式代码：
```

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +这是之前的挑战中的没有使用 React 而写的命令式原始沙盒：
或者不翻译 sandbox ？

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +你的任务是在 下方的沙盒中用 React 再次实现它。为了方便，标记已经转换为 JSX，但是你需要让它像原版那样显示和隐藏输入框。
```suggestion
你的任务是在下方的沙盒中用 React 再次实现它。为了方便，标记已经转换为 JSX，但是你需要让它像原版那样显示和隐藏输入框。
```

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +这是一个通过纯 JavaScript 和 DOM 实现的小型表单。通过与它交互来理解它的行为表现：
```suggestion
这是一个通过纯 JavaScript 和 DOM 实现的小型表单。先来随便使用一下来看看它有什么功能吧：
```
不确定是否更好

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +  1. 定位你的组件中不同的视图状态。
```suggestion
  1. 写出你的组件中所有的视图状态。
```

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +如果你不知道该从哪里入手，下面的部分已经有了大部分的结构。如果你从这里开始的话，只需要在 `updateDOM` 函数中补充缺失的逻辑即可。（需要时请参考原始代码）
```suggestion
如果你不知道该从哪里入手，下面的代码已经有了大部分的结构。如果你从这里开始的话，只需要在 `updateDOM` 函数中补充缺失的逻辑即可。（需要时请参考原始代码）
```
俩个`部分`有点重复

2023-02-19 09:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +title: State 驱动输入
标题是否换掉，感觉没表达出文章的意思？

2023-02-19 09:45 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +类似这样的页面通常被称作“living styleguides”或“storybooks”。
空格是不用的。单复数确实要改

2023-02-19 09:47 UTC, awxiaoxian2020 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +为了可视化这个流程，请尝试在纸上画出圆形标签以表示每个状态，两个状态之间的改变用箭头表示。你可以像这样画出很多流程并且在写代码前解决许多 bug。
全角符号与其他字符间不加空格，我觉得先要遵循这个。

2023-02-25 08:39 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +你已经从上面的例子看到如何去实现一个表单了，为了更好地理解如何在 React 中思考，你将会在下面用 React 重新实现操作 UI：
`how to think in React` 翻译成 `React 思考方式` 不太合适吧。就好像在 Vue 中如何写组件、在 React 中如何写组件，强调的是在"React 中"

2023-02-25 09:08 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +title: State 驱动输入
这篇是“管理 state”的首篇，主要阐述了用 state 管理 DOM 的输入相较于传统方式的优势，你有什么好的建议么

2023-03-01 10:26 UTC, awxiaoxian2020 commented
@daochouwangu 看一下相关讨论

2023-03-03 05:30 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +title: State 驱动输入
xx驱动xx，前者应该是更内在，更本质的东西。
state 驱动 输入
像是因果颠倒，而且文章的内容是声明式 UI
英文直译也是 用 state 来对输入给出反应。
用 `State 驱动 UI` 会不会好一点

2023-03-05 07:22 UTC, BBboy01 commented on beta/src/content/learn/reacting-to-input-with-state.md
> +title: State 驱动输入
Input 翻译成 UI 会不会改变作者的意思。
要不 Reacting 还是不要翻译成驱动而是翻译成响应，`用 State 响应输入`，这样直译对 React 用户也比较直观。

2023-03-06 00:51 UTC, daochouwangu commented on beta/src/content/learn/reacting-to-input-with-state.md
> +title: State 驱动输入
可以

2023-03-06 06:45 UTC, daochouwangu approved these changes

2023-03-06 10:42 UTC, awxiaoxian2020 approved these changes

2023-03-06 10:45 UTC, merged