[Beta]: docs(cn): extracting-state-logic-into-a-reducer
reactjs/zh-hans.reactjs.org pull request #693
Opened 2021-12-11 13:28 UTC by qinhua

2021-12-25 15:42 UTC, yyyang1996 requested changes

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +- **reducers 必须是纯净的。** 这一点和 [状态更新函数](/learn/queueing-a-series-of-state-updates) 是相似的，`reducers` 在是在渲染时运行的！（actions 会排队直到下一次渲染)。 这就意味着 `reducers` [必须纯净](/learn/keeping-components-pure)，即当输入一定时，输出也是一定的
```suggestion
- **reducers 必须是纯净的。** 这一点和 [状态更新函数](/learn/queueing-a-series-of-state-updates) 是相似的，`reducers` 在是在渲染时运行的！（actions 会排队直到下一次渲染)。 这就意味着 `reducers` [必须纯净](/learn/keeping-components-pure)，即当输入相同时，输出也是相同的。它们不应该包含异步请求、定时器或者任何副作用（对组件外部有影响的操作）。它们应该以不可变值的方式去更新 [对象](/learn/updating-objects-in-state) 和 [数组](/learn/updating-arrays-in-state)。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +Reducers 应该是纯净的，所以它们不应该去修改 state。而 Immer 为你提供了一种特殊的 `draft` 对象，你可以用它安全的修改 state。在底层，Immer 会基于当前 state 创建一个副本。这就是为什么通过 `useImmerReducer` 来管理 reducers 时可以修改第一个参数，但不需要返回一个新的 state 的原因。
```suggestion
Reducers 应该是纯净的，所以它们不应该去修改 state。而 Immer 为你提供了一种特殊的 `draft` 对象，你可以通过它安全的修改 state。在底层，Immer 会基于当前 state 创建一个副本。这就是为什么通过 `useImmerReducer` 来管理 reducers 时，可以修改第一个参数，且不需要返回一个新的 state 的原因。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +* 使用 Immer 来帮你编写变更风格的 reducers。
```suggestion
* 使用 Immer 来帮助你在 reducer 里直接修改状态。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +  1. 通过事件处理函数派发 actions；
```suggestion
  1. 通过事件处理函数 dispatch actions；
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +### 通过事件处理函数派发 actions {/*dispatch-actions-from-event-handlers*/}
```suggestion
### 通过事件处理函数 dispatch actions {/*dispatch-actions-from-event-handlers*/}
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +将这两个 `// TODO` 替换为 `dispatch` 相应的操作。如果要查看 actions 对于的参数和类型，请阅读 `messerreducer.js` 中的 reducer。reducer 已经写好了，不需要修改它。你只需要在 `ContactList.js` 和 `Chat.js` 中派发动作即可。
```suggestion
将这两个 `// TODO` 替换为 `dispatch` 相应的 action。如果要查看 action 的结构和类型，请查看 `messerreducer.js` 中的 reducer。reducer 已经写好了，你不需要再修改它。你只需要在 `ContactList.js` 和 `Chat.js` 中 dispatch 相应的 action 即可。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +`dispatch` 函数在这两个组件中都是可用的，因为它已经以 prop 的形式传递进来了。所以你需要用相应的 action 对象来调用 `dispatch` 函数。
```suggestion
`dispatch` 函数在这两个组件中都是可用的，因为它已经以 prop 的形式传递进来了。因此你需要通过传入相应的 action 对象来调用 `dispatch` 函数。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +这表示你的 `action` 对象应该有一个 `type: 'changed_selection'`。同时你也可以看到 `action.contactId` 被使用到了，所以你需要传入一个 `contactId` 属性到你的动作中。
```suggestion
这表示你的 `action` 对象应该有一个 `type: 'changed_selection'`。同时你也可以看到 `action.contactId` 被使用到了，所以你需要传入一个 `contactId` 属性到你的 action 对象中。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +通过 reducer 的代码，你可以推断出 actions 需要像下面这样：
```suggestion
从 reducer 函数的代码中，你可以推断出 actions 需要像下面这样：
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +在 “发送” 按钮的事件处理程序中，有很多方法可以用来清空输入框。一种方法是显示一个 alert，然后派发一个带有空 `message` 的 `edited_message` 操作：
```suggestion
在 “发送” 按钮的事件处理程序中，有很多方法可以用来清空输入框。一种方法是显示一个 alert，然后 dispatch 一个名为 `edited_message` 且带有空 `message` 的 action：
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +然而，从用户的角度来看，发送消息与编辑字段是不同的操作。为了体现这一点，你可以创建一个名为 `sent_message` 的 *新动作*，并在 reducer 中单独处理：
```suggestion
然而，从用户的角度来看，发送消息与编辑字段是不同的操作。为了体现这一点，你可以创建一个名为 `sent_message` 的新 *action*，并在 reducer 中单独处理：
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +在任何一种解决方案中，最重要的是你 **不要** 把 `alert` 放置在 reducer 中。reducer 必须是一个纯函数——它应该只计算下一个状态。而不应该 “做” 其它事情，包括向用户显示消息。这应该在事件处理程序中处理。（为了便于捕获这样的错误，React 会在严格模式下多次调用你的 reducer。这就是为什么当你在 reducer 中加入一个 alert，它会触发两次的原因。）
```suggestion
不管是哪一种解决方案，最重要的是你 **不要** 把 `alert` 放置在 reducer 中。reducer 必须是一个纯函数——它应该只计算下一个状态。而不应该 “做” 其它事情，包括向用户显示消息。这应该在事件处理程序中处理。（为了便于捕获这样的错误，React 会在严格模式下多次调用你的 reducer。这就是为什么当你在 reducer 中加入一个 alert，它会触发两次的原因。）
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
>  In this example, switching between different recipients always clears the text input:
在这个示例中，切换收件人时总是会清空输入框。

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +显然，为了实现不同行为，你不需要修改任何事件处理程序。但如果没使用 reducer 的话，你不得不在每个事件处理程序中去更新状态。
```suggestion
显然，你不再需要通过修改任何事件处理程序来实现不同的行为。但如果没使用 reducer 的话，你不得不在每个事件处理程序中去更新状态。
```

2021-12-25 15:42 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +派发一个 action 去调用一个具有当前 state 和 action 的 reducer，并将结果存储为下一个 state。下面是它在代码中的样子：
```suggestion
dispatch 一个 action 去调用一个具有当前 state 和 action 的 reducer，并将结果存储为下一个 state。下面是它在代码中的样子：
```

2021-12-26 05:47 UTC, yyyang1996 requested changes

2021-12-26 05:47 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> + title: 把状态逻辑移到 Reducer 中
```suggestion
title: 把状态逻辑移到 Reducer 中
```

2021-12-26 05:47 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +随着组件复杂度的增加，你将很难一眼看清所有组件的状态更新逻辑。例如，下面的 `TaskBoard` 组件有一个数组类型的状态 `tasks`，并通过三个不同的事件处理程序来实现添加、删除和修改：
```suggestion
随着组件复杂度的增加，你将很难一眼看清所有的组件状态更新逻辑。例如，下面的 `TaskBoard` 组件有一个数组类型的状态 `tasks`，并通过三个不同的事件处理程序来实现任务的添加、删除和修改：
```

2021-12-26 14:15 UTC, yyyang1996 requested changes

2021-12-26 14:15 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +在前面的例子中，你从 React 中导入了 `useReducer` 钩子。这一次，你将自己实现 `useReducer` 钩子。这里有一个模板，你可以从它开始。它不应该超过 10 行代码。
```suggestion
在前面的例子中，你从 React 中导入了 `useReducer` Hook。现在，你将学习自己实现 `useReducer` Hook。你可以从这个模板开始，它不会超过 10 行代码。
```

2021-12-26 14:15 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +这是因为被派发的 actions 在下一次渲染之前都是处于排队状态的，[和更新函数类似](/learn/queueing-a-series-of-state-updates)。
```suggestion
这是因为被派发的 actions 在下一次渲染之前都是处于排队状态的，这和 [状态更新函数](/learn/queueing-a-series-of-state-updates) 类似。
```

2021-12-26 14:15 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +Reducer 是处理状态的另一种方式。你可以通过三个步骤从 `useState` 迁移到 `useReducer`：
```suggestion
Reducer 是处理状态的另一种方式。你可以通过三个步骤将 `useState` 迁移到 `useReducer`：
```

2021-12-26 14:15 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +你的任务是改变状态的组织形式，以便能记住 _每个联系人_ 的消息草稿。你需要对 reducer、初始状态和组件进行一些修改。
```suggestion
你的任务是改变状态的组织形式，以便能记住 *每个联系人* 的消息草稿。你需要对 reducer、初始状态和组件进行一些修改。
```

2021-12-26 14:15 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +           type: 'sent_message',
```suggestion
          type: 'sent_message',
```

2021-12-26 14:16 UTC, yyyang1996 requested changes

2021-12-26 14:16 UTC, yyyang1996 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +  - qinhua
```suggestion
  - qinhua
  - yyyang1996
```

2021-12-27 13:02 UTC, yyyang1996 approved these changes

2021-12-27 13:02 UTC, yyyang1996 commented
@QC-L

2022-01-11 01:37 UTC, KnowsCount submitted a review, later dismissed

2022-01-11 05:55 UTC, QC-L commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +这个组件的每个事件处理程序都通过 `setTasks` 来更新状态。随着这个组件的不断迭代，其状态逻辑也会越来越多。为了降低复杂度，且让所有逻辑都可以存放在一个易于理解的地方，你可以将这些状态逻辑移到组件之外的一个称为 **reducer** 的函数中。
```suggestion
这个组件的每个事件处理程序都通过 `setTasks` 来更新状态。随着这个组件的不断迭代，其状态逻辑也会越来越多。为了降低这种复杂度，并让所有逻辑都可以存放在一个易于理解的地方，你可以将这些状态逻辑移到组件之外的一个称为 **reducer** 的函数中。
```

2022-01-11 05:56 UTC, QC-L approved these changes

2022-01-11 05:57 UTC, merged