[Beta] docs(cn): translate learn/index into Chinese
reactjs/zh-hans.reactjs.org pull request #696
Opened 2021-12-12 16:53 UTC by x-cold

2021-12-13 08:20 UTC, QC-L commented on beta/src/pages/learn/index.md
> -## Introduction {/*introduction*/}
这里的锚点丢失了

2021-12-13 09:10 UTC, sooia requested changes

2021-12-13 09:18 UTC, sooia commented on beta/src/pages/learn/index.md
> +这是一个最基本的 React 应用。用于让您第一次品尝 React，**编辑下面的代码** 然后让它显示您的名字：
```suggestion
这是一个最基本的 React 应用。要获得React的初体验，**编辑下面的代码** 然后让它显示您的名字：
```

2021-12-13 09:18 UTC, sooia commented on beta/src/pages/learn/index.md
> +React 没有规定要如何构建整个应用程序。它能帮助您定义和组合组件，但在其他问题中不会妨碍您。这意味您可以选择一个生态系统解决方案来解决路由、样式和数据获取等问题，或者您也可以 [使用一个提供了很多内置功能的框架](/learn/start-a-new-react-project#building-with-react-and-a-framework)
```suggestion
React 没有规定要如何构建整个应用程序。它能帮助您定义和组合组件，但在其他问题中不会妨碍您。这意味您可以选择一个生态系统解决方案来解决路由、样式和数据获取等问题，或者您也可以 [使用一个提供了很多内置功能的框架](/learn/start-a-new-react-project#building-with-react-and-a-framework)。
```

2021-12-13 09:22 UTC, sooia commented on beta/src/pages/learn/index.md
> +* [必要时如何使用安全舱逃离 React](/learn/escape-hatches)
```suggestion
* [必要时如何退出 React](/learn/escape-hatches)
```

2021-12-15 08:00 UTC, sooia approved these changes
Approve.

2021-12-15 08:01 UTC, sooia submitted a review, later dismissed

2021-12-16 02:25 UTC, watonyweng commented on beta/src/pages/learn/index.md
> +这是一个最基本的 React 应用。用于让您第一次品尝 React，**编辑下面的代码** 然后让它显示您的名字：
这是一个最基本的 React 应用。要获得 React 的初体验，**编辑下面的代码** 然后让它显示您的名字：

2021-12-16 07:29 UTC, sooia reviewed
添加翻译者和Reviewer名字。

2021-12-16 07:29 UTC, sooia commented on beta/src/pages/learn/index.md
>  ---
```suggestion
translator:
 - x-cold
 - sooia（刘俊）
```

2021-12-16 07:29 UTC, sooia commented on beta/src/pages/learn/index.md
>  ---
添加翻译者和Review者名字。

2021-12-19 12:40 UTC, QC-L commented on beta/src/pages/learn/index.md
> + - sooia（刘俊）
这里只保留 github 的名称，不要多余内容

2021-12-19 13:05 UTC, x-cold commented on beta/src/pages/learn/index.md
> + - sooia（刘俊）
@sooia 辛苦移除一下？

2021-12-19 13:05 UTC, x-cold commented on beta/src/pages/learn/index.md
> + - sooia（刘俊）
```suggestion
 - sooia
```

2021-12-23 15:07 UTC, x-cold commented on beta/src/pages/learn/index.md
> +        {sculpture.artist} 的 <i>{sculpture.name} </i>
```suggestion
        <i>{sculpture.name} </i>
        {sculpture.artist} 的 <i>{sculpture.name} </i>
```

2021-12-23 15:08 UTC, x-cold commented on beta/src/pages/learn/index.md
>        <label>
```suggestion
      <h2>Let’s check you in</h2>
      <label>
```

2021-12-23 15:09 UTC, x-cold commented on beta/src/pages/learn/index.md
>        <label>
```suggestion
      <h2>Let’s check you in</h2>
      <label>
```

2021-12-23 15:09 UTC, x-cold commented on beta/src/pages/learn/index.md
> +      <h3>
```suggestion
      <p>
```

2021-12-23 15:10 UTC, x-cold commented on beta/src/pages/learn/index.md
> +      <h3>
```suggestion
      <p>
```

2021-12-23 15:10 UTC, x-cold commented on beta/src/pages/learn/index.md
> +      </h3>
```suggestion
      </p>
```

2021-12-23 15:11 UTC, x-cold commented on beta/src/pages/learn/index.md
> +      <h3>
```suggestion
      <p>
```

2021-12-23 15:15 UTC, x-cold commented on beta/src/pages/learn/index.md
> +有时，您希望两个组件的 state 始终一起更改。要做到这一点，在它们两个中都删除该 state，将它移动到它们最近的公共父节点，然后通过 props 将它传递给它们。 这被称为["提升 state"](/learn/sharing-state-between-components)，这是编写 React 代码时最常见的事情之一。 例如，在像下面这样的手风琴组件中，一次应该只有一个面板处于激活状
```suggestion
这可能看起来像一个小变化，但在 React 应用中很多 bug 都是这么修复的。

有时，您希望两个组件的 state 始终一起更改。要做到这一点，在它们两个中都删除该 state，将它移动到它们最近的公共父节点，然后通过 props 将它传递给它们。 这被称为["提升 state"](/learn/sharing-state-between-components)，这是编写 React 代码时最常见的事情之一。 例如，在像下面这样的手风琴组件中，一次应该只有一个面板处于激活状态。父组件不应该将激活 state 保存在每个单独的面板内，而是保存在父组件的 state 中并通过 props 指定给子组件。
```

2021-12-23 16:16 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +欢迎阅读 React 文档! 此文档是您在本站点能找到的信息的概览。
```suggestion
欢迎阅读 React 文档！本文档是你在本站点能找到的信息的概览。
```

请避免半角符号的保留以及“您”的使用。符号要求：

> - 所有半角（英文）符号，请转为使用全角（中文）符号
> - 数字使用半角字符
> - -- 破折号，请使用全角 —— 替代
> - 缩写与原文保持一致

2021-12-23 16:17 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +这是一个最基本的 React 应用。要获得React的初体验，**编辑下面的代码** 然后让它显示您的名字：
```suggestion
这是一个最基本的 React 应用。可以 **编辑下面的代码** 并让它显示你的名字，以获得 React 的初体验：
```

2021-12-23 16:18 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +* [如何让您的用户界面响应交互](/learn/adding-interactivity)
```suggestion
* [如何让你的用户界面响应交互](/learn/adding-interactivity)
```

2021-12-23 16:18 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +* [随着您的应用的增长，如何保持逻辑的可维护性](/learn/managing-state)
```suggestion
* [随着应用的增长，如何保持逻辑的可维护性](/learn/managing-state)
```

2021-12-23 16:20 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +React 擅长交互设计和编程。**它让您可以将一个复杂的用户界面，分解为可嵌套和可重用的片段，我们称之为[组件](/learn/your-first-component)，它们可以很好的进行组合。** 如果您已经有编程的背景，这可能会让您想起用函数来编程。如果您是一名设计师，它可能会让您联想到图层组合设计。如果您对这两门学科都是新手，那也没关系。很多人都是在接触 React 的过程中才熟悉它们
```suggestion
React 擅长交互设计和编程。**它让你可以将一个复杂的用户界面，分解为我们称之为 [组件](/learn/your-first-component) 的可嵌套和可重用的片段，而这些组件可以很好的进行组合。** 如果你已经有编程的背景，这可能会让你想起用函数来编程。而如果你是一名设计师，它可能会让你联想到图层组合设计。如果你对这两个领域都不熟悉，那也没关系。很多人都是在接触 React 的过程中才熟悉它们的。使用 React 也许还会让你想起用玩具砖块来建造城堡。有时候，它甚至非常有趣。
```

2021-12-23 16:21 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +React 没有规定要如何构建整个应用程序。它能帮助您定义和组合组件，但在其他问题中不会妨碍您。这意味您可以选择一个生态系统解决方案来解决路由、样式和数据获取等问题，或者您也可以 [使用一个提供了很多内置功能的框架](/learn/start-a-new-react-project#building-with-react-and-a-framework)。
```suggestion
React 没有规定要如何构建整个应用程序。它能帮助你定义和组合组件，但在其他问题中不会妨碍你。这意味你可以选择一个生态系统解决方案来解决路由、样式和数据获取等问题，或者你也可以 [使用一个提供了很多内置功能的框架](/learn/start-a-new-react-project#building-with-react-and-a-framework)。
```

2021-12-23 16:21 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +### 您可以用 React 做什么？{/*what-can-you-do-with-react*/}
```suggestion
### 你可以用 React 做什么？{/*what-can-you-do-with-react*/}
```

2021-12-23 16:22 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +实际上，大量开发者们使用 React 来创建各种用户界面——从像按钮和下拉菜单这样的小控件到整个应用程序。 **这些文档将教您在 web 平台上使用 React。** 然而，您在这里学到的大部分内容同样适用于 [React Native](https://reactnative.dev/)，它可以让您为 Android、iOS，甚至 [Windows 和 macOS](https://micro
```suggestion
React 能派上一大堆用场！开发者们使用 React 来创建各种用户界面——从像按钮和下拉菜单这样的小控件到整个应用程序。 **这些文档将教你在 web 平台上使用 React。** 然而，你在这里学到的大部分内容同样适用于 [React Native](https://reactnative.dev/)，它可以让你为 Android、iOS，甚至 [Windows 和 macOS](https://microsoft.github.io/react-native-windows/) 构建应用程序。
```

2021-12-23 16:23 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +如果您好奇您日常使用的哪些产品是用 React 构建的，您可以安装 [React Developer Tools](/learn/react-developer-tools)。 每当您访问使用 React 构建的应用程序或网站时（就像这个文档网站！），它的图标会在工具栏中亮起。
```suggestion
如果你好奇你日常使用的哪些产品是用 React 构建的，你可以安装 [React Developer Tools](/learn/react-developer-tools)。 每当你访问使用 React 构建的应用程序或网站时（比如说这个文档！），它的图标就会在工具栏中亮起来。
```

2021-12-23 16:27 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +使用 React，您将在 JavaScript 中可视化地描述您的逻辑。这需要一些练习。如果您同时学习 JavaScript 和 React，很多人都这么干，但有时，它会更具挑战性！ 从好的方面来说，**大部分学习 React 都是在学习 JavaScript，** 这意味着您将学到的东西远远超出 React。
```suggestion
在 React 中，你会用 JavaScript 来可视化地描述你的逻辑。这需要一定的练习。如果你同时学习 JavaScript 和 React——很多人都这么干——但有时，它会更具挑战！不过还好，**大部分 React 的学习其实都是 JavaScript 的学习，** 也就是说你将学到远远超出 React 的内容。
```

2021-12-23 16:29 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +使用 [此 JavaScript 概述](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/A_re-introduction_to_JavaScript) 检查您的知识水平。这将花费您 30 分钟到一个小时，但您会更有信心学习 React。 [MDN](https://developer.mozilla.org/zh-CN/docs
```suggestion
使用 [此 JavaScript 概述](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/A_re-introduction_to_JavaScript) 检查你的知识水平。这将花费你 30 分钟到一个小时，但你会更有信心学习 React。 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript) 和 [javascript.info](https://zh.javascript.info/) 是两个很好的参考资源。
```

2021-12-23 16:32 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +如果您刚开始学习 React，您不需要安装任何东西。相反，我们建议您继续使用本网站中出现的 CodeSandbox。 它们看起来像这样：
```suggestion
如果你刚开始学习 React，你不需要安装任何东西。相反，我们建议你继续使用本网站中出现的 CodeSandbox。 它们看起来像这样：
```

2021-12-23 16:34 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +当您准备好开始一个项目时，有多种选择。您可以在线编写 React 代码并将您的代码保存在类似 [CodeSandbox](https://react.new/) 的环境中。您也可以将 React 作为 `<script>` 标签添加到任何 HTML 文件中，以便于在现有网页的一小部分中试用它。或者您可以创建一个全新的 React 应用程序，有或没有框架都行。**使用 [安装](/learn/in
```suggestion
当你准备好开始一个项目时，有多种选择。你可以在线编写 React 代码并将你的代码保存在类似 [CodeSandbox](https://react.new/) 的环境中。你也可以将 React 作为 `<script>` 标签添加到任何 HTML 文件中，以便于在现有网页的一小部分中试用它。或者你可以创建一个全新的 React 应用程序，有或没有框架都行。**请查阅 [安装](/learn/installation) 页面选择最适合你的方法——但现在你可以跳过它。**
```

2021-12-23 16:35 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +- 如果您**觉得迫不及待并通过例子学习**，直接前往 **[React 哲学](/learn/thinking-in-react)**。 该教程不会详细解释语法，但它会让您了解使用 React 构建用户界面的感受。
```suggestion
- 如果你**迫不及待并适合通过例子学习**，直接前往 **[React 哲学](/learn/thinking-in-react)**。该教程不会详细解释语法，但它会让你了解使用 React 构建用户界面的感受。
```

2021-12-23 16:36 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +- 如果您**熟悉这些概念并希望浏览可用的 API**，请查看 **[API 参考](/reference)**。
```suggestion
- 如果你 **熟悉这些概念并希望浏览可用的 API**，请查看 **[API 参考](/reference)**。
```

2021-12-23 16:41 UTC, KnowsCount requested changes
感谢你的贡献！很棒的翻译。不过有几个小问题需要修改一下：

1. 请修复行数不对应的错误。
2. 不要写 “您”，要写 “你”。
3. 符号标点请根据 [wiki](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-中文文档译文排版指南#符号标点) 修改
4. [空格问题](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-中文文档译文排版指南#空格问题) 也请注意

2021-12-23 16:41 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> -- The rest of this documentation is organized in chapters that **introduce each concept step by step**--with many interactive examples, detailed explanations, and challenges to check your understandi
这里行数有问题。

2021-12-23 16:41 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +上面例子中的标记看起来很像 HTML。 这种语法叫做 [JSX](/learn/writing-markup-with-jsx)，它更严格一些（例如，所有标签必须闭合）。请注意，CSS 类在 JSX 中指定为 `className`。
```suggestion
上面例子中的标记看起来很像 HTML。这种语法叫做 [JSX](/learn/writing-markup-with-jsx)，它更严格一些（例如，所有标签必须闭合）。请注意，CSS 类在 JSX 中指定为 `className`。
```

2021-12-23 16:41 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +就像你可以将一些信息传递给浏览器`<img>` 标签一样，你也可以将信息传递给你自己的组件，比如`<Profile>`。 此类信息称为 [_props_](/learn/passing-props-to-a-component)。 下面的例子中，三个 `<Profile>` 接收不同的 props：
```suggestion
就像你可以将一些信息传递给浏览器`<img>` 标签一样，你也可以将信息传递给你自己的组件，比如`<Profile>`。 此类信息称为 [_props_](/learn/passing-props-to-a-component)。下面的例子中，三个 `<Profile>` 接收不同的 props：
```

2021-12-24 02:11 UTC, x-cold commented on beta/src/pages/learn/index.md
> + - sooia
```suggestion
 - sooia
---
```

2021-12-24 02:12 UTC, x-cold commented on beta/src/pages/learn/index.md
> + - sooia
```suggestion
 - sooia
---
```

2021-12-24 02:13 UTC, x-cold commented on beta/src/pages/learn/index.md
```suggestion
---

```

2021-12-24 02:13 UTC, x-cold commented on beta/src/pages/learn/index.md
> +---
```suggestion
```

2021-12-24 02:14 UTC, x-cold commented on beta/src/pages/learn/index.md
> +---
```suggestion
```

2022-01-03 13:26 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +- 本文档的其余部分按章节组织，**逐步介绍每个概念**--带有许多交互式例子、详细说明和挑战以保证您的理解。 您不必按顺序阅读它们，但每个下一页都假设您熟悉前几页中的概念。
```suggestion
- 本文档的其余部分按章节组织，**逐步介绍每个概念** —— 带有许多交互式例子、详细说明和挑战以保证你的理解。 你不一定要按顺序阅读它们，但是每个主题都需要你熟悉前几页中的概念。
```

2022-01-03 13:26 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +为了节省您的时间，我们在下面提供**每章的简要概述**。
```suggestion
为了节省您的时间，我们在下面提供 **每章的简要概述**。 
```

2022-01-03 13:27 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +React 应用程序由被称为 ["components"](/learn/your-first-component) 的独立 UI 部分构建。 React 组件是一个 JavaScript 函数，您可以在其中添加标记。 组件可以小到一个按钮，也可以大到整个页面。下面的例子中，一个*父*组件 `Gallery` 渲染了三个*子*组件 `Profile` ：
```suggestion
React 应用程序由被称为 ["组件"](/learn/your-first-component) 的独立 UI 部分构建。 React 组件是一个 JavaScript 函数，您可以在其中添加标记。 组件可以小到一个按钮，也可以大到整个页面。下面的例子中，一个 *父* 组件 `Gallery` 渲染了三个 *子* 组件 `Profile` ：
```

其它地方都翻译了出来，这里不翻译有些奇怪吧。

2022-01-03 13:31 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +你可能想知道为什么 `className="avatar"` 使用引号，而 `src={imageUrl}` 使用花括号。在 JSX 中，花括号就像一个 ["进入 JavaScript 的窗口"](/learn/javascript-in-jsx-with-curly-braces)。 它们让您可以在标记中直接运行一些 JavaScript！所以 `src={imageUrl}` 读取第一行声明
```suggestion
你可能想知道为什么 `className="avatar"` 使用引号，而 `src={imageUrl}` 使用花括号。在 JSX 中，花括号就像一个 ["进入 JavaScript 的窗口"](/learn/javascript-in-jsx-with-curly-braces)。 它们让你可以在标记中直接运行一些 JavaScript！所以 `src={imageUrl}` 读取第一行声明的 `imageUrl` prop，并从父组件 `Gallery` 传递过来。
```

2022-01-03 13:33 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +在上面的例子中，所有的数据都是直接写在标记中的。但是，您通常希望将其单独保存。下面的例子，数据保存在一个数组中。在 React 中，你使用 JavaScript 函数，如 [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) 来[渲染列表](/lear
```suggestion
在上面的例子中，所有的数据都是直接写在标记中的。但是，很多情况下我们想将其分开存储。下面的例子，数据保存在一个数组中。在 React 中，一般使用例如 [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)  的 JavaScript 函数，来 [渲染一个列表](/learn/rendering-lists) 的东西。 
```

2022-01-03 13:34 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +阅读**[描述 UI](/learn/describing-the-ui)** 了解如何让东西出现在屏幕上，包括声明组件、导入它们、用大括号编写 JSX 以及编写条件和列表。
```suggestion
阅读 **[描述 UI](/learn/describing-the-ui)** 了解如何让东西出现在屏幕上，引用声明组件、导入它们、用大括号编写 JSX 以及编写条件和列表。
```

2022-01-03 13:35 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +您可以使用 [`useState`](/reference/usestate) Hook 向组件添加 state。 Hooks 是一种特殊的函数，可以让你的组件使用 React 特性（state 是这些特性之一）。`useState` Hook 允许你声明一个 state 变量。它接受初始 state 并返回一对值：当前 state 和一个允许您更新它的 state 设置器函数。
```suggestion
你可以使用 [`useState`](/reference/usestate) Hook 向组件添加 state。 Hooks 是一种特殊的函数，可以让你的组件使用 React 特性（state 是这些特性之一）。`useState` Hook 允许你声明一个 state 变量。它接受初始 state 并返回一对值：当前 state 以及一个允许你更新它的 state 设置器函数。
```

2022-01-03 13:36 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +State 也可以保存复杂的值。例如，如果您正在实现一个表单，您可以在 state 中保持一个具有不同字段的对象。 下面示例中的 `...` 语法允许您[基于现有对象创建新对象](/learn/updating-objects-in-state)。
```suggestion
State 也可以保存复杂的值。例如，如果你正在实现一个表单，你就可以在 state 中保持一个具有不同字段的对象。 下面示例中的 `...` 语法允许你 [基于现有对象创建新对象](/learn/updating-objects-in-state)。
```

2022-01-03 13:37 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +您还可以将数组保持在 state。 这允许您添加、删除或更改列表中的内容以响应用户交互。根据您想要做什么，这里有[从现有数组创建新数组的不同方法](/learn/updating-arrays-in-state)。
```suggestion
你还可以将数组保持在 state。 这允许你添加、删除或更改列表中的内容以响应用户交互。按照你的需求，有不同的 [从现有数组创建新数组的方法](/learn/updating-arrays-in-state)。
```

2022-01-03 13:37 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +阅读**[添加交互性](/learn/adding-interactivity)** 了解如何在交互时更新屏幕，包括添加事件处理程序、声明和更新 state，以及在 state 中更新对象和数组的不同方法。
```suggestion
阅读* *[添加交互性](/learn/adding-interactivity)** 了解如何在交互时更新屏幕，包括添加事件处理程序、声明和更新 state，以及在 state 中更新对象和数组的不同方法。
```

2022-01-03 13:38 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +您经常会面临选择_究竟要把什么_放进 state 的问题。 您应该使用一个 state 变量还是多个 state 变量？ 对象还是数组？ 你应该如何[构建你的 state](/learn/choosing-the-state-structure)？ 最重要的原则是**避免冗余 state**。 如果某些信息永远不会改变，它就不应该处于 state。 如果某些信息是通过 props 从父组件收到的
```suggestion
你经常会面临选择 _究竟要把什么_ 放进 state 的问题。 你应该使用一个 state 变量还是多个 state 变量？ 对象还是数组？ 你应该如何 [构建你的 state](/learn/choosing-the-state-structure)？ 最重要的原则是 **避免冗余 state**。 如果某些信息永远不会改变，它就不应该处于 state。 如果某些信息是通过 props 从父组件收到的，它不应该处于 state 中。 如果某些信息可以从其他 props 或 state 计算得出，它也不应该处于 state 中！
```

2022-01-03 13:39 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +您可以通过在组件渲染时计算 `fullName` 来删除它并简化代码：
```suggestion
你可以通过在组件渲染时计算 `fullName` 来删除它并简化代码：
```

2022-01-03 13:39 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +有时，您希望两个组件的 state 始终一起更改。要做到这一点，在它们两个中都删除该 state，将它移动到它们最近的公共父节点，然后通过 props 将它传递给它们。 这被称为["提升 state"](/learn/sharing-state-between-components)，这是编写 React 代码时最常见的事情之一。 例如，在像下面这样的手风琴组件中，一次应该只有一个面板处于激活状
```suggestion
你有的时候可能需要两个组件的 state 同时更改。要做到这一点，在它们两个中都删除该 state，将它移动到它们最近的公共父节点，然后通过 props 将它传递给它们。 这被称为 ["提升 state"](/learn/sharing-state-between-components)，这是编写 React 代码时最常见的事情之一。 例如，在像下面这样的手风琴组件中，一次应该只有一个面板处于激活状态。父组件不应该将激活 state 保存在每个单独的面板内，而是保存在父组件的 state 中并通过 props 指定给子组件。
```

2022-01-03 13:40 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +您接下来的步骤取决于您想做什么：
```suggestion
接下来的步骤取决于你：
```

2022-01-03 13:41 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +这个页面是快节奏的！如果读到这里，您已经看到了日常使用 React 的 80%。
```suggestion
这一章节奏很快！如果已经读到这里，你就已经读了 React 80% 的日常使用内容。
```

2022-01-03 13:41 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +当您需要了解 API 必要的细节时，不要忘记阅读 [API 参考](/reference)！
```suggestion
当你需要了解 API 必要的细节时，不要忘记阅读 [API 参考](/reference)！
```

2022-01-03 13:41 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +* 如果您想了解在 React 中构建 UI 在实践中是什么感觉，请阅读 [React 哲学](/learn/thinking-in-react)。
```suggestion
* 如果你想了解在 React 中构建 UI 在实践中是什么感觉，请阅读 [React 哲学](/learn/thinking-in-react)。
```

2022-01-03 13:42 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +* 如果您想在本地创建一个 React 项目，请转到 [安装](/learn/installation)。
```suggestion
* 如果你想在本地创建一个 React 项目，请转到 [安装](/learn/installation)。
```

2022-01-22 06:25 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> + - sooia
```suggestion
 - sooia
 - KnowsCount
```

2022-01-28 06:14 UTC, Bin9o commented on beta/src/pages/learn/index.md
> + - sooia
```suggestion
 - Bin9o
```
我修改了用户名，能否麻烦@x-cold 修改一下，非常抱歉。

2022-03-24 00:04 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +  description: 'The Terracotta Army is a collection of terracotta sculptures depicting the armies of Qin Shi Huang, the first Emperor of China. The army consited of more than 8,000 soldiers, 130 char
```suggestion
  description: 'The Terracotta Army is a collection of terracotta sculptures depicting the armies of Qin Shi Huang, the first Emperor of China. The army consisted of more than 8,000 soldiers, 130 chariots with 520 horses, and 150 cavalry horses.',
```

2022-03-24 00:06 UTC, KnowsCount commented on beta/src/pages/learn/index.md
> +        这个名字源自 <span lang="kk-KZ">алма</span>，哈萨克语中的“苹果”一词，通常被翻译为“苹果之城”。 事实上，阿拉木图周边地区被认为是苹果的祖先家园，而野生<i lang="la">Malus Siversii (天山野苹果)</i> 可能是现代家养苹果祖先。
```suggestion
        这个名字源自 <span lang="kk-KZ">алма</span>，哈萨克语中的“苹果”一词，通常被翻译为“苹果之城”。事实上，阿拉木图周边地区被认为是苹果的祖先家园，而野生<i lang="la">Malus Siversii (天山野苹果)</i> 可能是现代家养苹果祖先。
```

2022-03-24 00:08 UTC, KnowsCount commented
@x-cold 我最后看了一遍，应该只有我刚刚提的两个问题了。感谢！
如果你能把 conflicts 给 resolve 掉应该就可以合并了。

2022-05-26 16:00 UTC, merged