docs: translate useTransition and useDeferredValue
reactjs/zh-hans.reactjs.org pull request #772
Opened 2022-04-01 05:10 UTC by ManfredHu

2023-02-14 05:54 UTC, awxiaoxian2020 requested changes

2023-02-14 05:54 UTC, awxiaoxian2020 commented on content/docs/hooks-reference.md
> +`useDeferredValue` 接收一个值并返回接收值的拷贝副本，该副本将推迟到更紧急的更新。如果当前呈现是紧急更新的结果(如用户输入)，那么React将返回先前的值，然后在紧急呈现完成后呈现新值。
```suggestion
`useDeferredValue` 接收一个值并返回接收值的拷贝副本，该副本将推迟到更紧急的更新。如果当前呈现是紧急更新的结果（如用户输入），那么 React 将返回先前的值，然后在紧急呈现完成后呈现新值。
```

2023-02-14 05:54 UTC, awxiaoxian2020 commented on content/docs/hooks-reference.md
> +`useDeferredValue` 只会推迟您传递给它的值。如果要防止子组件在紧急更新期间重新呈现，还必须使用 memoize 的组件比如  [`React.memo`](/docs/react-api.html#reactmemo) 或者 [`React.useMemo`](/docs/hooks-reference.html#usememo):
```suggestion
`useDeferredValue` 只会推迟传递给它的值。如果要防止子组件在紧急更新期间重新呈现，还必须使用 memoize 的组件比如  [`React.memo`](/docs/react-api.html#reactmemo) 或者 [`React.useMemo`](/docs/hooks-reference.html#usememo):
```

2023-02-14 05:54 UTC, awxiaoxian2020 commented on content/docs/hooks-reference.md
> +返回判断pending的状态值，并返回启动转换的函数。
```suggestion
返回判断 pending 的状态值，并返回启动转换的函数。
```

2023-02-14 15:16 UTC, daochouwangu submitted a review, later dismissed

2023-02-23 15:04 UTC, awxiaoxian2020 commented
@ManfredHu Could you please fix the conflicts?

2023-03-01 11:33 UTC, awxiaoxian2020 approved these changes

2023-03-01 12:21 UTC, daochouwangu approved these changes

2023-03-01 12:45 UTC, merged