docs(cn): translate reference-react-dom-server
reactjs/zh-hans.reactjs.org pull request #774
Opened 2022-04-02 14:10 UTC by fanhuirong

2022-05-30 05:48 UTC, awxiaoxian2020 requested changes

2022-05-30 05:48 UTC, awxiaoxian2020 commented on content/docs/reference-react-dom-server.md
> +将 React 元素渲染成初始 HTML。React 将返回一个 [Control object](https://github.com/facebook/react/blob/3f8990898309c61c817fbf663f5221d9a00d0eaa/packages/react-dom/src/server/ReactDOMFizzServerNode.js#L49-L54)，这个对象
“…… javascript 执行来……”建议改为“……执行 javascript “

2022-06-02 08:19 UTC, awxiaoxian2020 requested changes

2022-06-02 08:19 UTC, awxiaoxian2020 commented on content/docs/reference-react-dom-server.md
> +将 React 元素渲染成初始 HTML。React 将返回一个 [Control object](https://github.com/facebook/react/blob/3f8990898309c61c817fbf663f5221d9a00d0eaa/packages/react-dom/src/server/ReactDOMFizzServerNode.js#L49-L54)，这个对象
```suggestion
将 React 元素渲染成初始 HTML。React 将返回一个 [Control object](https://github.com/facebook/react/blob/3f8990898309c61c817fbf663f5221d9a00d0eaa/packages/react-dom/src/server/ReactDOMFizzServerNode.js#L49-L54)，这个对象允许我们对输出进行管理或中止请求。同时完全支持 Suspense 和 HTML 的流式传输，随后通过执行 javascript 来“延迟”内容块的“弹出”。[了解更多](https://github.com/reactwg/react-18/discussions/37)。
```

2022-06-02 08:22 UTC, awxiaoxian2020 commented on content/docs/reference-react-dom-server.md
> +如果你在已有服务端渲染标记的节点上调用 [`ReactDOM.hydrateRoot()`](/docs/react-dom-client.html#hydrateroot) 方法，React 将会保留该节点且只进行事件处理绑定，从而让你有一个非常高性能的首次加载体验。
这个地方翻译成“高性能”去修饰“体验”是否合适，虽然我目前也没有想到更好的翻译。

2022-07-10 02:45 UTC, KnowsCount commented on content/docs/reference-react-dom-server.md
> +如果你在已有服务端渲染标记的节点上调用 [`ReactDOM.hydrateRoot()`](/docs/react-dom-client.html#hydrateroot) 方法，React 将会保留该节点且只进行事件处理绑定，从而让你有一个非常高性能的首次加载体验。
> 这个地方翻译成“高性能”去修饰“体验”是否合适，虽然我目前也没有想到更好的翻译。

我懂你说的意思，但是原文就是这么翻译的，我认为问题不大，能表达这个意思的。

2022-07-10 02:48 UTC, KnowsCount approved these changes

2023-02-14 05:31 UTC, awxiaoxian2020 approved these changes

2023-02-14 05:43 UTC, awxiaoxian2020 commented
#836 close this pull request.

2023-02-14 05:43 UTC, closed without merging