docs(cn): polish content/blog/2022-06-15-react-labs-what-we-have-been…
reactjs/zh-hans.reactjs.org pull request #875
Opened 2022-07-22 06:25 UTC by Huxpro

2022-07-22 06:39 UTC, awxiaoxian2020 requested changes

2022-07-22 06:39 UTC, awxiaoxian2020 commented on content/blog/2022-06-15-react-labs-what-we-have-been-working-on-june-2022.md
> +我们通常在任何时候都有许多同时进行的项目，有更具实验性得，也有一些更加明确得。以后，我们将会定期与社区分享我们在进行的这些项目。
```suggestion
我们通常在任何时候都有许多同时进行的项目，有更具实验性的，也有一些更加明确的。以后，我们将会定期与社区分享我们在进行的这些项目。
```

2022-07-22 06:39 UTC, awxiaoxian2020 commented on content/blog/2022-06-15-react-labs-what-we-have-been-working-on-june-2022.md
> +值得一提得是，我们放弃了必须使用 react-fetch 这样专用 I/O 库的路线，而是决定采用一个兼容 async/await 的路线。严格得说，这个改动并不会阻碍 RSC 的发布，目前你仍然可以继续用路由（routers）来获取数据。另一个变化是我们已经决定不用文件扩展名这种方式，而是转而考虑使用 [标注来确定边界（annotating boundaries）](https://githu
```suggestion
值得一提得是，我们放弃了必须使用 react-fetch 这样专用 I/O 库的路线，而是决定采用一个兼容 async/await 的路线。严格地说，这个改动并不会阻碍 RSC 的发布，目前你仍然可以继续用路由（routers）来获取数据。另一个变化是我们已经决定不用文件扩展名这种方式，而是转而考虑使用 [标注来确定边界（annotating boundaries）](https://github.com/reactjs/rfcs/pull/189#issuecomment-1116482278)。
```

2022-07-22 10:11 UTC, awxiaoxian2020 approved these changes

2022-07-23 12:18 UTC, KnowsCount approved these changes

2022-07-24 12:06 UTC, merged