docs(cn): translate content/blog/2022-03-08-react-18-upgrade-guide.md
reactjs/zh-hans.reactjs.org pull request #894
Opened 2022-08-18 13:30 UTC by jsbugwang

How to Upgrade to React 18 翻译完成。

2023-02-15 14:33 UTC, daochouwangu requested changes

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +查看 [React 18 typings pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210) 获得只含类型更改（type-only changes）的完整清单。它链到库类型的修复例子（It links to example fixes in library types），你就知道如何调整自己的代
```suggestion
查看 [React 18 typings pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210) 获得只含类型更改的完整清单。它链到库类型的修复例子，你就知道如何调整自己的代码。 你可以使用 [自动迁移脚本](https://github.com/eps1lon/types-react-codemod) 来加速帮你把应用代码迁移到更安全的新类型。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +## 自动化批处理（Automatic Batching） {#automatic-batching}
```suggestion
## 自动化批处理 {#automatic-batching}
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +React 18 通过更多默认批处理提供了开箱即用的性能优化。批处理是指 React 把多个状态更新组合为一次重渲染（re-render）从而获得更好性能。React 18 之前，我们仅把 React event handler 的更新做批处理。Promise、setTimeout、native event handler，或者其他事件中的更新，React 默认不进行批处理：
```suggestion
React 18 通过更多默认批处理提供了开箱即用的性能优化。批处理是指 React 把多个状态更新组合为一次重渲染从而获得更好性能。React 18 之前，我们仅把 React event handler 的更新做批处理。Promise、setTimeout、native event handler，或者其他事件中的更新，React 默认不进行批处理：
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +阅读 [深入自动批处理](https://github.com/reactwg/react-18/discussions/21) 获取更多信息。
```suggestion
阅读[深入自动批处理](https://github.com/reactwg/react-18/discussions/21) 获取更多信息。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +## 为库提供的新 API （New APIs for Libraries） {#new-apis-for-libraries}
```suggestion
## 为库提供的新 API  {#new-apis-for-libraries}
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +React 18 工作组和库维护者合作，为他们的特定 use case ，例如样式和外部 store（like styles, and external stores），创建了支持并发渲染的新 API。为了支持 React 18，有些库可能需要切换到以下 API 中的一个：
```suggestion
React 18 工作组和库维护者合作，为他们的特定 use case ，例如样式和外部 store ，创建了支持并发渲染的新 API 。为了支持 React 18，有些库可能需要切换到以下 API 中的一个：
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* `useSyncExternalStore` 是一个新的 hook ，通过强制把 store 的更新设置为同步，允许外部 store 支持并发读（concurrent reads）。推荐所有集成了 React 外部状态的库使用这个新 API 。 更多信息请阅读 [useSyncExternalStore overview post](https://github.com/reactwg/re
```suggestion
* `useSyncExternalStore` 是一个新的 hook ，通过强制把 store 的更新设置为同步，允许外部 store 支持并发读。推荐所有集成了 React 外部状态的库使用这个新 API 。更多信息请阅读 [useSyncExternalStore 综述帖子](https://github.com/reactwg/react-18/discussions/70) 和 [useSyncExternalStore API 细节](https://github.com/reactwg/react-18/discussions/86)。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* `useInsertionEffect` 是一个新的 hook ，允许 CSS-in-JS 库定位渲染时注入的样式的性能问题。除非你已构建了 CSS-in-JS 库，否则不要用这个 hook 。这个 hook 会在 DOM 可交互后运行，但是在布局 effect 读到新的布局前。这解决了 React 17 及以下版本已存在的一个问题，不过对于 React 18 更重要，因为 React 在并
```suggestion
* `useInsertionEffect` 是一个新的 hook ，允许 CSS-in-JS 库定位渲染时注入的样式的性能问题。除非你已构建了 CSS-in-JS 库，否则不要用这个 hook 。这个 hook 会在 DOM 可交互后运行，但是在布局 effect 读到新的布局前。这解决了 React 17 及以下版本已存在的一个问题，不过对于 React 18 更重要，因为 React 在并发渲染期间会把控制权交给浏览器，让浏览器有机会重新计算布局。阅读 [`<style>` 的库升级指南](https://github.com/reactwg/react-18/discussions/110) 获取更多信息。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +React 18 还引入了 `startTransition`、`useDeferredValue` 和 `useId` 等并发渲染的新 API，在 [release post](/blog/2022/03/29/react-v18.html) 中我们有更详细介绍。
```suggestion
React 18 还引入了 `startTransition`、`useDeferredValue` 和 `useId` 等并发渲染的新 API，在 [发布公告](/blog/2022/03/29/react-v18.html) 中我们有更详细介绍。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +为了让这些问题暴露，React 18 给严格模式引入了新的仅开发模式检查（development-only check）。这项新检查会自动对每个组件卸载和重挂载，第二次 mount 的时候恢复之前的状态。
```suggestion
为了让这些问题暴露，React 18 给严格模式引入了新的仅开发模式检查。这项新检查会自动对每个组件卸载和重挂载，第二次挂载的时候恢复之前的状态。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +这次更改前，React 按如下方式 mount 组件和创建 effect ：
```suggestion
这次更改前，React 按如下方式挂载组件和创建 effect ：
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* React mount 组件。
```suggestion
* React 挂载组件。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* React mounts 组件。
```suggestion
* React 挂载组件。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* React 模拟用之前的状态 mount 组件。
```suggestion
* React 模拟用之前的状态挂载组件。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +请阅读工作组关于 [Adding Reusable State to StrictMode](https://github.com/reactwg/react-18/discussions/19) 和 [How to support Reusable State in Effects](https://github.com/reactwg/react-18/discussions/18) 的文章
```suggestion
请阅读工作组关于 [在严格模式下添加可重用状态](https://github.com/reactwg/react-18/discussions/19) 和 [如何在 Effect 中支持可重用的状态](https://github.com/reactwg/react-18/discussions/18) 的文章获取更多信息。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +> 当前测试环境未配置为支持 act(...)
```suggestion
> The current testing environment is not configured to support act(...)
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +> 当前测试环境未配置为支持 act(...)
这里是控制台错误，是不是不翻译比较好

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +此标识的目的是告诉 React 运行在类似单元测试的环境下（unit test-like environment）。如果你忘记用 `act` 包裹更新，React 会记录有用的警告。
```suggestion
此标识的目的是告诉 React 运行在类似单元测试的环境下。如果你忘记用 `act` 包裹更新，React 会记录有用的警告。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +最后，我们期望测试库帮你自动配置。例如 [next version of React Testing Library has built-in support for React 18](https://github.com/testing-library/react-testing-library/issues/509#issuecomment-917989936) 不需要任何额外配置。
```suggestion
最后，我们期望测试库帮你自动配置。例如 [下一版本的 React 测试库已内置对 React 18 的支持](https://github.com/testing-library/react-testing-library/issues/509#issuecomment-917989936) 不需要任何额外配置。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +从这个版本起，React 放弃了对 IE 的支持，IE[从2022-06-15不再支持](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge)了。我们现在做出这个改变，是因为 React 18 引入的新特性
```suggestion
从这个版本起，React 放弃了对 IE 的支持，IE [从2022-06-15不再支持](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge)了。我们现在做出这个改变，是因为 React 18 引入的新特性是基于现代浏览器的新特性，比如微任务，而这些在 IE 不能很好的用 polyfill 支持。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +## 废弃（Deprecations） {#deprecations}
```suggestion
## 废弃 {#deprecations}
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +## 其他破坏性更改（Other Breaking Changes） {#other-breaking-changes}
```suggestion
## 其他破坏性更改 {#other-breaking-changes}
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **一致的 useEffect 时序（Consistent useEffect timing）**: 如果更新是由独立的用户输入事件，如 click 或 keydown 事件，则 React 现在总是同步刷新 （flush）effect 函数。而以前行为并非总是可预测的和一致的。
```suggestion
* **一致的 useEffect 时序**: 如果更新是由独立的用户输入事件，如 click 或 keydown 事件，则 React 现在总是同步刷新 effect 函数。而以前行为并非总是可预测的和一致的。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **更严格的 hydration 错误（Stricter hydration errors）**: 由于缺失的或额外的文本内容现在被当做错误而非警告，因此 Hydration 匹配不上了。React 不再尝试在客户端插入或删除节点对单独节点进行 "patch up" ，以匹配服务端的内容，而是回退到客户端，渲染组件树最近的 `<Suspense>` 边界。这样保证 hydrate 后树的一致
```suggestion
* **更严格的 hydration 错误**: 由于缺失的或额外的文本内容现在被当做错误而非警告，因此 hydration 匹配不上了。React 不再尝试在客户端插入或删除节点对单独节点进行 "patch up" ，以匹配服务端的内容，而是回退到客户端，渲染组件树最近的 `<Suspense>` 边界。这样保证 hydrate 后树的一致性，避免潜在的由 hydration 不匹配导致的隐私和安全漏洞 。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **Suspense 树总是一致的：** 如果一个组件在完全添加到组件树前挂起了，React 会以不完整状态将其添加到组件树，或者触发其副作用。React 会完全抛弃新的树，等待异步操作完成，然后尝试从头开始渲染（retry rendering again from scratch）。React 用并发渲染进行重试，并且不阻塞浏览器。
```suggestion
* **Suspense 树总是一致的：** 如果一个组件在完全添加到组件树前挂起了，React 会以不完整状态将其添加到组件树，或者触发其副作用。React 会完全抛弃新的树，等待异步操作完成，然后尝试从头开始渲染。React 用并发渲染进行重试，并且不阻塞浏览器。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **Layout Effects with Suspense**: 当组件树重新挂起（re-suspend）并回退到兜底时（reverts to a fallback），React 会清理布局 effect，然后当边界内的内容重新显示时，重新创建它们。这解决了一个问题，这个问题会阻止组件库在使用 Suspense 时正确测量布局（measuring layout）。
```suggestion
* **Layout Effects with Suspense** : 当组件树重新挂起并回退到兜底时，React 会清理布局 effect ，然后当边界内的内容重新显示时，重新创建它们。这解决了一个问题，这个问题会阻止组件库在使用 Suspense 时正确测量布局。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +## 其他重要更改（Other Notable Changes） {#other-notable-changes}
```suggestion
## 其他重要更改 {#other-notable-changes}
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **组件现在可以渲染 `undefined`:** 如果组件返回 `undefined`，React 不再警告。这样组件的返回值与组件树中间允许的值（values that are allowed in the middle of a component tree）保持一致。我们建议使用 linter 来避免在 JSX 之前忘记 `return` 语句的错误。
```suggestion
* **组件现在可以渲染 `undefined`:** 如果组件返回 `undefined`，React 不再警告。这样组件的返回值与组件树中间允许的值保持一致。我们建议使用 linter 来避免在 JSX 之前忘记 `return` 语句的错误。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **未挂载组件 `setState` 不再有警告:** 以前, 当你在未挂载组件调用 `setState` 时，React 警告内存泄露。该警告是为了订阅添加的，然后人们遇到这种情况时，大部分时候都是正常情况，而解决方法（workaround）让代码更糟糕。 我们已[删除](https://github.com/facebook/react/pull/22114)这个警告。
```suggestion
* **未挂载组件 `setState` 不再有警告:** 以前, 当你在未挂载组件调用 `setState` 时，React 警告内存泄露。该警告是为了订阅添加的，然后人们遇到这种情况时，大部分时候都是正常情况，而解决方法让代码更糟糕。 我们已[删除](https://github.com/facebook/react/pull/22114)这个警告。
```

2023-02-15 14:33 UTC, daochouwangu commented on content/blog/2022-03-08-react-18-upgrade-guide.md
> +* **不抑制控制台日志（No suppression of console logs）：** 严格模式下, React 每个组件渲染2次，帮你发现意外的副作用。在 React 17 中我们抑制（suppress）了其中一次渲染的控制台日志，让日志更易读。根据[社区反馈](https://github.com/facebook/react/issues/21783)，这个功能让人困惑，我们已删除
```suggestion
* **不抑制控制台日志：** 严格模式下, React 每个组件渲染2次，帮你发现意外的副作用。在 React 17 中我们抑制了其中一次渲染的控制台日志，让日志更易读。根据[社区反馈](https://github.com/facebook/react/issues/21783)，这个功能让人困惑，我们已删除了这个功能。现在如果你安装了 React DevTools，第二条日志显示成灰色的，同时提供一个选项（默认不开启）彻底抑制日志。 
```

2023-02-25 01:12 UTC, awxiaoxian2020 commented
@jsbugwang Could you please handle with reviews?

2023-03-07 02:20 UTC, jsbugwang commented
> 

suggestion resolved

2023-03-08 15:02 UTC, daochouwangu requested changes

2023-03-09 00:56 UTC, daochouwangu approved these changes

2023-03-09 02:02 UTC, awxiaoxian2020 approved these changes

2023-03-09 02:03 UTC, merged