翻译ReactDOMClient文章
reactjs/zh-hans.reactjs.org pull request #900
Opened 2022-08-24 14:05 UTC by hexiaokang

2022-08-25 00:30 UTC, hexiaokang commented
This is my first PR, I like React, I hope i can make contribute to open source.

2023-02-23 14:33 UTC, daochouwangu requested changes

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +如果你使用 ES5 和 npm，你可以这样写:
```suggestion
如果你使用 ES5 和 npm ，你可以这样写：
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +下面的方法可以在客户端环境使用:
```suggestion
下面的方法可以在客户端环境使用：
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +React 支持所有现代浏览器，但是对于老版本浏览器需要引入 [相关polyfills依赖](/docs/javascript-environment-requirements.html)。
```suggestion
React 支持所有现代浏览器，但是对于老版本浏览器需要引入[相关 polyfill 依赖](/docs/javascript-environment-requirements.html)。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +> 我们不支持那些不兼容 ES5 方法或者微任务的旧版浏览器，比如 Internet Explorer，但如果你的应用包含了 polyfills，例如 [es5-shim 和 es5-sham](https://github.com/es-shims/es5-shim) 你可能会发现你的应用仍然可以在这些浏览器中正常运行。但是如果你选择这种方法，你便需要孤军奋战了。
```suggestion
> 我们不支持那些不兼容 ES5 方法或者微任务的旧版浏览器，比如 Internet Explorer ，但如果你的应用包含了 polyfill ，例如 [es5-shim 和 es5-sham](https://github.com/es-shims/es5-shim) 你可能会发现你的应用仍然可以在这些浏览器中正常运行。但是如果你选择这种方法，你便需要孤军奋战了。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +为输入的 `container` 容器创建一个 React 根节点，并且返回根节点。根节点可以用 `render` 方法来渲染一个 React 元素至 DOM 中:
```suggestion
为输入的 `container` 容器创建一个 React 根节点，并且返回根节点。根节点可以用 `render` 方法来渲染一个 React 元素至 DOM 中：
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +`createRoot` 接收两个可选项:
```suggestion
`createRoot` 接收两个可选项：
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +- `onRecoverableError`: 这是一个可选的回调函数，当 React 从渲染错误中恢复时就会调用。
```suggestion
- `onRecoverableError`：这是一个可选的回调函数，当 React 从渲染错误中恢复时就会调用。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +- `identifierPrefix`: 可选的前缀，主要用于为通过 `React.useId` 钩子生成的id值添加前缀，有效的避免了当一个页面有多个根节点时的冲突，必须与服务器上的前缀相同。
```suggestion
- `identifierPrefix`：可选的前缀，主要用于为通过 `React.useId` 生成的 id 值添加前缀，有效的避免了当一个页面有多个根节点时的冲突，必须与服务器上的前缀相同。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +> `createRoot()` 控制着你传入的容器节点内容，当调用 render 函数时容器内的所有已存 DOM 元素都会被替换掉。之后的调用会通过 React 的 diffing 算法高效更新。
```suggestion
> `createRoot()` 控制着你传入的容器节点内容。当调用 render 函数时容器内的所有 DOM 元素都会被替换掉。之后再调用会通过 React 的 diffing 算法高效更新。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +> 不能用 `createRoot()` 去hydrate(可以理解为创建)一个服务端渲染容器，应该用 [`hydrateRoot()`](#hydrateroot) 替代。
```suggestion
> 不能用 `createRoot()` 去 hydrate 一个服务端渲染容器，应该用 [`hydrateRoot()`](#hydrateroot) 替代。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +与 [`createRoot()`](#createroot) 一样，但是 hydrateRoot 是用来 hydrate 一个HTML内容由 [`ReactDOMServer`](/docs/react-dom-server.html) 渲染的容器，React 会尝试在已有标记上绑定事件监听器。
```suggestion
与 [`createRoot()`](#createroot) 一样，但是 hydrateRoot 是用来 hydrate 一个 HTML 内容由 [`ReactDOMServer`](/docs/react-dom-server.html) 渲染的容器，React 会尝试在已有标签上绑定事件监听器。
```

2023-02-23 14:33 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +> React 希望服务端与客户端渲染的内容完全一致。React 可以弥补文本内容的差异，但是你需要将不匹配的地方作为 bug 进行修复。在开发者模式下，React 会对 hydration 操作过程中的不匹配进行警告。但并不能保证在不匹配的情况下，修补属性的差异。由于性能的因素，这一点非常重要，因为大多数应用中不匹配的情况很少见，并且验证所有标记的成本非常昂贵。
```suggestion
> React 希望服务端与客户端渲染的内容完全一致。React 可以弥补文本内容的差异，但是你需要将不匹配的地方作为 bug 进行修复。在开发者模式下，React 会对 hydration 操作过程中的不匹配进行警告。但并不能保证在不匹配的情况下，修补属性的差异。由于性能的因素，这一点非常重要，因为大多数应用中不匹配的情况很少见，并且验证所有标签的成本非常昂贵。
```

2023-02-23 14:36 UTC, awxiaoxian2020 commented on content/docs/reference-react-dom-client.md
> +如果你使用 ES5 和 npm，你可以这样写:
npm 处的空格都不需要加，我已经更新了 wiki，你可以看一下~@daochouwangu

2023-02-23 15:00 UTC, daochouwangu commented on content/docs/reference-react-dom-client.md
> +如果你使用 ES5 和 npm，你可以这样写:
好的👌

2023-03-20 06:49 UTC, awxiaoxian2020 commented
新版文档已经发布，将关闭这个 Pull Request

2023-03-20 06:49 UTC, closed without merging