修改ReactDOM细节翻译
reactjs/zh-hans.reactjs.org pull request #901
Opened 2022-08-25 01:23 UTC by hexiaokang

2022-08-25 01:35 UTC, hexiaokang commented
1、第43行
原英文：React supports all modern browsers, although some polyfills are required for older versions.
原翻译：React 支持所有的现代浏览器，尽管对于旧版本来说，可能需要引入 相关的 polyfills 依赖。
修改意见：此处的语境应该是转折，个人建议although翻译成‘不过’会更通顺些。

2、第47行的polyfill少了s

3、第65行的‘立即 更新’中间没必要有空格

4、第127行
原英文：because in most apps, mismatches are rare
原翻译：因为大多是应用中不匹配的情况很少见
修改意见：此处翻译为‘大多数’更符合语义

2023-02-14 07:34 UTC, awxiaoxian2020 requested changes

2023-02-14 07:34 UTC, awxiaoxian2020 commented on content/docs/reference-react-dom.md
> +>我们不支持那些不兼容 ES5 方法的旧版浏览器，但如果你的应用包含了 polyfills，例如 [es5-shim 和 es5-sham](https://github.com/es-shims/es5-shim) 你可能会发现你的应用仍然可以在这些浏览器中正常运行。但是如果你选择这种方法，你便需要孤军奋战了。
```suggestion
>我们不支持那些不兼容 ES5 方法的旧版浏览器，但如果你的应用包含了 polyfill，例如 [es5-shim 和 es5-sham](https://github.com/es-shims/es5-shim) 你可能会发现你的应用仍然可以在这些浏览器中正常运行。但是如果你选择这种方法，你便需要孤军奋战了。
```
参见 https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97#%E8%8B%B1%E6%96%87

2023-02-14 14:45 UTC, awxiaoxian2020 approved these changes

2023-02-14 15:15 UTC, daochouwangu approved these changes

2023-02-15 02:51 UTC, merged