docs(cn): translate content/blog/2015-04-17-react-native-v0.4.md into Chinese
reactjs/zh-hans.reactjs.org pull request #925
Opened 2022-09-16 08:27 UTC by hexiaokang

… Chinese

2023-02-21 01:19 UTC, daochouwangu requested changes

2023-02-21 01:19 UTC, daochouwangu commented on content/blog/2015-04-17-react-native-v0.4.md
> +自从我们开源 React Native 到现在有三周了，已经有一些令人激动的的活跃度：超过 12.5k stars，1000 commits，500 issues，380 pull requests和 100 contributors，另外app store中有[35 plugins](http://react.parts/native-ios) 和[1个app](http://herman.a
```suggestion
自从我们开源 React Native 到现在有三周了，已经有一些令人激动的的活跃度：超过 12.5k stars，1000 commits，500 issues，380 pull requests和 100 contributors，另外app store中有[ 35 plugins](http://react.parts/native-ios) 和[ 1 个app](http://herman.asia/building-a-flashcard-app-with-react-native) ！我们期待这个项目会引起轰动，但这远远超出了我们的想象。感谢！
```

2023-02-21 01:19 UTC, daochouwangu commented on content/blog/2015-04-17-react-native-v0.4.md
> +过去几周的主要关注点是让 React Native 成为 Facebook 以外开发者的最佳体验。以下是自我们开源以来所做事情的重点概括：
```suggestion
过去几周的工作重点是尽可能提高 React Native 在 Facebook 以外开发者的体验。以下是自我们开源以来所做事情的重点概括：
```

2023-02-21 01:19 UTC, daochouwangu commented on content/blog/2015-04-17-react-native-v0.4.md
> +* **专利授权**: 你们中的许多人对专利文件有疑虑和问题。 我们推送了 [一个新版本的授权](https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/) 。
```suggestion
* **专利授权**: 你们中的许多人对专利文件有疑虑和问题。 我们推送了[一个新版本的授权协议](https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/) 。
```

2023-02-25 01:09 UTC, awxiaoxian2020 commented
@hexiaokang Could you please handle with the reviews?

2023-03-20 06:48 UTC, awxiaoxian2020 commented
新版文档似乎已经不再包含这篇博客，所以我暂时将会关闭它

2023-03-20 06:48 UTC, closed without merging