doc(cn): tranlate /content/blog/2016-07-13-mixins-considered-harmful.md into Chinese
reactjs/zh-hans.reactjs.org pull request #957
Opened 2022-10-23 03:57 UTC by favorhau

doc(cn): tranlate /content/blog/2016-07-13-mixins-considered-harmful.md into Chinese

2022-10-24 13:57 UTC, hexiaokang commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +这并不意味着 mixins 本身是坏的。人们成功地在不同的语言和范例中使用它，包括一些函数式语言。在 Facebook ，我们广泛地在 Hack 语言中使用与 mixins 非常相似的特征。尽管如此，我们仍然认为在 React 代码库中，mixins 是不必要的和容易出问题的。这里列出来为什么这样说的几条理由。
个人建议，将“列出来”改为“列出了”，语气更合理些。

2022-10-24 13:57 UTC, hexiaokang commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +Mixins 打破了常见的，通常是安全的假设 —— 你可以通过搜索 state 在组件文件中的出现位置来重命名它的键名或方法。你可能会写一个有状态的组件，然后你的同事可能添加一个读取这个组件 state 的 mixin。几个月之后，你可能希望将该 state 移动到父组件，以便与其兄弟组件共享。你会记得更新这个 mixin 来读取 props 而不是 state 吗？如果此时，其他组件也在使用这
Mixins 打破了常规

2022-10-24 13:57 UTC, hexiaokang commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +让我们清楚的是，mixins 在技术上不被淘汰。如果你使用 `React.createClass()`，可以继续使用它们。我们只是说它对我们没有好处，所以我们不建议使用它们
末尾缺少句号。

2022-10-24 13:57 UTC, hexiaokang commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +让我们清楚的是，mixins 在技术上不被淘汰。如果你使用 `React.createClass()`，可以继续使用它们。我们只是说它对我们没有好处，所以我们不建议使用它们
没有翻译in the future

2022-12-26 08:43 UTC, durgasatti submitted a review, later dismissed

2023-02-18 00:45 UTC, awxiaoxian2020 commented
Hi, @favorhau could you please fix the conflicts?

2023-02-22 02:37 UTC, daochouwangu requested changes

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +下面的每个部分对应于我们在 Facebook 代码库中找到的 mixin 使用模式。对于它们中的每个，我们描述它们问题和我们认为比 mixins 更好的解决方案。这些例子是在ES5中编写的，但是一旦你不需要 mixin，你可以根据需要切换到 ES6 的类语法。
```suggestion
下面是我们在 Facebook 代码库中找到的一些典型 mixin 和它们解决的问题以及我们认为比 mixins 更好的解决方案。这些例子是在ES5中编写的，但是一旦你不需要 mixin，你可以根据需要切换到 ES6 的类语法。
```
虽然原文是 `usage pattern` 但是阅读下文发现都是具体的 mixin ，故这么翻译。
> we describe the problem

直译是我们描述了问题，但是下面可以发现，没有说到对应mixin的缺点，但是却说了他们解决了什么问题，因此我觉得可以这么翻译。

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +我们将编写一个名为 `withSubscription(WrappedComponent)` 的新函数。它的参数可以是任何 React 组件。我们将传递 `CommentList` 作为WrappedComponent（被包装得组件），但是我们也可以将它们应用于我们的代码库中的任何其他组件。
```suggestion
我们将编写一个名为 `withSubscription(WrappedComponent)` 的新函数。它的参数可以是任何 React 组件。我们将传递 `CommentList` 作为 WrappedComponent（被包装的组件），但是我们也可以传递任何其他组件。
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +组合发生在 React 渲染级别，而不是直接调用函数。这就是为什么被包装组件或者用 `createClass()` 定义的，或者 ES6 类或是函数式组件是毫无关系。如果 `WrappedComponent` 是一个 React 组件，则使用 `withSubscription()` 创建的组件都可以可以渲染它。
```suggestion
组合发生在 React 渲染级别，而不是直接调用函数。所以说被包装组件无论是用 `createClass()`创建的 、 ES6 类组件或是函数式组件都可以。如果 `WrappedComponent` 是一个 React 组件，则使用 `withSubscription()` 创建的组件都可以渲染它。
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +高阶组件是一个强大的模式。如果你想进一步自定义它们的行为，你可以向它们传递其他参数。毕竟，他们甚至不是React的一个特征。它们只是接收组件并返回包装组件的函数。
```suggestion
高阶组件是一个强大的模式。如果你想进一步自定义它们的行为，你可以向它们传递其他参数。毕竟，他们甚至不是 React 的一个特征。它们只是接收组件并返回包装组件的函数。
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +如果你在 mixin 中看到渲染逻辑，现在是时候提取组件了！
```suggestion
如果你在 mixin 中看到渲染逻辑，说明该提取组件了！
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +> 定义组件为函数式组件并不是必须的。使用生命周期钩子和 state 也没有错，他们是一流的 React 功能。我们在这个例子中使用函数式组件，因为它们更容易阅读，并且我们不需要这些额外的功能，当然使用类组件也可以正常工作。
```suggestion
> 定义组件为函数式组件并不是必须的。使用生命周期钩子和 state 也没有错，他们都是原生的 React 功能。我们在这个例子中使用函数式组件，因为它们更容易阅读，并且我们不需要这些额外的功能，当然使用类组件也可以正常工作。
```
first-class 有翻译成一等公民的，但是这里的意思更偏向于是 React 本身就带的，大家都是平等的。

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +我们发现的另一组 mixin 是提供和消费 [React 上下文](/docs/context.html)。上下文是一个实验性的不稳定特征，具有[一定的问题问题](https://github.com/facebook/react/issues/2517)，并且将来可能会改变其 API。我们不建议使用它，除非你确信没有其他方法来解决你的问题。
```suggestion
我们发现的另一组 mixin 是提供和消费 [React 上下文](/docs/context.html)。上下文是一个实验性的不稳定特征，具有[一定的问题](https://github.com/facebook/react/issues/2517)，并且将来可能会改变其 API。我们不建议使用它，除非你确信没有其他方法来解决你的问题。
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +然而，如果你已经使用了上下文，那么你可能已经用这样的 mixins 隐藏了它的使用：
```suggestion
然而，如果你已经使用了上下文，那么你可能已经用这样的 mixin 隐藏了它的使用：
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +我们认同在 Context API 稳定之前，隐藏使用组件 Context API 是一个好主意。但是，我们建议使用更高阶的组件而不是 mixins。
```suggestion
我们认同在 Context API 稳定之前，隐藏使用组件 Context API 是一个好主意。但是，我们建议使用高阶组件而不是 mixins。
```
高阶组件 专用名词

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +有时，人们使用 mixins 来选择性地将日志记录添加到某些组件中的生命周期钩子中。在将来，我们打算提供一个官方的 [official DevTools API](https://github.com/facebook/react/issues/5306)，可以让你实现类似的操作，而不必触及组件。然而，这仍然是一项正在进行的工作。如果你严重依赖日志 mixins 来进行调试，那么你可能希望继续使
```suggestion
有时，人们使用 mixin 来选择性地将日志记录添加到某些组件中的生命周期钩子中。在将来，我们打算提供一个 [official DevTools API](https://github.com/facebook/react/issues/5306)，可以让你实现类似的操作，而不必触及组件。然而，这仍然是一项正在进行的工作。如果你严重依赖日志 mixin 来进行调试，那么你可能希望继续使用这些 mixin 。
```

2023-02-22 02:37 UTC, daochouwangu commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +Mixins 在传统场景下并不过期。你任然可以通过使用 `React.createClass()` 继续使用它们，因为我们不会进一步改变它们。最终，随着 ES6 类得到更多的采用，在 React 中的可用性问题得到解决，我们可能将 `React.createClass()` 分解成一个单独的包，因为大多数人不需要它。即使在这种情况下，你的旧的 mixins 也会继续工作。
```suggestion
Mixins 在传统场景下并不过期。你仍然可以通过使用 `React.createClass()` 继续使用它们，因为我们不会进一步改变它们。最终，随着 ES6 类得到更多的采用，在 React 中的可用性问题得到解决，我们可能将 `React.createClass()` 分解成一个单独的包，因为大多数人不需要它。即使在这种情况下，旧的 mixin 也会正常生效。
```

2023-02-24 11:49 UTC, awxiaoxian2020 requested changes

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +## 为什么 Mixins 是破坏性的 {/*为什么-Mixins-是破坏性的*/}
```suggestion
## 为什么 Mixins 是破坏性的 {/*why-mixins-are-broken*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +### Mixins 引入了隐式依赖 {/*Mixins-引入了隐式依赖*/}
```suggestion
### Mixins 引入了隐式依赖 {/*mixins-introduce-implicit-dependencies*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +## 从 Mixins 迁移 {/*从-Mixins-迁移*/}
```suggestion
## 从 Mixins 迁移 {/*migrating-from-mixins*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +### 性能优化 {/*性能优化*/}
```suggestion
### 性能优化 {/*performance-optimizations*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
>  #### Solution {/*solution-2*/}
```suggestion
#### 解决方案 2 {/*solution-2*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +### 上下文 {/*上下文*/}
```suggestion
### 上下文 {/*context*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +#### 解决方案 {/*解决方案-3*/}
```suggestion
#### 解决方案 {/*solution-3*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +#### 解决方案 {/*解决方案-4*/}
```suggestion
#### 解决方案 {/*solution-4*/}
```

2023-02-24 11:49 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
>  ### Other Use Cases {/*other-use-cases*/}
```suggestion
### 其他情形 {/*other-use-cases*/}
```

2023-02-24 11:51 UTC, awxiaoxian2020 requested changes

2023-02-24 11:51 UTC, awxiaoxian2020 commented on beta/src/content/blog/2016/07/13/mixins-considered-harmful.md
> +#### 已解决，复盘一下 {/*已解决，复盘一下*/}
```suggestion
#### 已解决，复盘一下 {/*solution-revisited*/}
```

2023-02-26 05:15 UTC, awxiaoxian2020 commented
@favorhau Could you please fix conflicts?

2023-03-20 09:14 UTC, awxiaoxian2020 commented
最新的文档已经不再包含这篇博客，暂时予以关闭

2023-03-20 09:14 UTC, closed without merging