fit(cn): lack of translation
reactjs/zh-hans.reactjs.org pull request #974
Opened 2022-11-07 08:45 UTC by GarlicGo

有一小段内容没有翻译，不知是不是被遗漏了，简单进行了一下翻译不知道合不合适。

更改前：
But as the Web became more interactive, logic increasingly determined content. JavaScript was in charge of the HTML! This is why **in React, rendering logic and markup live together in the same place—components.**

更改后：
但随着 Web 的交互性越来越强，逻辑越来越决定页面中的内容。JavaScript 需要对 HTML 负责！这也是为什么 **在 React 中，将标记和渲染逻辑耦合在同一个地方 —— 组件。**

2022-11-07 08:48 UTC, NewVo1d approved these changes
你就是我的神

2023-02-14 13:30 UTC, GarlicGo commented
> 我不知道“耦合”一词是否合适

我也感觉“耦合”的含义貌似不是太精确，如果改成：
这也是为什么 在 React 中，渲染逻辑和标记耦共同存在于同一个地方 —— 组件。
这样会不会更顺畅一些？

2023-02-14 13:36 UTC, awxiaoxian2020 commented
> 

我觉得没问题。
cc: @daochouwangu

2023-02-14 13:39 UTC, GarlicGo commented
> > 
> 
> 我觉得没问题。 cc: @daochouwangu

OK已经更改啦

2023-02-14 13:41 UTC, awxiaoxian2020 requested changes

2023-02-14 13:41 UTC, awxiaoxian2020 commented on beta/src/content/learn/writing-markup-with-jsx.md
> +但随着 Web 的交互性越来越强，逻辑越来越决定页面中的内容。JavaScript 需要对 HTML 负责！这也是为什么 **在 React 中，渲染逻辑和标记共同存在于同一个地方 —— 组件。**
```suggestion
但随着 Web 的交互性越来越强，逻辑越来越决定页面中的内容。JavaScript 负责 HTML 的内容！这也是为什么 **在 React 中，渲染逻辑和标记共同存在于同一个地方——组件。**
```

2023-02-14 13:46 UTC, awxiaoxian2020 approved these changes

2023-02-14 15:13 UTC, daochouwangu approved these changes

2023-02-15 08:48 UTC, merged